apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web
  namespace: calibre-web
spec:
  template:
    spec:
      containers:
        - name: calibre-web
          env:
            - name: DOCKER_MODS
              value: linuxserver/mods:universal-calibre
          volumeMounts:
            - name: custom-init
              mountPath: /custom-cont-init.d
              readOnly: true
      volumes:
        - name: custom-init
          configMap:
            name: calibre-web-init
            defaultMode: 0555
