apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: flux-system
spec:
  suspend: false
  chart:
    spec:
      chart: ./k8s/charts/servarr
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
      version: 0.1.0
  interval: 30m
  releaseName: bazarr
  targetNamespace: arr
  values:
    app:
      name: bazarr
      port: 6767
      image: lscr.io/linuxserver/bazarr@sha256:ac284d3fda9ee7da8b15197dc51f0d7a2a1da98549bee99a3d924d3e94a5e7ed
    database:
      environment: true
      mainDatabase: bazarr
    legacyConfig:
      format: yaml
      path: /mnt/Data/apps/bazarr
    exporter:
      enabled: true
      port: 9708
      image: ghcr.io/onedr0p/exportarr:v2.3.0@sha256:af535d94061cf97a52e1661945ffba78c03f9443eae7c0da1a80a5a4be56b520
