apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lidarr
  namespace: flux-system
spec:
  suspend: false
  chart:
    spec:
      chart: ./k8s/charts/servarr
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
      version: 0.1.1
  interval: 30m
  releaseName: lidarr
  targetNamespace: arr
  values:
    app:
      name: lidarr
      port: 8686
      image: lscr.io/linuxserver/lidarr@sha256:67887807b13ae025c0fe979da298347c8609969087ab064c81d8e9acc1e06bbf
    database:
      logDatabase: lidarr_log
      mainDatabase: lidarr_main
    legacyConfig:
      path: /mnt/Data/legacy/servarr-seeds/lidarr
    exporter:
      enabled: true
      port: 9709
      image: ghcr.io/onedr0p/exportarr:v2.3.0@sha256:af535d94061cf97a52e1661945ffba78c03f9443eae7c0da1a80a5a4be56b520
