apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: flux-system
spec:
  suspend: false
  chart:
    spec:
      chart: ./k8s/charts/servarr
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
      version: 0.1.0
  interval: 30m
  releaseName: radarr
  targetNamespace: arr
  values:
    app:
      name: radarr
      port: 7878
      image: lscr.io/linuxserver/radarr@sha256:a45b5ab0f850f39edb4cc9c95bbd967b52ddc3d4574a4dfb45561177db6c88f4
    database:
      logDatabase: radarr_log
      mainDatabase: radarr_main
    legacyConfig:
      path: /mnt/Data/radarr/.config/Radarr
    exporter:
      enabled: true
      port: 9711
      image: ghcr.io/onedr0p/exportarr:v2.3.0@sha256:af535d94061cf97a52e1661945ffba78c03f9443eae7c0da1a80a5a4be56b520
