apiVersion: ENC[AES256_GCM,data:gCc=,iv:RCU4amk78VWO7AByrd6l7lIVWwXeZG8BI9/wYWUeG7k=,tag:oeGEihggJ8WKSkwaCoEczQ==,type:str]
kind: ENC[AES256_GCM,data:lpcde+6l,iv:j+ma33JWwvOr47nrspWVgFQ86hsBJQ7JunNA2wav96Y=,tag:MMwNqpudv8TSVhB8Jd9zuQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:OxokdsFdyV2OOPo=,iv:0yUJWEdy1lsRrNWB97raegKUFKh1yxAhvjUUW0hxr4o=,tag:jd40JgJrAl0NytlTWUBcRQ==,type:str]
  namespace: ENC[AES256_GCM,data:CKmRyiIneg==,iv:+7RGmd4gvwVrE3xPdtCXBpxSNmqvkV8AOyEUDrZdMw0=,tag:pehoUVNaHhi885bH6po8Qw==,type:str]
type: ENC[AES256_GCM,data:sy1qScW9,iv:wUU2bPIq+4ZU+PRUg2VSRbqXeSlL4bU74cI6xxEA8iw=,tag:H+P1VU0hSG54MOyNyktshg==,type:str]
stringData:
  FORGEJO__mailer__ENABLED: ENC[AES256_GCM,data:qNYBBQ==,iv:jpxzPzt5BNmPUD3WTKWvHrDz2/20RlN1G/NmmqHGgmI=,tag:dJhrh+Iy9v0G5iSHaMKVLQ==,type:str]
  FORGEJO__mailer__FROM: ENC[AES256_GCM,data:ohqWIXxYOk+CNlJ6dZgLrp0UdVnN1VUTc/pt7w==,iv:QqOr6L8hjSqk8HySJB3YWrdtUa0RuRNTBSUhNbqOU/Q=,tag:UPHI9H+Qxgsdr2UaXhUDsw==,type:str]
  FORGEJO__mailer__PASSWD: ENC[AES256_GCM,data:eNHdGOYCHyQJM4M9aS7qyUHVXDSJVeUjfarzO+iPfKfesFzL,iv:mTsxs5l+7+ZFZJOK56ocFlgBkvoR4fgD0SuQLCLov0c=,tag:dtwwAAYB8RS7jasvK7OSQQ==,type:str]
  FORGEJO__mailer__PROTOCOL: ENC[AES256_GCM,data:XvfnGEk=,iv:ru78qo3Ou1L5RIeUeSYYGmyFWhdBZX5/3gCw782gV1o=,tag:1o3T+Znp4qx0N9jsSl3zbQ==,type:str]
  FORGEJO__mailer__SMTP_ADDR: ENC[AES256_GCM,data:E6pXQJaDu3CC4I+9rBiH,iv:wDkzLQLzZ9NVkbFp9NAL2MpeKrvjjHc+/XQzejAqux8=,tag:bVF9B+WaGNPDEFmpFmSHaw==,type:str]
  FORGEJO__mailer__SMTP_PORT: ENC[AES256_GCM,data:RuKMJA==,iv:Pj2ByJ5bB0oDM/CGJO9YLggm4gD8hpp5Azs0AX0oT94=,tag:UKjCsvU0oy3qFNCmcLh1HA==,type:str]
  FORGEJO__mailer__USER: ENC[AES256_GCM,data:4DXaMvGq,iv:CsF/0oRtuqqLboDUbuo6Yl2bnjSu550XzxNrWa6UVjc=,tag:cQHd+wsO1WF1kC0ho3MW3w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZU80cm8wK3JqeUx2QktV
        ejMrTmcwQXc2M2NEdHk0MVU4VCtBMTIzT2pFCnNSY0dQRXhUdDlQM283MXBWMHRO
        SjB4N2grQi8zSFZhQzF6cWhIL285YUkKLS0tIHlRcldDUVF2b2Z2VUl4b0k3ZHlj
        NUtTQnUzVHkzRTRoRUYwQ1NPN2J3LzgKpmEZTTaBKjJoxV22u5AIedF/nZVl/Mai
        N1TOuWfqSr94Oh2wSWBq9HhY5pZrPriJrkeu1OduDCz0mBJzkulCwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTmJLaGhkemFRaGc3cmtP
        NGRyNFVpdnhRU3c2MEc0eXo0L3JERnNadEFnCkRILzhvblVHWFhBbGxlU284aldo
        MmQzSlNRUi9yc1NBb1NnbXZUcXVWZUkKLS0tIGsyeGVMMTc1Y25xVml0Z21ybDR3
        SlZCZWUraTcyd3o5TXVmVnlVakNXME0KqpxfpH0WALaArjh3GAqBk+4GRKRqmqSC
        2fXpy8Ikg2dXxzZvOV32y0PiRl7MbBcdrDCKk0hwFh6pXv3NCGLtuA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRckIwdUVqZ21UMEFFVUwr
        Ym9pZWF3dXQvNHh0UXplenRxdWlSUElVcHdjCld6ckZZZlFaaXRmTWlDTllHT005
        K3dnUDdpZHowQmI1YzdWTHM1WUhhT1kKLS0tIFJPMTQ1M3BuRUlYWkhnSjA3Nnl3
        a2w3NDZJdUFTNTF3YndCeGQzbzBNUVUKnB4DQhT4JxzH6L7nt+m5FQUhgFR8jcxh
        Cxh5veIfINstfUwn7smxI96YDHIZDEs0XfMi3TTUBdIIW2veNuYvAg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tdgfvwl4qdptyvgxju3rwz9uh45hz422txzcgsrwm4f4f96x558skzxklr
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdWN0aDJEL0VaOXZaQlNI
        UWJocHJRTUtwemtvSzhSQmZhZzNqS0pjLzBzCnFQM0tKNTg5amN5dzZ4cURUOXJr
        WDQzbmdpQVJMazVHK3VTekV4Qmw2UGcKLS0tIDJTak9tR2FvQ1YyM1NUUUpXSFpn
        QkJBbWV5eFpncTMzT2lLaUsyRWs1bW8KbAAGiHqSMADNsnZKVWbcllBw5vHv79g5
        a8NCZ5ucp3KLBcbpfJB6kTH9EtkUCWYXjOMWiutbBKTywCodYruG0Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bHFQR3d5aUtBZk9QdVRz
        R1hDOWUvZGZJUlJkTVhmS0YwRVdzRm1sVWpNCkxpckI1ZktMNk9UOW9URHhKd1ZB
        MVRSSGJYVENma3VLVEExeExzc1RCdlUKLS0tIGk1b3A4c3ZpbzV1aE5vcDFwY1Q5
        UWlYTkJ4eitQRHhMZnl0cTFKVGhENzgK0Id59JsbCyTV66NnecoCZfW1IqfC01rG
        hprQwXKQgVI0H7yHJ4vtU9aCRpX4GcR7gHic33Dr+G4DNIJx7ocHFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMllad2YzZHNMUG1TMmh4
        ZmZKR3JyR1c4VGFBSXUwSEJpQnNySG4rUEdzCk5pbnBpc2JQWmo0VVBIa0tidWFD
        REgzejVTaFYzbStGRnNMYlBTWVlQL0UKLS0tIHRENXJUbk04bjJLdTRGQmtWa2Fa
        bU1GOVJ4Q0sxTGFaM3N5Y2NqVnRtdzAK3zofnGQixqdaOWRER/NEzMkiciVX10st
        lQgxLecIyopqtcnoxW8IeAXsqW6AvEm5bQHs6watOOO1AjGMgLjASg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENmF5T28rWk83eEI4Yk81
        T3ZHNnZoaUhGeThXYlBRdVhXZHRLMzFEc2tZClBTejA1Y1pHakpMcnJmU0NGUU9a
        OE8rSDlWeFIyOTlUTlVsNG5OY2hZamcKLS0tIFZLVzFXcCtyMktEcXhJNmw5Uitw
        ekRkelZEMEdIUUhFbkViakJhVXZZaTgKP++O+OyPACkB5iVT9eHdQXBJZd7zs1l7
        mgBSO//OkPhXIoumLpjWjAW4zf70CwLsk8nVBtjbdNhFaetUfJuvrQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZFoyay94aUowR3dHYUgy
        ek1Oa05wWEQxVU14TmRadjc0VFhDakNwT2wwCmNzM3J2Z01PVEZZSWs0L0JEVUxN
        UnB1Unc3bjNVQmpPVkl2VVA2TDIrcmcKLS0tIHNheXRHODZoaDlabkwybHF0aHhW
        c0VCZHpkcktkblE0VlhFbjJuNUpSYUEKY2bfx0CjCuAngqsoz6pYvj1f4bNRtHMf
        TMmJakNpkafj91W/GaDMK+MGuLthOTvGFGEbf+Q2S61W2A8N17kmHQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMFVUTnNoL1VxQWhQbXly
        TUZtMHc5WHdGUXlibk9CY2FTL0NjTzgvWmw0ClZ6RnVwekhKQmVrSUdubm1iMldJ
        aUVzc1EzNS8rV2VmKzhNck9CanZVUHMKLS0tIFkxbUVpRjQzOU51aEl2enJYb3JX
        c2cvQTlCRjl5dC95R0o4Wm82eERqRXMKq4RosJ3zlLYGQI+oF5cnd3/u+IXIouk3
        i4aZJr2c4VEkiZk3mjkQhd4K1SYGhYqrJ7pUM25eSX8rlbpa8kZTcw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QUlsOXpZMmNUby95R3or
        VEQ3ZnBRMEhWY2M4TUVoTFY3TnlNVkNXbFJFClpIT0JrZlMvaCs2YjRobnNnQm9h
        QlQ2UFBvWGhxYm91N1NVVm00Q1lsWXcKLS0tIE9Nd3RFYng5RGhrVzhwUC9uNk5O
        bHhuRFdCbyt0eExmeXVTTEtqWFZMcEUK9YS8QzlswAJbNzA2f3iCI035qftIQtbf
        xw5fQ/+c50h74Z5KG3SXdq1fFPCDPGc30dt7Zn52l8mIi343DfjLfw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1l5t62uzsj05pzftv9wg6s346csxyq202vxmmyyx8gwy8zu2nrfrs7v2a4z
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOE1jRnp0Mi8xYVBtK0JS
        NzhlVHBhZURQbGFlTElBMHpLNTEzd1dCVzNjClducW9Kd21ZUlVpdXR4Q0lrSm9R
        c3lsb3ZuckN3NjlxcDQ4OEJqNjZDYUEKLS0tIFAwc0FyNU16R1oxbnRac0todVNE
        YXVMUEZrTFVEUG5KU2F3TnVFcGw5NFEKjlio3jQg1T448j8UhBTDURGQ1LEh02kR
        l8ztW/k4V66T2mz37mKXRdbD8oueCzWeMmj+aEfV21iGNz6y+UoHxQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-29T22:49:20Z"
  mac: ENC[AES256_GCM,data:GUDO54NTrXLIOAS72+QI+/lpc3zjbCisuQyhxDrwZfnWjXa6kAaWLwmjeKa4K8kzT4JsvLYdHoH8MkR2KTZt7P4lqtidT9Zxi6WzizKgIgAS8LfPr2MBgOILDNMMWibaSHK6bBvkQGLpj0zyA14bigJs2W3Z+759/SsFJhIqAQo=,iv:DSYYhUTFe9fJfMULR9lC9/BuSRtQdS9AkrpM/R6tz2E=,tag:Dru9qw0koGdokHf8yVL07g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
