apiVersion: ENC[AES256_GCM,data:gCc=,iv:RCU4amk78VWO7AByrd6l7lIVWwXeZG8BI9/wYWUeG7k=,tag:oeGEihggJ8WKSkwaCoEczQ==,type:str]
kind: ENC[AES256_GCM,data:lpcde+6l,iv:j+ma33JWwvOr47nrspWVgFQ86hsBJQ7JunNA2wav96Y=,tag:MMwNqpudv8TSVhB8Jd9zuQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:OxokdsFdyV2OOPo=,iv:0yUJWEdy1lsRrNWB97raegKUFKh1yxAhvjUUW0hxr4o=,tag:jd40JgJrAl0NytlTWUBcRQ==,type:str]
  namespace: ENC[AES256_GCM,data:CKmRyiIneg==,iv:+7RGmd4gvwVrE3xPdtCXBpxSNmqvkV8AOyEUDrZdMw0=,tag:pehoUVNaHhi885bH6po8Qw==,type:str]
type: ENC[AES256_GCM,data:sy1qScW9,iv:wUU2bPIq+4ZU+PRUg2VSRbqXeSlL4bU74cI6xxEA8iw=,tag:H+P1VU0hSG54MOyNyktshg==,type:str]
stringData:
  FORGEJO__mailer__ENABLED: ENC[AES256_GCM,data:qNYBBQ==,iv:jpxzPzt5BNmPUD3WTKWvHrDz2/20RlN1G/NmmqHGgmI=,tag:dJhrh+Iy9v0G5iSHaMKVLQ==,type:str]
  FORGEJO__mailer__FROM: ENC[AES256_GCM,data:ohqWIXxYOk+CNlJ6dZgLrp0UdVnN1VUTc/pt7w==,iv:QqOr6L8hjSqk8HySJB3YWrdtUa0RuRNTBSUhNbqOU/Q=,tag:UPHI9H+Qxgsdr2UaXhUDsw==,type:str]
  FORGEJO__mailer__PASSWD: ENC[AES256_GCM,data:eNHdGOYCHyQJM4M9aS7qyUHVXDSJVeUjfarzO+iPfKfesFzL,iv:mTsxs5l+7+ZFZJOK56ocFlgBkvoR4fgD0SuQLCLov0c=,tag:dtwwAAYB8RS7jasvK7OSQQ==,type:str]
  FORGEJO__mailer__PROTOCOL: ENC[AES256_GCM,data:XvfnGEk=,iv:ru78qo3Ou1L5RIeUeSYYGmyFWhdBZX5/3gCw782gV1o=,tag:1o3T+Znp4qx0N9jsSl3zbQ==,type:str]
  FORGEJO__mailer__SMTP_ADDR: ENC[AES256_GCM,data:E6pXQJaDu3CC4I+9rBiH,iv:wDkzLQLzZ9NVkbFp9NAL2MpeKrvjjHc+/XQzejAqux8=,tag:bVF9B+WaGNPDEFmpFmSHaw==,type:str]
  FORGEJO__mailer__SMTP_PORT: ENC[AES256_GCM,data:RuKMJA==,iv:Pj2ByJ5bB0oDM/CGJO9YLggm4gD8hpp5Azs0AX0oT94=,tag:UKjCsvU0oy3qFNCmcLh1HA==,type:str]
  FORGEJO__mailer__USER: ENC[AES256_GCM,data:4DXaMvGq,iv:CsF/0oRtuqqLboDUbuo6Yl2bnjSu550XzxNrWa6UVjc=,tag:cQHd+wsO1WF1kC0ho3MW3w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVa1NKWUJPSEE4SWtaSXFX
        Y2VsRy82QnpZdG4vRFF5RktSeE9XV1NLNEVNClQ4TnV4UlNML2JKek1mUnVBcmcr
        OUpBOHQvbSsySE8rTmg3YndDR3Q0RmsKLS0tIHJxZTVNYXVoWDlnNjI0UEJLMFFh
        WWJMb1RTWW9CNVBFa0hNdldtalVFRGMKVAbd4u2wLbleBR17pTlryEVMuSNrdtS3
        dVJApsMuyf8UeqBUllvhhvJePt3rqmwpwOtAM9FnwsRhWI4Jjv1Ciw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNFpLNm5seDZVZnVFTGpy
        WTZ1MDRiWmJDYjlrRFlVWDdSalFEdUtHSjA4CkxjTFUxVmJwc0JxZVJ6YWVEeFd4
        czRhdlpaeG9iUzlyYmtreUw2WVQ4Q2MKLS0tIGRwWWdCRWgwTkFPUVR0WDcydlJs
        Yy9NQkFrQWxLQzUvOGFhN0xiUjgzSWMKCSZ84bfuKLMSliH/TNONOerchPTH5Bwq
        ZYardlEyx+8KulTvL6f/xzBVw9rr77zMsgMhV8xbfoXoBvZ4yDMPkw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreUpZaTVqU3F5RXpSaU5B
        OHphOVdlekhYTW1oS2U4UFZTQnNXZ0k4Zkh3Cm1YNTZSUFJZVFJNZGR4WEtzQVdR
        RzdBeGk0ZkpZcENWVGNqd3NtT1d5Tk0KLS0tIC94ZEVIRTBNb0ZHUlB6MGlJWk4z
        K3ZTRXlzeG9wK2JaTGtabjE4NVJnaE0KzUJYtKpF7kK0P6Lcmmw6FTUomJtXgVxs
        sC4AVCAgWWQ0YWbM4em1Lxsg5PybiT5Ee3f6GIDJyI3iQXQNxoEKLg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbDk4alAzOGgycHJ1OWhl
        b1lRS0ZTdERvK2d5SGkzS0h3b1pIajNMTUd3CmNsM0Z2ZzNLYWdCa0ZISTVSbExm
        VnZrSldEMS9BdW0rK2VoU1d0Yk14MG8KLS0tIEU2OEp5RytwcWMzSW9jNEMvTnps
        WGdjeFI4Y2JoaVFCVGtZYWkzTmN5VFkKW9jcVysvbZhmMpUL7zVqD84hY0l1CFaM
        T2+UUs5QwKJ5Z+k7DWHhWBmyiRA9pM6fKV6JP+NPT8O/HJhI60Kbkg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5T040NVBZcENxTEtIUlRE
        RnJRMGk4bnRlc1A4NlhWSzdkVzlTUE1DMDEwCks4SlhUL2lDdzRDNkhlSDluVFgz
        TkM3dVM4WC9wTzB4YmR3OTF2N244SXcKLS0tIDV1dUVDNnlTNXI4Wmw2WUtFNVc3
        OWkyNDgwVSt6SmdEUmwwbGJhelNOYW8KAHtWBm/KrYRFcq/WBi8psS38sdU7Fxw/
        qamBgZ8g15VhYH2+MBDn8gkRfZ3fC0a+1ogrLJHS7L0kNvrS9H32Mw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdDR3SWpYN3M1cEpWbDg4
        NWJUb25xVFg4T0xXc3VEaSt4SlhwZFY1Z1RrClJ0ZG50Q2xFRjE4b0tSMWU2NlNn
        WDZIU3RMR3JyTEVVVFZVcW1acFR0Y2sKLS0tIGRYbS8yNjdCYzBvT2JJUFNORzNs
        NFdMVlJIdTdsWnlnVEZDandEeHFjMFEKci6F86S0QPdKQgv5wO6t8T5XC1BV537+
        TmKrdRbTawE3R2ymZTvH25Gxm8F8YYoy4Rbfd4xxN3QFvpNpXM5VEA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0b2hOcVAyNWxKM2ttajBy
        L3dyS1FQZkM1S0hQTElMaGxMcktMQy9JV3hrCnpXYVZDeHhEakg2UmxNV3hBeU1R
        OVNPVnVIUEJCbFlFTi8zLzhqNjJVME0KLS0tIHdDVnV1MU1ZMDdPYzN1Mk5GWWZh
        NUlqdlZkeEJxbUp4eW1zMHRmWnhib0EK6wJQ3pX/NRwwNWTLUhERYd60xRK4JgOk
        T9zwZWHeNC4So/6X6NeP+WMbFtjh58D36SGml9kvt9XWu7ZIuYPt2A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMk83NlRxZTdBbi9VbzRP
        U3ErTnhJU1ZEKzgyOTlVUkhjNUlaaHRpd0c4CmNqWmVLRjFZL2RGRm03ME94STdy
        RWFhakJVYWVGeitRUWtkZ3lsVEhNbzgKLS0tIEcxemJyZGg3YTdZaHBEN3NVMEh2
        OUsvWnh0ajJsOGtJUmVFc2dPUW9xMUkKBvQ6ubIhR4UsBZ1Apq4cUxMR/Uj51AFZ
        eK2IgglqeoQ/wEcMuvyq7CPdOaIaaREdMWAGVYVi//y28EGo0/7DrQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcWNkQ1ZDaUpHRVJ1OWVa
        NDdzU3IwS0thRlYrNGZNOWpZWEFQM3Nhb1VzCkNpVG93b1BGQmFzLzJIMGRFa2ZD
        L2lha2NyRXhtQ2d3YmpLU1BHbjlsYm8KLS0tIGpvOGJVdHhGbDZDQTNhamIrR0hh
        OGpOV1V1YmRVK0xqbEU5Zk91eWxIQ2sKBrPvkTVLgxQCbswCgHWy9TftAPKk1bfJ
        NlnDh7XFof5+sLg+F5mmk/lyyQdcHqQcSM0je9n4Se938Rn7xCgfBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-29T22:49:20Z"
  mac: ENC[AES256_GCM,data:GUDO54NTrXLIOAS72+QI+/lpc3zjbCisuQyhxDrwZfnWjXa6kAaWLwmjeKa4K8kzT4JsvLYdHoH8MkR2KTZt7P4lqtidT9Zxi6WzizKgIgAS8LfPr2MBgOILDNMMWibaSHK6bBvkQGLpj0zyA14bigJs2W3Z+759/SsFJhIqAQo=,iv:DSYYhUTFe9fJfMULR9lC9/BuSRtQdS9AkrpM/R6tz2E=,tag:Dru9qw0koGdokHf8yVL07g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
