apiVersion: ENC[AES256_GCM,data:Fdg=,iv:OI6GlKIhCua+vfdgBOImG865xU8D53LIHMKDUVLCCzA=,tag:ffYnu19cX9/qMemEXM2yiA==,type:str]
kind: ENC[AES256_GCM,data:HBwMO+xA,iv:nIX+LdUO3VS/yaoOrgDIKPocItEY0IrylrlNB+O2UJQ=,tag:9OmnqFxKLEdyk1KAa1c6qw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:zFfnQJfwjEaiK7lgY0egdiCR,iv:n+0tgDPpZMggtQ2Ufkgk+lT4OIDTyuWfC1lH8sPZGDc=,tag:bWfj6LwGEw8fBM5kBkp2BA==,type:str]
  namespace: ENC[AES256_GCM,data:+6ldko/gpeyZDQU=,iv:mJEOdhs9Tdj3WnB4Le8FiBzmMTBT36SR7qP7WysbcmU=,tag:Ur325p4aQICg3aYBZK0KPQ==,type:str]
type: ENC[AES256_GCM,data:/xYi48K9twueOL8Rt04FAo+teUb5wOyu,iv:0CEsXr2ztu52VfpKI0DSS4RhZx0trx9DFD2NJ+FaBWE=,tag:h8DAAcNT8xdVaH7GcizaMg==,type:str]
stringData:
  username: ENC[AES256_GCM,data:pMutlsjYnpF8,iv:CAipY5VEdgSwbwPS5bNri8fIt9FVq1bfkma80dUuwwI=,tag:rXWJmqlbIb9vWo3+qZF5sA==,type:str]
  password: ENC[AES256_GCM,data:UX3EJiuhFaeCec1EpBWzdDCvYjeRJb48wKK6oWrvemF5Ac2aeB/VT5keCFVSz6kAHJqsBQ8ncHJZE0yJPucI9Q==,iv:9MfUiOIJ0QslZgbSWa8AxSo2AS+4TgDdHTF4UuzHt5c=,tag:LasA446KqMhqUQt16jdsUA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCK3duS1QvT2tXd1dvSUtx
        RkFmMHFnbnJKbjJ0b1Y2d0RpQXJVNjBNdldvCkh0WjZwMUtVUjNRZWcxQ3NWUzFC
        R3hwUDV5SUR5OENnRWtONnJXSllMYWcKLS0tIEJyTk5NNFBVWUI1Y1hrL3lLclRY
        UFdyK2pHdDBMMEdNdSs5alZhMUdYSWMKtQGYjukOwqf1WDr4ux+QrarPgEwvhwlH
        9so3n+sneZjDEQ0fqRgs//sEe6Xhg9ERC8xGm5kgWjB0vBrAxfrWXg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRmRUUEc4YVJGTXdiclVx
        Yjl4NVdET2RGelFkZEZNeGtMWHdGR1htZXlRClJENFNEbjZ4eW82NGZaNVBqeEo3
        Vkx5QS9vY1k3Q21XRUp6bEQ2blN4RDAKLS0tIGpVR1FiUFZLZUlLVTFwdzhnS1Qr
        YjB0dmhCRzBSbW9TTUx0RXJjWm5QS2cKYO8KMMiF4ycR4Ix+li7Dv4efmRm/aFsE
        MgB7IyCEsT7x6qC5Eb5SPHfayhuE+Kl81qYCNVTGS6Oj/2tKZl6/Jw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWFNNZCtncGg5dEVkWVJW
        S3djMjFrL3h0ZE5PcS8zNkJPNDQ0RGNrOENrCnJIaWpyVGlHcnBSVmF3N2dVVnpM
        NlJmdEROUDBpZE8xS1lsVXR4b2R1M3cKLS0tIHJHN2RUTGdFb2N1d0EzVnZrUUty
        SVZSblllU1NSM2pZeGR1YVViTy9mdXcKgb/yiVm+Ux8sa6IcsGCaPlse3ryuhbbe
        HkwIpbgrfyH8iIaso95clt2GxhN95Vwqxl9ebF0xZ8EauAZ9DLKyEA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tdgfvwl4qdptyvgxju3rwz9uh45hz422txzcgsrwm4f4f96x558skzxklr
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQnIxSHNUemhEdS9TaS9j
        Tzd2bWFYbzVLZ256T3l4VHBzVEEzVjdWWlZNClBIQktPcnBtR2kvQWdadllUU1dW
        MGNTYzZIQ3hlNjRhMG1Idkk1SlI4QVkKLS0tIGMyUUlBcDBZUE5oSFVZekYybDlY
        YUNycGp2eWpVSHd4VkNBNWEvNXhBdlkK/N7RKgn9+9TLjinud5zD5SO6ssIdDw7q
        P/aseYy6DWEr3FrG8wPnGlQoSWwqQVv9qDiVANUzEc6zXp2VZhC2/w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTVZhT1RlQnZtRU9KSmx5
        ZHZJWVVac2lLdE1IU1dzTEFRK09CZGx5K1JFCnRGWHJNcU1LQTJJWVRQeDdaMkFI
        UUNDN2FKQlpuYzNOQ1gxRmNBNGJpVWcKLS0tIGkybzlzdWNzSlZtT21oa2VaOFZx
        OHgvcGUwOGRBdlk2blZZaHIxUjlHa2MKB+Q0WQ73t+tVFqg2jPR5sYFmmbC9D0RT
        KcLNdZ1ICQerMd/IKvOopIlijCs7FgPrQUIYyMIQEDOSVI0f6QRz/g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvS1RBZ3hmUVEwbUVWNjVH
        SFVFNTRSckxIQndSNXBGMW8rRWtVTXcyMUFZCmxtemlKS3h3ekRNdTJFaHF3NUIy
        Z21qS1RUcXZuSnl3b1Q3WlY2LzdJTG8KLS0tIHpZdjJGWERzL0xpY09pL0I1VE9o
        U0NIQ0tObjBFU3EzNUlYVUdEQ2dlcmcKQK3HWkHHCQYj7khtLGiLKqfswJyNixtN
        pVd+4sv0uZSZdjNs+t12UCNYP/GLpo5FUVVbu1N3jahHbkIMFgb9eQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtb01qT1RXSVFlcmlMNzJG
        M25xTFpxMTVSNnhyRkdLUEpQL1JZR3FMelZjCkh1ZGsvV2JqNGtPbDRTc3FUOVZ1
        eENIbTI4RGNjMG9pUWFNekdEb0FxSUkKLS0tIGF6UFdkckJsWU5RSVNFSi9TWGJr
        SHY4b2lYWmlkRUxHV2gzamRNRDJOYUkKLZJESQwr3XuzT8JkwDSPG3aGKWVRT02h
        k+m4okWR8TXnZ7k52E6YGPZMHVqtBwMviBfKMyGhfXHl7OFTdQceUA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZmxmY29XdElkNWdUU2NG
        VTh1MXVyVVVkdlVMUkN4Yi9VWEhmR1ZFV3dBClp5TkhrbFNlcEJkRVpZVUV2aUFj
        UGNpODVOV3g0OEk4b0gwUnY2MnNZemsKLS0tIFl6K1g4a0dnRzBhS3NTNTNXelhy
        MXRtQTNCRmVFN2hnKzFoMTFBS0txU2cK6teVpETSSwIAmF013MQJlXpFsYwpa9Fk
        P6121u7Muj6+Oe0GqOIhi0PYhlx5dpO//En+oNiKLOAslejDJgIFCA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubjdoMkF1YTdRSU5DSFpi
        UGV2RkI1TmViWmtTWVVyK0I5QXg4ekVRemhRCk5oZU50cStRTEdTZEtubUR6Wngz
        elZkbnNyRVNNZmNIcGtnTzV2L3RhYTAKLS0tIFhXTXpVZ2pZbFNwWjB2MWFPWGNk
        MllRTGdzd0EyRENYOUVMdENKRUh5VEUKqUDWy8zLzdDPSgP40WyQQiW37ty01Ghx
        c4SH9u/tp73MZihQK7e7wZqOGcuYI30aNJAxSUWY41BUMnltfjyxrw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQklEaVkrZVpiNm1DcHNk
        RERHQUEwdXl5TE9tQU5iMlBTNlB5VGU3V2lNCnJtdkUrQm8yR3dLZWlucjU0d3Rs
        dmJJdjQxUUVKZ3VwaXN3VURjRjJEdlEKLS0tIG50WjVMRHovR3A4aTVGb0VwMkt5
        dkJEVWNiN2VtazVlSVRUcE9qZTJjamsKcJGPsMYj1EExPqZZ2No65xUC3URKmzUU
        IVKdBkORCiZoWtGiml0ENz5Osqbys5QBsDELNOi1cXQYCKxytiq+SA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1l5t62uzsj05pzftv9wg6s346csxyq202vxmmyyx8gwy8zu2nrfrs7v2a4z
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMkY3ZFM0RnRvQVRpWmJP
        UkVZdXN0K0p4MzJ4YUFVbVpWMHVSWS9wUGhNCk5oYU9icEVkK2U1RFE2d0t1RXIx
        d3NRdExJaFEvTngvL3BLaEd2TWl4RnMKLS0tIG02ZklYa095ZnZKNWpobE53cTQr
        N0ZFa1dJVDJtWEhKQ0tQNmlseDZjMk0K7AEQ2736uDmWhL5HBJwJMpjy16XolGs4
        A2UhmPfp9SJpcdtyyxT8p6VcewjcIB7SAYXQt5IlaFlNyNWM/9SYtw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-09-12T14:21:09Z"
  mac: ENC[AES256_GCM,data:mjDKNYwyytYj/IM8CA7Ky/VgOMyj9HTOS0oNUmGuSQgTQ30z5pWahNXgtB64qdCDsHz2wC5po0YWwyAfgNdKlC73zRH/CmTrjtOYVd743mCL/q5BQK6G8shVJphzeUXk9qWx2Q+pOEXcJbAbLzogEClqi2dWxd1BcCMAhysNyiQ=,iv:Z3Itq8YS4oX6aZ3Uo3chZLDwwzFoJnh/iwRzt590kzo=,tag:08S5M33VRXBpNvIk0VcvWQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
