apiVersion: ENC[AES256_GCM,data:Fdg=,iv:OI6GlKIhCua+vfdgBOImG865xU8D53LIHMKDUVLCCzA=,tag:ffYnu19cX9/qMemEXM2yiA==,type:str]
kind: ENC[AES256_GCM,data:HBwMO+xA,iv:nIX+LdUO3VS/yaoOrgDIKPocItEY0IrylrlNB+O2UJQ=,tag:9OmnqFxKLEdyk1KAa1c6qw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:zFfnQJfwjEaiK7lgY0egdiCR,iv:n+0tgDPpZMggtQ2Ufkgk+lT4OIDTyuWfC1lH8sPZGDc=,tag:bWfj6LwGEw8fBM5kBkp2BA==,type:str]
  namespace: ENC[AES256_GCM,data:+6ldko/gpeyZDQU=,iv:mJEOdhs9Tdj3WnB4Le8FiBzmMTBT36SR7qP7WysbcmU=,tag:Ur325p4aQICg3aYBZK0KPQ==,type:str]
type: ENC[AES256_GCM,data:/xYi48K9twueOL8Rt04FAo+teUb5wOyu,iv:0CEsXr2ztu52VfpKI0DSS4RhZx0trx9DFD2NJ+FaBWE=,tag:h8DAAcNT8xdVaH7GcizaMg==,type:str]
stringData:
  username: ENC[AES256_GCM,data:pMutlsjYnpF8,iv:CAipY5VEdgSwbwPS5bNri8fIt9FVq1bfkma80dUuwwI=,tag:rXWJmqlbIb9vWo3+qZF5sA==,type:str]
  password: ENC[AES256_GCM,data:UX3EJiuhFaeCec1EpBWzdDCvYjeRJb48wKK6oWrvemF5Ac2aeB/VT5keCFVSz6kAHJqsBQ8ncHJZE0yJPucI9Q==,iv:9MfUiOIJ0QslZgbSWa8AxSo2AS+4TgDdHTF4UuzHt5c=,tag:LasA446KqMhqUQt16jdsUA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMG9neUdGSDZZemVSWGVS
        OU1IakIxcTdJRUo4THJrcEVhSEZXYm92NlV3CjNsY2ZNdEhEK05rVEVkbGJZbmpm
        QzhKRzFXbWlBQld6VnErVXFIQ3pjTWMKLS0tIFNGeVFFZWlPQmxaa3F2MTJYclF3
        czVGRjlreGNyazFGa2E1RC9xeHR0dG8KBU75biyA/Uv0BXbE4as6CTheRcqPM2IP
        wBP8hkFMtp6NjB/+wLLTirZUgi10v69DM3LxxYXCLTImK0G4T/Ebpg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOTM5cVBydTRKTSsrc0lU
        UkJuNlRkYnRwVXBPVWgzZjdpbVZuUVhNc1U4Cm0zTzU4ekx3N0hUUnA4dTlFUTg2
        MTZqeWZ5OSs1eE5BOHFPTjl4NUlBOFEKLS0tIFAwdFRiSHN4VUV5M2dKZ3VGeWhn
        ekpGRkZNdG9qU0VHYjhHb1VFMEpLK0kKz0iExFl313TicHnWz78m9cwrusTVDLwJ
        cywxN5RWSXUS1/HMnK3VsuFKc2K71NwIuwgeQql1U30SCy2VxGngRA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZy8wM1JRZjgxUlZQZUkz
        dmlzSUd4QVUzbUhVYW9hSEY4bFR5WGEwcDM4CjA5SFkvTzd3UnZQSVlPQ1ZIcSta
        anR5MFRjd0NxVUFmenRYVlVsc2VlNmMKLS0tIEhZaHF1TmRGWXhzUnNub3RyMXVi
        SmJxZ0FRZDZ0N2dLTmlzZktjV2krVzgKDTVZbsOhVEqAf3JgBA9boYC4h1XFvxTR
        XuhRK/OdJ6PdCbOIX9tGdM2xGfZuGnYYk9Xjat3PXeygOockcIQPNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZFFVTnljMkJWUmlEZGNT
        RWdybHFmZzB5cTUwYnlWNXAzMld4QlBpOVFNClVHNnFBZEpNL3BUMDJiRWFaZVdu
        cllybnRtWk9CdzFvQjRFUTRHcHpTQW8KLS0tIGdNMElTbWFDNHRvaUdPNXh6Y1dH
        OTNmOTlxMWd5elNOMGNZRjg1dm5FTDgKOHs3bQ2+Szt30YkUxUU11ivgZWfoYRmS
        asups3A60F2qEtejX1JqpsoRP58UeKgz0jzwyoR+bogl3Mx9W34aPQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYityYWJsb0VEYklMYjhw
        V2FkUVVvWElURmdOZGF1UjJPR3pEcVFlbGxNCnNUOW90amt4a2tJOXZ4SlNaaDcw
        RTBDZ1FtQUQxRmhnM0VjUmpLQ2ZYZFUKLS0tIGp2SHMxVys4bHl5MC9GZmxJVERZ
        RFlTSlV6MGp4eXNWckU5bldmSksyWjAKfSU7xQorayrwf2aykQGzr4ueemXl9bGj
        Pm23pVCDYdn3gRSEoUv0gKrmncT0E0hbb5RDUO5ndtjLFivEQ1/Gww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPN3B6WnNrNmdjOFlpa3F0
        MDhuV0dSQnRoQ2ROeXN2TzBvaHZMY1M4UzE4CkpkTHJlVjFaYi9KeDJHd0VkSXZS
        M1hPbVRaM2ZwUm9vSFVBNmVCUFY3YUkKLS0tIDJvck5mNWFZL2RyQUpkd2lxM0Fs
        QUx4dUJZeWhCUStxc0JIVDF0MHdJNVUKxj0Mq4KaWW6u58Np6NXBl1PNW2RwmwhV
        9fAjo7ziPpSupGc3VuqKGTaIfDL4NqScb+3m1Pz8mgAEA9Wm70J8FA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSUQ0eTl2N0NpN0x4WDlm
        UlIzZzlsdVkwVlZkMVNkM1g5YnBaeTl1VUc4CkZNUzZNRmQ4WU03QVlIZkhmdUZU
        YjFFZlRoL2k2OHlSYVFEOW55SHhrcDQKLS0tIEd6SHdWZm1WeHEyZ3g5UGM4RjZL
        QjA5N3FSN2lUMmdERDFDZ2VBeDFGM3MKREOmZUtocOFYmXCAvk9ylQofNkfzHswz
        /KJiSeD6BA9Xq+pwc7hto5zwFn9N0QYTdbYEngci3oRkviq3xOB8tg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjazlSa0pYWVAyRVdRVHp5
        VmhpYkR5b1R6QTZTMjFycnJCYXZGZVJtUXpNCkowNUM5SFBKbGFhdGp3OStFNmtl
        Z28yRVpSa0pZSWdyZHZDUmZvL0pSVlEKLS0tIGFTdWhaQ3MzOS93UHhRSkU1VzFh
        WXFKL0ZvNHZyOGwrRm4wQ2QvSWdCSHMKFz9f1eAgs/REQJMCjQkHZ+4dON8K5Dn+
        RV3wMx1u3k+PulVqFGFn36iLbsfAiHUl7GAEzke554MPOXjNVk0dzw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOXB1YWhXUFhvbFlZODJZ
        VHVHZlhTaWtwRFhVQmRDZkZtSFppY1llSGtJClZDZEQxMnJQMXRWc1N4UzM5SzRG
        d25mMmJyQ2hpMVdrT1EwMWQ5cEN4T2cKLS0tIEpWWjVFNG83NUJwTlJ2WTVMcWc2
        V3k5RVVXZzRaaGp2eURSQkcxazBnZEkKWLe4mRQ5udH7DdDf0VWCjbx8iLQAoOWY
        losIhNMTd8tYYkRj9jgxNQmlIsIutgryCOoj9AE/vZly3XLooeSHvQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-09-12T14:21:09Z"
  mac: ENC[AES256_GCM,data:mjDKNYwyytYj/IM8CA7Ky/VgOMyj9HTOS0oNUmGuSQgTQ30z5pWahNXgtB64qdCDsHz2wC5po0YWwyAfgNdKlC73zRH/CmTrjtOYVd743mCL/q5BQK6G8shVJphzeUXk9qWx2Q+pOEXcJbAbLzogEClqi2dWxd1BcCMAhysNyiQ=,iv:Z3Itq8YS4oX6aZ3Uo3chZLDwwzFoJnh/iwRzt590kzo=,tag:08S5M33VRXBpNvIk0VcvWQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
