apiVersion: v1
kind: Secret
metadata:
  name: immich-monitor
  namespace: immich
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:Njp6ZuT/9b4r/JZSiwCOvClLay2o7Nim7ghdkQ4yqsJrpdGyxzAMKzq39Ahxrw5t,iv:4qS45htVce/O/Z0eBVhhn/EVgZQh5+YeHZtk+v7WWyQ=,tag:BRdBI5AGkcHpLgEWYz+Pxg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBST2syeHgvRFJTc28yaXFJ
        dzU4MVJRZEtPVWl2QXp1dFpaV1VLTGNLRzF3ClNNZTZ5V21tN2s1M3E0aUJQV2tu
        UlVOU0o5MWVIcG10WkR3YnNpSmt2TnMKLS0tIHVkdVBHbjdCU2E1OEl0YjlkQlcy
        QzlzK1VTTmF4VktHUjNQOTYxRE40SE0KBDG5II0/AgqLukyWtO5XT9yKl8RfMTpW
        WLlFFvfVpbUskV625qzntuGXEKWfdhh0RUXbngDv8qDlydS/GNQnDw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRktyZnhEWVJRcTZnajcr
        dlQrTHVGTTZCZWJ1cHhFclBiNnBYZDF2Um5ZCndndWF5N2cyaDZWRk9jREVycEd1
        VUpkekN5V09JSFBlRjRKQkZlWXVueWMKLS0tIE1vODk3UGNzcVBKdjFITWlsdmV5
        RTQ0Mi8yQzI5cjNkQ1R5MWFMMm9Cd2MKBeHUmMNiPS+NXNEdn5VG4wIdMzmJ12X/
        41d4Icjy+Dl7iG3cisCAPr7OFgWXEcEaRk1zNbCdOv0raxeOlqLAmw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaVJTTVl3Q1orMjVvY2pS
        RHFNVkJDSktUNmxURlk0M1NoRHdCNHd2bHpnClU0Mm12K0c1akJKc3MwNmNLLzYx
        UE1rcFNVMGdheVg5NmlDcER3QTB6Z0UKLS0tIE1taHNEKzl1TlNadFF1VHdFUmJK
        d1k3ZytCZ216eTV5eitVczlFR1A0YlkKvrtui+SZoR3Jv/oIbi5YgOtWFzA67O6c
        uhsRFGEMGYJTji4AtktxPeaZUHOZUk9Y9XtL+nxDSqSufVrmoQ+SAQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tdgfvwl4qdptyvgxju3rwz9uh45hz422txzcgsrwm4f4f96x558skzxklr
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZFdxK2Nnb24zWnBOUnRY
        dGgveDFNQUZ4N21CQ0UxNzVLMVdraTdhN1Y0CjlxcHl3aXBUdVRucVVCb0w2UE40
        bHFSUEFjTU82TS8vcXpURkVMd0c5cnMKLS0tIEw0eE5jQ1YvTXdKeFhtd3QwcUti
        LzQ3SUQxblFsYk1xNkpqOXRyYWRjckUKrI7cbqzaM8KqdYHMFI98fDHQVrvCtJdP
        JHLDes0pNIVorRLjhNVpSExIm5EEWB7LkYVMLNKn2DMiCH+27xn1qw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQWdPRG9QdUlZZ3ZtcTdD
        MUpTcDRIdUlLRk1VR2Z6UGMrOEdkK2JzSkdNCmpweVFtK1VZWnRYRHZCdGFUMzdR
        OGRGbGFHRnp1YWY3dElvUjJwanJvdXcKLS0tIGU4dVYrVHl6c3FzQmNMMEJ4OVV6
        WUloc3d6akxjTkxBWFROTUlDaEdWUEUKdfqmm+IIIpKxk+/1fbM0BKGW7x3y8z/T
        TeLVFR9GgdIE4Pl53/Mmduc8MiBoM7/TOnYRufozrrm5Rr6EiSZKTw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1eUNKWGFDRXJDMHloS2tu
        LzVORFJTcHJ0Y3VHeEtkcFlLVkdqZzJyNDFRCmhMVm9ETFNLM2NPT0dIb282VmMy
        dE0rOUNFZDNhT3YvWmwzcXU3Q0hEazAKLS0tIExScVFCcDVwa2Vwb3M3SlR1Q1JE
        MTNZZ2VJM05BOW93eU13bXFtaXM1bDQKXdEnsYZDwAbskaPRPJrpYS4zn0eqgDBs
        YAOqYDfP9I1nfIBcVhdSKehlMWVgq+A7ir69JPxIHypqSkXEf4iOKA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6V2dzN2V2TkZPSkIyZ1F0
        NFg3QkdXb05NWmJ5RERKcWZLRWtGU1ZGL1FrCk5GZEhROFlaK3JBZm16VXNvajhh
        VXhtZHZzcE55SUk2Zkx5YWJaVC9ESUkKLS0tIFFJKzFjMTg0dmZYVVBOemNzclJL
        MnNxUVJmd3E2cHV3QkhBRXB2ZWh2N1EKBXR9CrcjQzDpsl/WruKbgmhDgTVvReRX
        l/l48/3hWNKvvEnUq6jQiKE+TDtgRqPFv/vuWpTw9K//BPJY1Lg+aw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLU3FSQ2xNQ0ZkOEdTSWUv
        blNXMHhzcXdNSU5rWE1nR3hINGRKMEh3U3c4CklKSTllekR1Z2pJbkE2S3RKK1E5
        QmFzZSs0UGgyV0ZIZ2ZLMG1RQkgzeTQKLS0tIEFpZVRUNm9YRkJUVEttTEh5NEgw
        WEdKaXNVMXdnNHVQVWdZRjlBTWlvMHMKtaLrEbCOOfOtwQGZv5pNenVvFb9IWdHR
        2kvXZ3l1uDUgnC2stGlJ6thE+qX7ai06zSyueyBO7uYle5uJhIvk6g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQXhDVXhXa0RPeTRwdjhK
        ajRZM2lMUkU4MGZibHV3NkUvaGo0MGJxRVY4CkxITEpTYnVFUjA1NWR1bS9rcGFy
        cGdDOWVWc2tpcE0wMC8zR2Z0aHM3cVUKLS0tIDdGLzNYNGhicGNCQXdMRmRHbU9I
        R1Z4bXNaNTlEc3cyaUIwWTFIbTd1clUKOb3NHDKfdTsyVIpWGIF/NndBqd0/ftj0
        /NwyPtjNs7eybkBkwG8FdDPUjXm548gELAjvyZpvy4vC99WtZoO8Hg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeUpEY1pkb3I3TUxuaHFE
        S3h2c1RGUjNXOVZ1ZkVHVHFQblNacSt2Q1RzCmhGR1FDQW5rR28vMmdEZjBtSkw5
        T05RSEUyTnNpZVJGSXE4dFhOOVRIU1kKLS0tIFBnNk1ycmxqYW1XUzY1U2pySldr
        VzB1SEdEMmdzZVFTSWlyMXJxUEJTRk0KcT2XBzf5nIcmQPr/Cx6IgRRrUkqVLgWb
        PMcWOhpVeZn9L4EBD4qQ66K3fkZK6aDo98Wv5dPNcTU/ggRrNGwvrw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1l5t62uzsj05pzftv9wg6s346csxyq202vxmmyyx8gwy8zu2nrfrs7v2a4z
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMWRxVWpmd2dUZGxYTm5S
        SStJM2dFaWE1N1J3dE5WcmdYQWxXUmQ4L1RFCitDellYTGl3dm15ZHJIbHpXQTZk
        MUlxRzIwRDNNWXZYRE5DM0FxbmJhOU0KLS0tIG5WZEZWcGRkckpKR1AwNU4zcGxo
        THp5L05kNDcrQjQ3TzlnSmVlM01QZGcKQ8ikf71zOArpH5q+srQRnZeFzy3YAqqW
        thAw4qMVdnIrUTuqDmX3ZdJ8nX7s+playpRW7J+nXSvkGkmGA778+g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T15:55:14Z"
  mac: ENC[AES256_GCM,data:1RAnTcy00GaCqNsYFkBBk3uOeTrY9KqCNbCYAUllV4Yuo8LRLeGKOH5qnv8PBOmuTdo9eykCKgK7wP2CPzG6Tq71XctDaAP8UX/tP8gvJja64GGx9r9yIdbgtgsK0XV4OSy7Yss7xUjTjD9iz2o+9kAbEqLj1AZao7yUZG6V9A0=,iv:roQ6fJmM98XZ099Shwei3PovUDN7lFvM40Ca7a4Y85w=,tag:WhDdEvm3YNcLxbUPgNG2rQ==,type:str]
  version: 3.13.3
