apiVersion: v1
kind: Secret
metadata:
  name: immich-monitor
  namespace: alloy-system
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:SdPFdtSK4Gox/QfK8ZkCNhfaqe4A28w2jN6uZ4PqCCyWwHWvANoNR+MrA+q5jxLM,iv:gkpdcYq3ygfUG3DjCgs9+mAAJYj5oo3X62bEL+wif9E=,tag:GrQPstdPVD3QlleVon/3pw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVVBmMGZpaXFVVmliMllm
        Z2NKNjQvK2ZFaXBCQzBjOVhGa2JZYzNyRHlrCldHNEVGSENGOUNVUFJHbUJhSE5V
        aGpaS09FNzVWMzZHM29rUW5QeWhwdncKLS0tIDRjeUpPQVRZbTh1Q3NMOVdqMHh2
        c3Vsa1VzRDk1bHBsOXpiRXA1V2N6VU0KltTXg6UQwj2kdYNuir59uDjndsHB2yWb
        j8qSJyEDdQPCO2nO6+VY8laimkAe+L8q6ybs2NvTQpKL4FVPJqTaIw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRnRISHcrdTh5dllVeFBW
        SjJIQ3VJbjEyRC9BWUlMdTVycHR0UmJScHdRCjRFd3dNb3dqMHBGL1pOOUtucHpr
        dXBCZEV1K0lCY3hTTVVUcUJ5NVJoUkkKLS0tIEduRG56K3poN21hb2s3T29zVm45
        V3JRdWtlMjlUbktlNVBvMzlYVHEzdlkKXTA+JkhlLFI9CA+Py1+BR+4F4XgeKHqr
        5c9yq5pOSrBJHPdQJg/DqZlzzzRwA7p4QPVgkSrzFoN4KKwqmrt+6g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVXgraGZFZlhkUXhlSG95
        L05vdk5kZ0RTSnBkRmc3RlIvWWdhMzNDOWpRCmNmZWFmUWVQanY5WnlRWW9FUFdQ
        UG5XeFJacTU2ZEdRRUt4Z1NaNDZXbWsKLS0tIEQ0SDA5eVI3SzVNazNwQngzNEs3
        UUc2R2RTNFVlVWc3MUlhbXJ1bmdxK1EKRnI4Cbgo/c7+4P8WzTyf3YdOU594S5ux
        yvIJZA3zbe8Hv0ei2I5aFhGyvFaGaZ3/iBFRy05NZ9oUjMQlaSgs1Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tdgfvwl4qdptyvgxju3rwz9uh45hz422txzcgsrwm4f4f96x558skzxklr
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbE9JYnZzM2NSWFo5ZTlX
        Q2hMOXNnY3k1ZG5OSFdzRWZUNkpXalJqQzFVClhiTllFWXRYWGxiSjZTaVZJUmxw
        dFh2SXFkdFBNY09vdUg3ck5oT0x3NjgKLS0tIHJnQmQ1T0pvZ1NLK0JibG0vcjVl
        TXRMQWtBMWFHN3ZWWHdEcE50L3FDNFkKfPkEDwTT7qHIaa6EkLFgCZsDyOFHzSeH
        y1Qm4WtxttxaONWT98YfTBTBwOvOwYc0a/c+IuUrRYTksKSZVztQZA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURTJqbW45S1h0cG9yd1dV
        WE50OC9CbU5WS0haREcrWi9zL0lmamRPWG1BCjIydWpHV1ZzaVdwSUxSSmNEN21r
        eVVYTHBiWkZpa05xZDY2Mkp5N0pmV00KLS0tIEc2UXMwSXZnczczZWtJanNhUHVU
        T2toTGp1TXlJYlYzODF3QlhPeUdZVTAKzsqt6v/gK/zEHzdiX+9B0Rcv53nF1Ong
        A+tOm4Ivgimabri9WO16rt+GIzapX4xOt6OCs8FvSqH8KXgrGa66yQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMHA5SXRIUkVrcjZVQ0lG
        T1RndGhWL21TZHEvTjlEOXZNVGRhazlhd1VjCldZRWFwK09oSnZoUFMrWmZaaHow
        QXVGSkhJNlFvVnJXOWJZaldkTWUrK2MKLS0tIGNmYUpiWVd4dG4xU1ExcWJBUy81
        RGZCZEVQM2NkeW1qRUdTeXg0Tnh6Z3MKWyvZV3PpQN0+4bsjRPTm+koD/YAMWFal
        wL+8FHNTbU3xV6NuvCsjz96hR5aZctP8PDis5YDbfViNep2M2UxwuQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bVkzQ1ZybER5WGl3aEJl
        dTcyLyt2NHVGS0dhcU12cUNWSlQzeXZMakVjCmhHdVU5dHM4b2MxTFJpOGtnMnlE
        VER3ZmFlNVFRV2dseG1pZCtkdm11NmsKLS0tICtxWUpQT1p6TGx2TlhsbTNJMVgw
        bHhCN285bldvNHlYb1QwcTFHZjIxdlEKhXuB2yqXu/7nHX0hYrrK//4117Ht6YP3
        /ed6D+YoPzcFkL5aN1E0g82HUuPTpGzFsewGEgyiBARWGdPU2PqdDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMDZKSlZqSERjS2JYQ3Zo
        NUJqTS9tWDdtNTBzTG83NHlITmZ1WHl4ekdRCmpldXgrUVlEQ0l4OGhNK2E3NFZp
        MkFUbzl0akpXTkZLcmFrSm9PVUk2MGcKLS0tIFd0dHRtbHFINTBXOVBCWlY3bXdB
        aFc0K3V6QzJPRSsrSEMwaTJaZThxZUEKAdhuf3zW+emSFuGP6BYzKRGQuVJ0EtNc
        unANeMUtz/pCZb/k3rJftHnpIf/i+cK1/Hk5esjXoZXhVnMufF7cjw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WFMwb3BOWDZhRlVDSUUx
        c2poSnd6MjFlVnI5VERwM2I4aENUd1hmb1VRCkxBQzU2TFg2WUEvWW5oVEtWek5P
        OWJMWGs4aVZlTHYxTmRCS2VSZkVRdTgKLS0tIEZ0M0s3ZVRJN3hXaWdpVlJCZE8x
        VWFSMlp6TCt2YUZicFBRaDI1N0JneW8KDo/Xw6u9ELGxfybJENgrNBWfw/Yx/1/W
        wig6eY23iQJlmO0MxNNZKykFrKhjP01Xg9SjIUh1phla9oTlztBSzA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMXhJZk5sSXJuUXZiZmda
        OHBrQ0w2SEZRRm9xYTF2SW5PRUNnTEZPU2hnCnFBQTZIL1lXdS96NElpYVdlSWdN
        TkNUdW9yWS80MitHUlVkV2h6bjNzMzgKLS0tIHQyTUcxU3diYTdTU0FVa0RDcDZ4
        R2VZMzlxY0hpbk14OXl5SUQ3MGZ1cjgKltnSl87NzDDF2X9y+sHPS6D46UV0qzFH
        2JWJNg1NwZezoxOrSFsnOkg4EmDtxBwDFRp1dAEiN1rRbqDOMbLs3A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1l5t62uzsj05pzftv9wg6s346csxyq202vxmmyyx8gwy8zu2nrfrs7v2a4z
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVmkwWG5OVXRSZE83cjhC
        QXJqYjFPMDhzT0k3MDQ5M2dmd3BCNFJrZ2dBCjJZOUNEMDR6MGcvMzUweU5lblpB
        ZWJYdENESU9tdzVCWW5YSllRSUxuTlkKLS0tIHprZDVFRUo4QVl5ZUZmekVIRDl0
        NjlGYTlTQlQ5T0JmVC9HaStjeUVGQlUKDstZChnHmFSOPuX78r0rt5z0MzsbvaT5
        Y7k/0echLtRsW/QznSIFHXPUeyEtRTLjf2/PWT1AJsWm+Bt2PMD1Qw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T15:55:14Z"
  mac: ENC[AES256_GCM,data:AkSG1/Ei6xZncet1VsL14jxZVmDLl0TM6E1p3v0LfZ1OwCuqBmLTMjvy/LmlmWqW3hLUDzd6RmjQX/0ZKwFAseMQk6Yo1INlVoxzeU78cBaI2IJ3XThWSIbpFk5G+CS7HPycE1AkscAGUESJOiJzpcoWDjUYmv/SkSDM8alxt9k=,iv:jLFMSjCW40VsJlZgSx7v8tt/eLvhJwoNFQHwaOLBUuE=,tag:KJLqAkMLmZ+o4yBLiBWc2g==,type:str]
  version: 3.13.3
