apiVersion: ENC[AES256_GCM,data:Haw=,iv:9NVblKBnXkWdEAgu6WFkVo+9v5ztBW63T5LddBF7HQI=,tag:q2puuxhqBwqhHYkxokQgWQ==,type:str]
kind: ENC[AES256_GCM,data:KOO1+W3G,iv:zt1lpjSx1jpFONveNvG/yu47/z/FxgvW4tgkFIsdPpw=,tag:/Ty+kj3RlBtDe2I8yMNgvA==,type:str]
metadata:
  name: ENC[AES256_GCM,data:d8e5iN5kr6JVPhxhpPavxvmG,iv:ZuR1Qi5ACSbbAPcJnP+8pVegtZJnB9bYj9M4HkaJWGs=,tag:LLG2NPgWfAGDnUF9nYHaZQ==,type:str]
  namespace: ENC[AES256_GCM,data:Hwzuf2zSdJ5NyA0=,iv:wj6YDZn/hxX43mw4mmafhRb3c6ZHaXWq6tzmSiO1Wgw=,tag:FPyeB/1IABxDrOc7fJVp/A==,type:str]
type: ENC[AES256_GCM,data:gIlu/9wHLT8FyzvV/EVQXacWuOvIziBK,iv:QlbjBBTK700FoU6GMNoNPs4zKmC1r0DaDpwartsA/Tc=,tag:5SnMjYjuTnqIrexjMQDg3A==,type:str]
stringData:
  username: ENC[AES256_GCM,data:/6jFl3ZWCONC,iv:8wEAUiijz3jftihkNxFunAfMT2sqLfw+LyPupp8JZyQ=,tag:waoRKLOJmN+IB3js+bkHDA==,type:str]
  password: ENC[AES256_GCM,data:8u89/WiblL6tiF3ckveiFiZ/P1Gz3TRHkMs2nUJ+ctaroqktY+D/EWnzUNsJpKHq2SAAxxlSs7MV47VWhlOklQ==,iv:vlaLQFJFl2gtD95elZ3oDZnwAY6yeFjAHO+KRZmdiU0=,tag:4LGjnqs5LZp25z2wojgF6A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZkJpblBCbGR4K3B1TWN1
        bnhUNHV6K1JSemUveDZQZFJyVUhYZUFzUVIwClEzMHhXYnJkMWZCMkdFYzB2cWJS
        a2dGY3FCSmJoYncxZVJUWnpsT0lrc0EKLS0tIHBId3A0V1NEalR6RGZndlp5ZFBx
        MnJZUTFDSzdITjNEVWpTb0lhckczZzAKmXcpuVxqruX5TN8uIanxUXyb3i9AMGft
        fwUPO1eXrgpvolbcSB/DwLcXVH5B0wn2/uhgRm+h6Thb3hhfBkmPaw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxN0J0Sy85TXFaNmRiWEVx
        dkhkRWNWL25nTnFKZmh6aXJNYjBKUk02R2g0Cnl1Uk9GY0pPMU1FeHh5UW8vN05p
        WDFJMjVqWUs1VTdDczFmdmJ1MlJwUjAKLS0tIE8yN0JMdEdCbW5SUWlIMDhmRVJi
        SVpEYVEwYXZpVUJaTkhXTTVZL2dRM1UKBLuhb1UGjlhtyX73cXuj4lkTNWSc+xKA
        Ytzc2jIlMRhz4yiVy+rjQzu6dsN+i96I15HNlURkZESe8lhW4it/Og==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNzJvSDdFd2dlNzhIQklE
        M2k0c3ZkYlNzS1VvWWJiL245cExLeEE1SFNRCkZXeUhsVzc4TnE5NnBFN2tPcGFm
        OVg3WkRucHNuK1dMSGRRTG9nUFBlNDQKLS0tIGJnb1BmL3diUk0rbklRYzdQaDVH
        OW9LLy84Mm5qbUhhVlZyc2o5SGxLRmsKTyS3o8VPiHgIQeUIE63W4tbNC1JTxaHu
        WbhKz+WuB07YnuxNehMSOPHdoWAdyQrKMxB8X322Yag2owikgy5dDw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tdgfvwl4qdptyvgxju3rwz9uh45hz422txzcgsrwm4f4f96x558skzxklr
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpanZ6TGZ2MENUZUxHRzhN
        T0dOUVdEUTVoa2NndmM5N2YzYytBYzBDcUFjClFiajNDMEkrZ3pvcTVIdXRRdmVW
        WEVWVlhISnBLS2Q4MFpZVTliVmxzOW8KLS0tIERpd3ZKQjc0dHZwa0hsT3hrTUhU
        WUpXYWNEU3duVkdhOUlVc3djVVV5Z1kKC4AlYlDhMjbJDyFSlP44st15aQxlURWo
        x/anTq31lLlu37zApD2YqGbUqwTN6cMXgL89bB3s3hV+Zx2Ppczo9A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQmxQMTFRTThLY1N1Vzl0
        Y0c5UmVFazg4WGdTaHZsRUtIc2I5aHgvUmp3CjhsOENTUHJ3d1F5U1IwbDFEMWY2
        VkgzS0FyNlBUTFFYY0hDblVSc1VtSWMKLS0tIEFYTVp5SGRBR0srY0JQRTZwckxp
        UWZwZ0hxWUkzK2JRQjVPeGo3alZVc00KN2j1/vnLyt9vzva1GXV+h4b5OVtvP/JQ
        l2eK4YtcpB+yJRtBrQxMPG1EN/91P+ZU5gBZ605SzSZgphumv9mbvQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWc2YxTG5GY2dYY3pjSTBH
        QUFGRFQ3VzVyRTQwU3FxWUFBUmpSd1VWRzNzCnBTUi9tZ21oeVVnR1UxTEtUVEtu
        V05XdVQ0SkhjbFdTTjRMMmZNTEJtUncKLS0tIEovWjM4VDRSRHlzdEtWdm5JWWZp
        cTh1cVY5dFBwSkRqWHQzS25vRlZ5V0UKtzYJMww/gy0AAJ4BNLb5B3obgpyjEWL7
        gkMVvXo3fr6o8DNHSliEMd4MuLHtq98EEwi3g1UJYS/ToLGayCz9eA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVGh1dmN2L0FiSWVHTEhL
        cGpBZW1YZEljczNOVXlvOFJQZXZKY3pjcjBRClRtWWdwOGtDQ0ZHT2Z5SEZxeG5C
        TElDR05SSjRnNUp2S1lndkFGQmFpM2sKLS0tIGtRNlVrRVNEVndBNlJ2YkhSQnMz
        eUhST2Y4V1JlbTBaTXdZUlBtQURlV3MK+l2R18+Nm89/rgZxE3hr9bbw3l5HT+9+
        vXHPNsCE/dDzG2dymx0R+N/S2lHNFFOl0XjIg4YveJ6weooRDKDkIQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRmJrb0hJSXpqSlRLUEtW
        aElzMTIrNVVrc3dPZnFzLzNBVGhJWGhhSEJBCkdXSk90Ti94SGRIUnpET0ZLd2gv
        TUIvdGJ3Mk9zbFIxcFE1SHg2SmM5WE0KLS0tIEdqWjNIOVFqRTZQbGd3RjJtUTN2
        UUk2VTA4Rm0yS3R4K2Z3NWpFaXdjTnMK6vMeCj1+SpHGSSSZ9tBLjrAPoChzSXB4
        gXfDz6pd+y7S2rUu33133O6o+LgWkw01hRzVtAAqSKksL1w7Q+xijw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRUZTVnMyUkFXdnZBaTFp
        STQ3dExTaEFjUnR0UXEyQlllWHRDK2VveVZ3Cmd6Y2g2YVRaeldnN0ppU080bEx0
        NzJHWFdVaVhOREVwQ0pHVVRmVlFDV2sKLS0tIHhxWEk2WGpHN29FbEwxVlgvaElC
        ak1UbVBNTG5GUVgzTUlIVzErWFdNZXMKbqnZOqxZRifz1v6fNyJJqJJWY6PXSXQ6
        Jb5f7VNDjKgN70TAiaEHA6iQJK7iOZggoVAOcn7U9VjLKfVxJ2upSw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrc1Y4OWRiQXBPMGdydkRH
        bUNsUGlpSFlxTEVjeXRkWDRheUhZQ0t2eURJCjNpeHdlUjEvTCtEajVhSzkybDlv
        UktPOC9hV3lZUngyRWRPSkI4U3hVMmcKLS0tIGdqeFdGbHVHdS9OSWg4SzJ0WE1Q
        K1lBYnJJWU5uVkZpVC9DVEVZa0F1S1EKfzXvhSGj1YvFoayLJDF8baxDlImNrcui
        kCIgZ35bQ4HgntYVuoZHbY7dtgAFuuJ185GRYeq4lYJ2IoWYFDSyWw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1l5t62uzsj05pzftv9wg6s346csxyq202vxmmyyx8gwy8zu2nrfrs7v2a4z
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaVlhcFVFTExRaUlRSGIz
        Vk0ycDBQOTlmc2J4VVg2QzJmcWlOMGpYeTBvCm9xVlNLazF2UktiVjdhWkhzZlAz
        Y1ZpUzNJaXBUUU5tdXhCOVVNMGN5bUUKLS0tIE9ZeG1nSDd2M2J1aHNEd0M1akRC
        ajNQcnJ1bUJvdnZpbEVnY1IvUGNvanMK8jxQWoKiYDYMzKKxHq0pQoF/k5xEIvHZ
        AjXvkcfeUi3iQN2urmjUtla61LoQscG85VvXPuiAtYZYYMsHhfk/2A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-18T20:55:11Z"
  mac: ENC[AES256_GCM,data:L6C/UilsRMUnpCPtwPEOSzEhtIvTaTSrdTXf8nt2Z5YQEkYXtS+Bsje1jqegNc0FsOZJGD8qu3hqKSKJS5yVBn8IgwHuQ8af2h4NLsng+XB1A0Zyre+nKQNxPaJtVUtSZkAakLWAE4k4OYXCmlxrPzanMLKfax5XTy6WS9J4K54=,iv:jLgFdUuH0vlI/FeDm95B4h/VMUGD36Btml4hw1/4Gqw=,tag:XJ919LxEYpq8aW1tzuqbwA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
