apiVersion: ENC[AES256_GCM,data:2aI=,iv:acyxJlxbXx/lX9aNJDI4oaPztQq6cZc014tbmJ8+lQ0=,tag:rGh+1WBTDZWbZnCWofn5nA==,type:str]
kind: ENC[AES256_GCM,data:y8rQbjK0,iv:739kHmQDYy5bhweMWA4tHM+XRfDsrL9KKVdkMvG6d5I=,tag:Q5ru0NbOLj8NPwWN9svxFw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:1VOmoN0n0dBmmaHL0g==,iv:WtPc+pOjZEo+jd3lzi9GJgE7c8n2fk1OGRIkUihhAl4=,tag:u9ERQXmVIbHJBU8KZSG+eA==,type:str]
  namespace: ENC[AES256_GCM,data:K3mZtfmKmv7D,iv:PBYCVOqK1SbDfoNqSV8+dI//RaoOHxdxK3fKOOuAzvo=,tag:h1//hsgvfy3pfn9n5rfqgg==,type:str]
type: ENC[AES256_GCM,data:/XcpJ+rD,iv:yc85Nu+Lcvfg5Ll2z2QA9nohTLcvki768xf/j27SjTs=,tag:t4R+wvhKHgtq4XZ6xsHWJA==,type:str]
stringData:
  NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:O9eZx71oQouN0pm3uNEYNX/mPgfn+DhXIbemp2gm/DH9PnZHcquHLoKJTQbMe8pa,iv:IQk31qlcKMYski9ySy/rg2nqkxC+GG9mi4Lbroo2hh0=,tag:/TufbM8fEgop/GZCSp0CUw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:EghI3RLMZOVFZPeVqesBUySKKaafaf/YTBdQH6M2j+iqsF6Bh+YEVi88pJhNbQEg9R2fXfzDxf1aRzg70ZVp6A==,iv:5pQ3YYEKwo8hc3wnqX4ffbTkOdC8l0Vr9AcsbtOyUz4=,tag:LRZi2UPZdZ85+B2CyS/vlg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:6YqTEZoRDIqHEzuFurKLrsuJvZDTX7qze35MzceKRJqoLJvy,iv:KLNriwHUEGZXr9p+KC5OYS5C2XpZ1NcYon2d7154y1o=,tag:vcHX5cyuyjSytwIrfuje+g==,type:str]
  OBJECTSTORE_S3_KEY: ENC[AES256_GCM,data:nDUR6txNtW5BmXkZbkiDJt0xJ7CYxoHPKK7ri8hEojRgxw==,iv:I1AIH9qh6L8thXdkdd4sl1NzwyJJvMqlVDbKBbUs9iQ=,tag:tLDfYf0xiqpRxTZvsuK+Gg==,type:str]
  OBJECTSTORE_S3_SECRET: ENC[AES256_GCM,data:0aBSEO6SPcYPoTaAR9NKv39HwLrcoXbsMfKFutyy/j0TlXDu0jEron/xyYMslqc4tEaf4X3y7nt/Bz8nY7qgyQ==,iv:I+vqKJP7Ka1MWS3eJTUdQ0vh6zae5BSS38RDzoEfmfY=,tag:VVo9H2pDBm346ybjD+EPDg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQjltb3AxNjR4VTd5Z2Zw
        NjQ4TVVRTkpwNm1KZWZSY0JzUC9hWTVtQ2swCnNOOUZrVXdydk1WcjFqTkoxMUx5
        bWwyRU8vdjV5bi8rSlNjNzdjR1hJZmMKLS0tIFFDR3dWY2RmNGRDN2dCVjNnamEy
        VmJ1Z1ZVYkhFblpIOFlnaXhaSXBjVXMKPlMULVCYSCOfeOWrmgKJm17eChjFvSrS
        zAe61hO1wORppiKTILN/waPOQjjOsWuFk1CedAMYglBenpH6QBrMRQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OXU4TDE5YVVEMFZJTHdE
        ZWVUZ3prbnlSV25tUnJTYnFJdERsUEhCR2d3ClEwZ29NOVhvaUV3VytSeCtKZHpY
        UTZKSEdoa2RuMXNIV0llUHBsZVhHeTAKLS0tICtZenZGVEJxeUl1QzM3cUVEaVBs
        UkZXUDdseTdqNzg5UEpLU3NZSzd3OWsKOK/VgXBjo4PJgcY7xmHaAGSyGAYccocd
        1FWYXWw+lmCWlq0IfEqdBr6MWK7UwKzNIlJ6gjP59fJ2nxOySmFlmw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlellSVk5KakcxeXJNalR1
        anhNLzlJbDlQc3NwK3Z0eW9FZDJTbnhsL1hvClIrdlpYTThLeHJlNzUxaFFJZE5P
        T0pWb2U3OHVISGxNTER6SDNGWGtrclkKLS0tIGxwNGFJclNFUEtBU0RJbUFNemsx
        ZmtxekxhbGM2TCswd3h0VHZRU3J3VzQKD+a6owGZ9qsZdICwGY9/2GWQIDoIBbs2
        9gU7fVojnxF9iy2PTxpSI5TAhz2Q8v+FnW/gFFLhvyW2WVFQYbq0uQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tdgfvwl4qdptyvgxju3rwz9uh45hz422txzcgsrwm4f4f96x558skzxklr
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcDZocVhFbHR6UldzbTZV
        UGRDUmMrZjBWcE5SS0ZjRVR5UHQwOElzU0cwCk9XdjNKZjZKM3BnN3RlcEtWWnN0
        QmVRMUJZK2NxSUpENWhuVFNRWnZBL28KLS0tIGplU0RuNnpDQ25WaENmSXZKQm9o
        dFlDUHZORXBIVTBUdGNqeUhtMS81M2MKbczf03pLXzWI/Mp144fN0kjKbDsEwK0p
        Txpm/ULdMMOj4bWf6NSdyxNaSTMC7su8vpu9m0wLXYGXXv2rqTlyEA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Rnd1dWNldXJaNEJNTlI0
        L3owY3kvQW92dGxGUnNPUExTTTk2WU9KbmdFCnVIdGtSVVBxTnk0eE9QZHYyUGQx
        WjFJdXFQVkxwWWhTRWgxYWNJYThKdnMKLS0tIFAzb2hsb2NrWGFlMFhkbElYNG9q
        S0hrZG51RDZWc3hnWmdGSDJEdHdTME0KSdQnTyivOos03MaX8fZFJu6EKSBoQA2H
        zxhsNx3bQJWrE2gAi3VEeViyJdoYdUvwUvdho8P4oNKZNfzo2JawAQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMkh2MHpUWitqUDBPd2hy
        bmgxaEdvZkI2ZWRmRHdYZElGVEk0dXBzUURVCjhlekdmci95TnVsanJSVzU2S0pD
        aVVKai8zWTYrT1NmL3ZnZ0NJVlhqTU0KLS0tIDAwZzZDbnZnNmVoMk9yd3dxVmhV
        SjhESWpZWGdLT3ZQZUpSc1FIQVJrVXMKE/8OBzxnEVXc1FULUtcD8FLrn6915s49
        R542zRxGYUqXTQwUrKWTX49at7SoJg/xmLmOLQRRHAS/at1Wo/C/sQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBREkyOEhpOVo5eUx6b2JD
        Yll0TUcza3dsOGpMR0hsM2o1RjgyemltR0hrCjErZi91b0pjVFdaUzNHNUplaXlW
        U3o1M3dlR0Fwdm5HK0tsMmp5c21KWWMKLS0tIGhuUnhrdVFJdjhkdXIyYTJQMzk0
        UEtMSTlnM283KzFlU1oyVjJCODk4ZjgKAByxxdA7ZKIg4sCtJCtdYTi0SJc75g7n
        U07iFdtdv8Wzcan/4nhBJuC+ldcQpoZhqO/TRDt39FUK+NeXHWORwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIclJoNGYvUDhVZUpPWTE5
        c2piT3JPcWNLZFRFVDc5QW85NHI2UzNnR0RJCmt6d29vcXNmaGxNR21Qc2REWTlt
        MDNrUTIyNWV1bitmMXcvNFh3R2Z5dzQKLS0tIDl5MTlxWHdsVHRZZUp4cUljMEh5
        LytsaUpMN3NCTXhja05DNmZVYmdlK0EK6whDHPi7AHAd3vNb4ESkMvL6q2dVm6zQ
        5FJBhnmPcL0LFuKpmw/1UPe8OxtqnL83ePLuSZYMEie1Xbg6thi1Bw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSjlvalZJUkZEY2wyUmZU
        clBZL25IMXIvQUc5dlA2cFJLL1JSVWtrRGlBCkQyTTR0NW5Cb0tWOFpOekxwNnN2
        RmJraVJhNURKVDgxRmszSXBWcTJpS0EKLS0tIHI0cHB4UVRXa1MrWDgvZ1p4cjJJ
        WEV6R1doWUJnRkVJTWpQVUUxRTVVdEUKdXZnJNW/bUqtraMgzgRJJMe8iGoZRthL
        VD9BqUonfTRMhrFeoR+UWXeBKRT1EPeEQDl+9k0XpeF89xNQ2ZcwLA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK1lsWE5QRnc4OVNGL1l5
        NGtMbjQ5SDVVcFZMR3lpRlBwa3hRNzBWQjNFCmRrRzcrZzJlejVOa3NpbkdlajN6
        THk2eC9mV1IxN25HWDVIb3FnSkY5d1kKLS0tIDVuMkhsWE9GQ0Y2UFpMNmJyUktJ
        SFdMZ0hnMmNFVXg4WEpsQjJ1MmsrVFkKhkHDQER+b/OP6h/9SEOhFG6poHHOm1m4
        I3+bWIc2Yzslz5RM8SP1H502H9/Axr3FtKE1AvwAiHhAwRbIsMiZsw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1l5t62uzsj05pzftv9wg6s346csxyq202vxmmyyx8gwy8zu2nrfrs7v2a4z
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bTZ3NGZ5eFA4OU9XNThm
        QXhHQUVkVXQxZTFyMHNpQ3hOT2QyNTBtVzNRCnY5aGY4MUtLTVdrRmg5YWozMkRV
        TmIrUmJYaUV4UHBvMmJTNWI0eGNCUGsKLS0tIGk2STBFMUhKSUYwR1owQUpMUG5H
        TVhaSWZvSnJ0VHNRQlRNYzVBVmZhdkEK+dzZFxTtegqOQLoMw2AD24sMVCqruP0m
        14t7IBq/SXz+4+utdJe0sk2wK9aJxSGs59oMk1Fm017xtSZTOTA53A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-18T20:54:56Z"
  mac: ENC[AES256_GCM,data:FX6HF1gbMkXvsB14mDYc1V2gWYG6RcxwYbKZKc+h8sjt5Nt+LktTAvLALip9PG5W75RNsz2MuyAzp8Xeh9vzm1XYYN03bDv3Chl8COHAxYsWNceXF8ZJwuOpSIQ4r4eraqpYS9rpnRlPWc3T1pGoqsCJu+tKB7AlZ1IY8K3wAJY=,iv:fcj97aJRjpZakLeg3yoqKUvMyKx7ktif2C5D3vEkO1A=,tag:/Z4a9xFpmt7QldrzVpmGog==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
