apiVersion: ENC[AES256_GCM,data:Haw=,iv:9NVblKBnXkWdEAgu6WFkVo+9v5ztBW63T5LddBF7HQI=,tag:q2puuxhqBwqhHYkxokQgWQ==,type:str]
kind: ENC[AES256_GCM,data:KOO1+W3G,iv:zt1lpjSx1jpFONveNvG/yu47/z/FxgvW4tgkFIsdPpw=,tag:/Ty+kj3RlBtDe2I8yMNgvA==,type:str]
metadata:
  name: ENC[AES256_GCM,data:d8e5iN5kr6JVPhxhpPavxvmG,iv:ZuR1Qi5ACSbbAPcJnP+8pVegtZJnB9bYj9M4HkaJWGs=,tag:LLG2NPgWfAGDnUF9nYHaZQ==,type:str]
  namespace: ENC[AES256_GCM,data:Hwzuf2zSdJ5NyA0=,iv:wj6YDZn/hxX43mw4mmafhRb3c6ZHaXWq6tzmSiO1Wgw=,tag:FPyeB/1IABxDrOc7fJVp/A==,type:str]
type: ENC[AES256_GCM,data:gIlu/9wHLT8FyzvV/EVQXacWuOvIziBK,iv:QlbjBBTK700FoU6GMNoNPs4zKmC1r0DaDpwartsA/Tc=,tag:5SnMjYjuTnqIrexjMQDg3A==,type:str]
stringData:
  username: ENC[AES256_GCM,data:/6jFl3ZWCONC,iv:8wEAUiijz3jftihkNxFunAfMT2sqLfw+LyPupp8JZyQ=,tag:waoRKLOJmN+IB3js+bkHDA==,type:str]
  password: ENC[AES256_GCM,data:8u89/WiblL6tiF3ckveiFiZ/P1Gz3TRHkMs2nUJ+ctaroqktY+D/EWnzUNsJpKHq2SAAxxlSs7MV47VWhlOklQ==,iv:vlaLQFJFl2gtD95elZ3oDZnwAY6yeFjAHO+KRZmdiU0=,tag:4LGjnqs5LZp25z2wojgF6A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZ1hPdlJiRXFTb3hZWGtJ
        ek5wN2R1RVRReVhYM2JLYmx5THJzaFM2Q20wCi9JbFJIUlc5RlZSNU5ZcHp6NGZq
        Y1J3Y0srd2JBNXFjdi80Y2xVTk1rclEKLS0tIEJac3lMcXdqREhKc0R1WmZOdi9p
        RWExQ05vWGFMbzZtQ2FQSVVHVW5SM0EK4viW3ofX2UWkkiU2lXerruQlEFOTpX8p
        tIF8wNSgRk0v6nuQ6upy9DXUNpdmy4tDd+8saytUE3Z0Xsu76BcfBg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybzZrT1FyNlRtNjJEdGRM
        Y2JDdUxKaExpR0NKS3NMb01zdWNZTFVaSURVCkJNYU9HY3dseXpQOGo2TkRtcUNO
        K1QxV0hmM3JDcERxbUVRcC84SEsydUkKLS0tIENJc0JvMWxra0hra2dMYWxPUitT
        OFVrYS9POFBtZkV5QmlSekVRaXQvalkK29Fs4oaXKy+idMXVypZnEemeXE7BsG3B
        wJyKYu2bIgURn+psx9yNptd6w82G2QrH7tgV1foUloNdR4lKAVvCYw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVXFSZUltVkEvUUNQbjFa
        ZCsrdUJhdlhkV0orY0tXaVdZalNkNmd0Z3lvClJWSnJQSDdFZ0pXZS9HWUJNQ3A1
        UlgrTVl2OHZPK1JBbnR2ejlNQkRWcG8KLS0tIFNxVUpBZTIvVGd2ZkZIVm5PNzVv
        T2UxbzI5U2xHOUU1STNHdmlQUkNyS1kKy4dz/ipN8hl2nbDfzzb9mDoCz0a81hMe
        irQCXhSCXITIB8BSBo5Pkiaczn/ncrZOPFX7vSTrUZf2ksZ/6JVQJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Q2p2VFVRU0lxblhQZXBV
        dXFEaUtPZ3VveDk3SDE1ZjVtZTdjZWovbDFZCnVIRjJIYldlRVRqdWxVQ1ZrV2FX
        azNqbnJSWWdOcFdjK3BtRGhYWkRtR1EKLS0tIElZYjFXT2VsOUJZRnNGcjJ2TEN2
        ZjZTVURIdEdvbVV5eFFqWXVMYXJBYTQKCOw+XiSRX9YI1jZ8BUZ8D5cKFXOQdOmx
        exeQppwVCX5g0n1lsuQ4WsFrgRxYX5ro6YBfS0SX9icDzmgvHxXskA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaUpwc0duaXlVMFNkSnhC
        UFFWR2VWUmVvZk9wUGR4TnBBandISytGanpVCnFESHVaR3hyd1puVUpHdW5TcFZU
        VjJqSElZMjdzbE9rc0ZjOGtxcDMwaDgKLS0tIExyU3NqMzh4dFo5Mkp1eDVGSmd6
        WE1Uc0QyNWxpZkhId2x5elIwQUxramsKA22mApeJv8Yv7r1MmwWQcTEe2XTji8SZ
        VHif7/iQ/Ja4jm3dfR/wwD86Kc0EdK5nUZ229gxcKGrZhw/TaW7ZRw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcUIrZHBFeEgzQWR0TFFT
        bnpXTkxFSVhqQlF4cXlNd09lcklrT3JucGxzCmhzcGNubE9YSEpTRldmM3ZOQktW
        Q2hBNExpUFpTNnpZa3owekdrNkFRcVkKLS0tIFBPTDc1d2hidkVsMkNhRGdmQ0Rt
        NHN0Nnd0WDRVNVFnVjRXSlFMRFdWU3cKXfKJG4ipIyn4H1Pf5J4ZqAvObIyYkm8b
        ZXu/KdVc8ME2lPUzndSruFaIo5YFRyyPK0V1aB5hsVtDkh4PMWQM4Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUTRaZzFHa3pNbXlzU0tG
        MlUvYmRRM3FBQnY5dDA3S0trK0c5UTE2dng4CmhJdHVjbUlVMWtZSndERGtBa0th
        bzA1K2pnT0tvZ0NhN1VReXlKdFloTjQKLS0tIDBMRlcvZWZmZ0hwbE5ndEh6TnNn
        bzJtU2wzYVVvUGdJMllGdVhodVZ3SGcKkSVZdNAcC2qKJWa3mI0dv7NpqhhvFXKc
        xulsUJcr/NLz1O31vYswBB0fnK1vF3w2T3YtSh33S1qZscaQy1/I4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLM0lMdnBzTHVMR1E2VWtY
        TGs3ZWV5YnVwYnc5UGtEeGxjVjBoOFc1d2lrClEwVzQwSGNmbThncnM0dEY0MFJa
        bm1aTjE1MU9ScVlQK2tQMDZ4aEgwUnMKLS0tIGJMVHV2SDMxM0doSzZEVWNUOFdR
        RUJHNzNvcGNZem8vNERzTFhaYlhRSUkK3R3/o63idAx0jPpTmJlUDdPzTQAYahvG
        gjg+gXW5k92YX3MCuO7+XXrUogE/86pABIMvSeYrjj+FTqI8wa05kA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-18T20:55:11Z"
  mac: ENC[AES256_GCM,data:L6C/UilsRMUnpCPtwPEOSzEhtIvTaTSrdTXf8nt2Z5YQEkYXtS+Bsje1jqegNc0FsOZJGD8qu3hqKSKJS5yVBn8IgwHuQ8af2h4NLsng+XB1A0Zyre+nKQNxPaJtVUtSZkAakLWAE4k4OYXCmlxrPzanMLKfax5XTy6WS9J4K54=,iv:jLgFdUuH0vlI/FeDm95B4h/VMUGD36Btml4hw1/4Gqw=,tag:XJ919LxEYpq8aW1tzuqbwA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
