apiVersion: ENC[AES256_GCM,data:2aI=,iv:acyxJlxbXx/lX9aNJDI4oaPztQq6cZc014tbmJ8+lQ0=,tag:rGh+1WBTDZWbZnCWofn5nA==,type:str]
kind: ENC[AES256_GCM,data:y8rQbjK0,iv:739kHmQDYy5bhweMWA4tHM+XRfDsrL9KKVdkMvG6d5I=,tag:Q5ru0NbOLj8NPwWN9svxFw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:1VOmoN0n0dBmmaHL0g==,iv:WtPc+pOjZEo+jd3lzi9GJgE7c8n2fk1OGRIkUihhAl4=,tag:u9ERQXmVIbHJBU8KZSG+eA==,type:str]
  namespace: ENC[AES256_GCM,data:K3mZtfmKmv7D,iv:PBYCVOqK1SbDfoNqSV8+dI//RaoOHxdxK3fKOOuAzvo=,tag:h1//hsgvfy3pfn9n5rfqgg==,type:str]
type: ENC[AES256_GCM,data:/XcpJ+rD,iv:yc85Nu+Lcvfg5Ll2z2QA9nohTLcvki768xf/j27SjTs=,tag:t4R+wvhKHgtq4XZ6xsHWJA==,type:str]
stringData:
  NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:O9eZx71oQouN0pm3uNEYNX/mPgfn+DhXIbemp2gm/DH9PnZHcquHLoKJTQbMe8pa,iv:IQk31qlcKMYski9ySy/rg2nqkxC+GG9mi4Lbroo2hh0=,tag:/TufbM8fEgop/GZCSp0CUw==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:EghI3RLMZOVFZPeVqesBUySKKaafaf/YTBdQH6M2j+iqsF6Bh+YEVi88pJhNbQEg9R2fXfzDxf1aRzg70ZVp6A==,iv:5pQ3YYEKwo8hc3wnqX4ffbTkOdC8l0Vr9AcsbtOyUz4=,tag:LRZi2UPZdZ85+B2CyS/vlg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:6YqTEZoRDIqHEzuFurKLrsuJvZDTX7qze35MzceKRJqoLJvy,iv:KLNriwHUEGZXr9p+KC5OYS5C2XpZ1NcYon2d7154y1o=,tag:vcHX5cyuyjSytwIrfuje+g==,type:str]
  OBJECTSTORE_S3_KEY: ENC[AES256_GCM,data:nDUR6txNtW5BmXkZbkiDJt0xJ7CYxoHPKK7ri8hEojRgxw==,iv:I1AIH9qh6L8thXdkdd4sl1NzwyJJvMqlVDbKBbUs9iQ=,tag:tLDfYf0xiqpRxTZvsuK+Gg==,type:str]
  OBJECTSTORE_S3_SECRET: ENC[AES256_GCM,data:0aBSEO6SPcYPoTaAR9NKv39HwLrcoXbsMfKFutyy/j0TlXDu0jEron/xyYMslqc4tEaf4X3y7nt/Bz8nY7qgyQ==,iv:I+vqKJP7Ka1MWS3eJTUdQ0vh6zae5BSS38RDzoEfmfY=,tag:VVo9H2pDBm346ybjD+EPDg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUTRZcFZ3QlJFQzJsZXEx
        SXdjL1JQTUZkS2JQUC9vYTNqVW5jbXRVZWswCmdiMGJNOVRvUmpJeDF4RkZMUTdP
        a1hMUEtXL2Vkczh1ZGk2YVJYUm9zM1kKLS0tIG9EdU15K0VvanJ0ZkVBMHEwTkpl
        TjdKZG5TdG4xL0pMRlFMYmZjSlh0VDAK8/C35kDTkz3OVUA8y7XFlUUPqNq9BLLk
        TO5sra5tR5hyiNeY6pTswWrRcbkrUF8ZmQhHg7aUuNWeXwaKOA4I+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaUZ1ZnJiT2N6akJXVlZP
        ZDlQMUpXZVpKcWoxUGZKaHZ2VzdTUjQzMkNrCmx0bW5nM1IxNlJXWmJCaFFwbHRI
        MDYzcitnWHNsQkw2Q1RMRHNSZzZNNncKLS0tIC9Ta0t1NTloY3dRbFZrMnFuZUZx
        SmZCeFIxcU5ZandrbWdVeFdobXUzVkkKhYELTbq3ciBnhSBTPvrTVnfa5nqmboDW
        YQ7op5ZFRtCXA3UW7CqKFOTBqK6dw26bVZEjTfq3axhUWsoR8Aocvg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdk96VkczUUttMWFKTlp3
        dmpqcG9BUlMxR3FGSjRmVUYrMUtYRy9ZS0ZnCk1sSWtoUHJrUGlWUXc4aGJ1R25o
        VjZLQUpwZXRLTWJicitPM2poTjRkNjQKLS0tIDlwTkhzQW9pODVIYWdBUGZoNHZN
        dWxoaERnUUgremo0VmRlbWxLVGtTeHcKnLPKtHoVSxBT5AuYfjXF374s3CPDrvtD
        ABGU8k4tx3pt9W9MMQrYR6IJjRDSJgcktaWjs0lHafFb+Q/W/ME9uA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cnFVUmwralJLY1VUUDV4
        Q1NBbkt3RTMwODhVeEVjNTNzaXNJdDFzR0R3CkNyMWhQcGg2cW4wemwvMVQ4TlBn
        UWlXTm5OUkljVWtsaU5YVTNvdnBUMFUKLS0tIFd5Q2R2a2wrN1djSTFzRHpIZEVn
        bnJvcG5mb2V3M3VEWitIRmpwc0toUVEKx72HEMSgQMpmNCYiap+8e5xe2M9dL1Dp
        emYSiLQ3LwhfW2j2lx+taKhM4BStMQtXMjwAuFS9KUqBXlgMBQmUbw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzYUZydGlxdUozK3pEYllW
        aXVQSlVHSUo1V2puNEJ0V096OGNtb21Ua0hjCnBSZHdhZmdaT09GbExiSUJMWGlN
        UzhpQjR5aDFnSTIzT2VydWlnTFlYSDgKLS0tIEV5VnpPYkJPWmpoS3l5T2xiUFk0
        SmhFOUZEQWw1WEIzM2MyWHp6MHpXYncKuA+2kewAncHFAHMTG1NtcmKIMNiO/YS0
        vsomCvR+IPBh8S6YOQkCMWOMoUZP3UhoIjq8OYGAKyKmxXZgsVAuQQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdEI3RWZLV1E3a2hqTjBZ
        aW44U0o4Z2g4amU2VnFabHNZQWFzVWVWQVZrCkR1VkEyd3VteklJR0NHTlFFS1Nq
        MnFTUkVNSkVGS3lJUHZJNkE0YSthNkEKLS0tIDRwUEc2RUhwY2VLUzl4dVFPazM1
        OS9nbEJpN0xmbXNUWHVadWdMRjNWNlUK2lM9q8/N0JsQo/wNvy9fszximCz08Ix4
        B1KkwnNlOcABHCsL33z9ThMBg8D9qsArCvye+DDcvpShLNEBhT46Mg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtT09XbjN1UThZRHBKNllK
        aFNFalZNdFgyMUJxc0FxSjZKTmRNWGNvQVJJCk1GUHlVcXVYTmlDV2lOWlo0N0FL
        cGpqVDV6azBlVzFZclFNelBJTzY2eHMKLS0tIEMrcWQrMEIxRTJLTGVOTFFLSXpy
        MHRLam94NkVZaUZwZGp0OUxaTDFjYWMK26HrVypJh2zyS5K0oCnWiElaTKrG+GRR
        uFuMzGV1S9lWkRPB1mL4+j5UMpeNA7xF06hzahzi5TohdMSOG+NqEQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcEZXcWdUbml4SlFhamRL
        OGdqQ1c3enVwS2IwdjBIYVk3V1MrcHVEZTJNCnN1MzNLdVZ4SWQwRllZVVhYaWls
        bUx4ekxEWFZMZWdvWGxYYWpBSWN3VXMKLS0tIE5iRk1teUY5V0ZQdFdYMVdIcmRk
        ZjBwK1I1M3hJQXRzTTcxakR0akJEYmsKTwy47qTzejAzhUBspAGxp3cJQx9AHssh
        o9cgzktumZQn6z6LOHk8UtVq4VdW7S0IHlPWKyDxYdZMyvGnWiA4VA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-18T20:54:56Z"
  mac: ENC[AES256_GCM,data:FX6HF1gbMkXvsB14mDYc1V2gWYG6RcxwYbKZKc+h8sjt5Nt+LktTAvLALip9PG5W75RNsz2MuyAzp8Xeh9vzm1XYYN03bDv3Chl8COHAxYsWNceXF8ZJwuOpSIQ4r4eraqpYS9rpnRlPWc3T1pGoqsCJu+tKB7AlZ1IY8K3wAJY=,iv:fcj97aJRjpZakLeg3yoqKUvMyKx7ktif2C5D3vEkO1A=,tag:/Z4a9xFpmt7QldrzVpmGog==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
