apiVersion: ENC[AES256_GCM,data:Fug=,iv:DGlBdCFb0oNdD5gOeY/2ysxoGUEWAfvWDW74rwK4pFY=,tag:nC8fT8Rn0l9mPkKgJxRPuw==,type:str]
kind: ENC[AES256_GCM,data:RxVqs2QV,iv:njgwtgwMtTvUt19TQ2vk0CyNX3aH13IzMm4PRJ8AELk=,tag:NZyOcrqFNLo3c1UAM/XuVg==,type:str]
metadata:
  name: ENC[AES256_GCM,data:iuIDQmoUMvo3yTuCjoVEXDRD7dq25LjGTiT6,iv:kxazCfjpAnf444I3FH3xPyC7yTcinDpXMjqjOz5c0T8=,tag:O8hfL3jCYJ7xX5bgF91wsw==,type:str]
  namespace: ENC[AES256_GCM,data:YvD8Jg==,iv:GcTFfOtoXaMJln2IxdeBMk5uUQOBF/eOPqJDD1LlQKY=,tag:fhu1xHU8T+ZolWHRlQuzBw==,type:str]
type: ENC[AES256_GCM,data:SZCHSJvl,iv:Zj2ddbVmY9BdE1P3VdFrbVHVeFO4nuVTtS5swl7AuQ8=,tag:bMbbjF/q23cKCJvxj3YMCw==,type:str]
stringData:
  database.json: ENC[AES256_GCM,data:ZMdmRzf3YC6xG/mJcPRgOcY3AHvvYiuYGJQmqDTFKTJsHInB1rMprxc9vxE9dLzaiXkzSFo4vRaYRkzeC8MsEYLxAilQpnDZpsQ9gD9TsasrUu7GNGijoFFkRqLBfszfyNpVWznrrpZEC8p+8ui6s1xaaNPJyeWOXX99VEG1nkAuHIO2m/vKoCzcDrd5MVEei/Xmv85FrOJjtjaEFANYbl+4OiZfLMvKUvVvDYQjFsTTC2FuwQ9dCx3fwpe0X7CdBAT7URtU6x6m+/OSiIEzFDN827L9FjL0b+cHshk1xw7ChOFKbb/7IdOGOlBCex1PNa6pdEiVxvyectQDI403GMNWmxjpVZSByDJiAvntIHDNSteSZoUbYQxKyQb4UVaQm0AxdCiDKl+B8EDbPsBXtvQiDV207RScPdJx3+3pI9yQ5Mzs59f59bId0txPvOzfpfcbX4Gav2+x2F1VXpQStCG/k2a9cgHhK7NWXDLPqfkn+rfcISNrExHVUFM8Q4lPRA5HqViqPQc9XalDdH281BzW4QkoMoaf+4ZLdfogZqpY8CtjYRk6qkKOdwRwRwwejypaeP2ejjaRm+/lGyer7F69VfFaws1lULKXpAxowKnULcuJARUGJyWewxv7mhVtcN7OJFOXotHgEBWFvEq6CiXu0dLN1Vn5MJ7CzgaVSrmakm7CaxigrgkZL2gv87tC6J7EsQbQ3U9s0/Yn7MeyF83s8KHQjeP5n0q/gszJ7JEdWP2K/8qVwxjA08h9HrMynB+efpPnxjKF2NS1p9dFso6JAaOmQ8tfEozfk8v7QI3vZvJIhGLIqnrVvDvOoun6IFDUtAvH/8+Chnp8DvZtk+ieWVI=,iv:kMa9Ahrsg1+cEzo0qZZDX2Pjz4BTTwdxZ6P7JozqlY0=,tag:fA96T123ANRUV3rsS4eGBQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eVZGaVFBZWd1NWZ0bG1M
        QmMzRm1uRFhWYWJGcUpXMU9CWWhxQk5aVTAwCldKanZ4WjZyQ0xpUWlYSU5lZUpB
        UHRMd0prM3V3OUltMWpmbzgrZkdkS1EKLS0tIG5vNXJCbzhuM0N6MnFKZU80emw0
        QkxsY0dBNE03MUFwMTlSbS8yLzVQQXcKF8/yFsiTC10YlW1HRUCFiGo2BUi7Esgc
        dv7IHZpCQpWPGoxBJtqtpwan0/c3HXusFEU7NXDDyzYIbGuZNL6KZg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNnc1anRZMEFaVFh2ajhj
        NFVBMkpqZWJwTXJXL08yODB5ZFFJL0pqZ204CjhHSk1oeE9CeFExS1JiOFp4RFRQ
        dEF4SGtIcE1jdkpvV0xvdHdrVmhiRVEKLS0tIEFMOE9LNkVRZWc5bHF0ZHUxWkc3
        YThuK1Z4VksvRFNhN1NmbXJkdHRJemcKkBTusK5wZydvQmbpesWXmTXN2LlF3kxR
        sviY7ZZlD5aaCPaMH//iRlZ65NrLCl/RbwY8ddoi7ii9mLfVb0Pt6A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUjBtMlE1TDNGZ0lmYTho
        WndGczVoL3AxZU5kVDIyNTUyRmxFMzRGV1VvCitRWlhiaVdWV2FFdlFPMjlMYmxo
        OWlKaDFmZGwxVDloZkp3OUd5d01lVXMKLS0tIEIrMTFEZmlxYXJFWkQyNWpRVGw1
        V2RDcXgxWVkrWks2NHZ4S0lnaTJvSFEKH9hFN+fHu1rkn1vCr0KWs76+Num3VlcO
        5rkRAnhZw/HzQ9rcSKIbwR2Qg30PG4tckEfxrXx6z3Bbriw/7j8LNQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tdgfvwl4qdptyvgxju3rwz9uh45hz422txzcgsrwm4f4f96x558skzxklr
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWHRMUTVGME1HWFlQSnNE
        WWljbTdLY3pLYlF3VWN1eEp4clozWVhQcEhVCkllYm1LekY3NVo3K3JQRUxUclVU
        UzU4QnlkOFZieG9jWmU0bnVZUmVGVEUKLS0tIFNkd3liRFBJSHVYWVQ5bHU2ZVQx
        YjR2SktkR2hxeXBSL0pQYys3RUxqNTgKY856uha288XqY3ASOpXKbwlDvqi26d0G
        JSeZSxVjI8aC3Kqkl7qeV04StvPvK9VY/Z8pMLLb2alf/NYptOADRg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkb0tFYmxGTXlndTdBd3Jz
        dExqYUpsSDZSYlRWaGtJb2F6Y1UwcHljVnc0CnBZNGRnbGN4QUdyNmI3dWorNUlK
        RVQ2UkpLNklDNlN3bzBRbVFXd3RMbXcKLS0tIFJCTVdsZmdkUzR1RmtPMzh5bCt6
        M0dwaFRsbkxJRDFham5sYXlpbGY0aEkKIFgEH590xUC57LsJFyZGfRafnj2Z9UUH
        74vfFSuTChruBMY8GpK//jF1Ux3g7KztzC1IOeD8lxXB0c5FfJsBxw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdUM2MFFTYmVydC9vUkZL
        aElJajdDRlpqZTg2NjRRVU5NSlFDYU8zNFZFCkcraDFidDdaaGJqaUFJYVd2R25M
        ZVhlVlE3cUZEeVJpODB5SEFiZ0tBaGsKLS0tIFhENlkvdWMyZmdLSHVPdU41eGN2
        c2srTWlxa0lEdTNzYkUydWdXTjlqMTQKxJPVdv1DeJX408lR2/JUTRuaG27qpxN5
        65AS1gD7m6ZJqXcY0WrPD9L3VV7otMhdgM8CAw4u2w1H80kRoWBTZw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0K016dW8yZ3k2c3BFZzgx
        TlA5alJMS04rcjlmanFMU3g2UXdIYmNWSkRJCnpMOEhwVnJGS1NPVm1BaUhGZ2Jz
        ZUd6OHNsOW5EeUwwQnM4Um9LMHZoR1UKLS0tIDJVSWhaTzNxTzNOTW05cmpLU2gv
        YzlNeG04ckM1VVQvZ29maUJDM3d0bzQKFsaZLdV/B0vl+6LMahG7M7OfQEEwCWmq
        UC/fgxy+uNUykryLyjSn+1mHMrHy//vZuFAClgfrYhbjaTUHVXTqyw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYVAyQzBZa0NCZ0tYOURz
        ZGF4dkFFZHVkelp6Q0lHZHQvK3JHSFFNQ0hrClhwaTRKTlhVVUFrdlpCZ1JnV0Vy
        SmVDRFZyWXNmSXdRdWgwQ1JNWDRKQTgKLS0tIGNaMjIrQmJQMktqMXBBK2ZtVFoz
        cThPbkVPeXpEeS9CVk5lWmhEdTVpVTgKvRHOznoLK80TkOCgvgwk9/Gq5qBaULfJ
        1uFAp/zQ8cs4M+khQ8raNY3UD57oLivach2L7h/1FyurnYjNzxPbvA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VjZGRlJsclltWlhZaHdu
        cC96aUVwWUZzYkEyWjhTRk5zeWF0bDJQVWd3CkxadWlBWGY1Nkc5b1RiekJWemI1
        R2lmdU40cVFIbGs4UVpSdlR4bnJpc1UKLS0tIGp4ZVhpNzJncmF5TExRNjVtQThO
        M2VTOHNYU3hRbWtPYTRIbnY1ZmxySDgKp12atF+NBbULhc24wphLNtDzl5w2+Yvi
        IDPsep08ghh5JhoedLxNldBpLnaM0NF7bHISXwV9BrK/sa5td1pS5w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cnFoY0JNeG9xR1lHYjE1
        MUQ0NWhCNlNQSHpCczhva2tYaUk5MVM1L3pVCkxobFRQaUdaZmIzM2tLSVRaSzJW
        dUd0MkQ5d0pVQ2lWY1pYS2pnL0ZZVVkKLS0tIEE3L1FQZUs3b0daZmVnR2J0QVBj
        U2l0MWp2TlM0MldEQzhWTFZidW0yNUEKzEhyNoDCO2L3asg3Ra6Cef6mMM60QhT6
        9UhU2L1QnFpqDP4sb5Y/CKvmf/DmSb/LQbcDK3ZQkbCC8lYyDoCzbA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1l5t62uzsj05pzftv9wg6s346csxyq202vxmmyyx8gwy8zu2nrfrs7v2a4z
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGc05PS0xUZjVJUjJ1amxR
        MmNiWHpldDg2OXliMFNtNlFRTDZ6WFIvQVhjCjArK0lxeW0vekxmT3ZYaTVXUkVv
        eUcxRWtOS3hSamdUMS8wckhrTVRRZmcKLS0tIFkyclNuL2RBM2l3amtXT1I1amJ5
        cVNKQk9jdmRCQmZ2TW5mdW1oajlEQm8KLQpHXmHZacr2ETbc0tJ0pdTFlDydqezh
        PrXzvn5/10SqGLlEKO9dhdEGnrdxhg6gUtpiiAL+B3mdshp3VBnWIA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-18T10:38:28Z"
  mac: ENC[AES256_GCM,data:NxwEihmh/oF3NQ4469LGmjcEjKwlmMb07DQyY8NTGJ5pRdGXo3irZ6gVTZp1Iwvw6Ja+f5G0SkE/qtVybBJaTbCEkpXcg2MroouRwt2t+f0FtlH6ON8fVvcEfhj9fLl32dFAnc1LJfYv+gzVxrwZ4E4sY4SJSOMI6d4cBc4ItgY=,iv:EiyqFmLctw35XlTSRbJNQA+E4x50zjs+jweBiveSsfc=,tag:sN9NJJEzsxRcdbK63naCzA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
