apiVersion: ENC[AES256_GCM,data:ljA=,iv:OsQhNYLjkiIzzk50E1qngiZqoKDtYzKGNWg65EICyow=,tag:ds5LsecaYExx9YULluzk9w==,type:str]
kind: ENC[AES256_GCM,data:lFuSjhb7,iv:1rpJCb0ZtSX7r11Cf5EkNMgLJbud2p5gGvL/f4jvJPA=,tag:2TFfB3gEPAp4XmGmgU8BOQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:HmdzqySSWu00Z+9K3Q==,iv:42LAVN205Y38ioltD8mqhKWapa+FlUvXdBNuBXzAWpQ=,tag:otTW267Q1PR/wY/joz04OQ==,type:str]
  namespace: ENC[AES256_GCM,data:47YR6Gc8ju2+,iv:aEkBhNKmMahYWbVSGwxSPwa0jAW54Smgzuep9RkgtYo=,tag:bCA70AeNQCtD+sPY5n1Rrg==,type:str]
type: ENC[AES256_GCM,data:IaBNUnxx,iv:ynVIWgAeh3Wchbp3PX8GMtocUHpFlqAR0+i7kbH/Bnw=,tag:7g9zyx50trLreNfPwsfHtw==,type:str]
stringData:
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:khUDdCsRpA3rddbYYIJlJaBOqgZeEidnxhGVgg4clb3aGBiGUFfnvPXfHp0=,iv:Cz6AyQvrLpFItDn8Ej2xX1OKwkoF6wFVNe5QnqhWuRI=,tag:q9/G7woxVCZ4cGA72u2Vig==,type:str]
  PAPERLESS_DBPASS: ENC[AES256_GCM,data:lbZ/iSrlxkW6HzossiIblwhmgDDsL+Syxq/ordcVX7G/5q+BR7BUw9tZSX3LzWeblR8llqXnBjNQjz0tDJQkjduPIlEwohKFcJWtYaS49Efj6jaE0cGQKQ==,iv:Oqj4svtXjqgXOudvDOfYKkYosuE6hfezbg3+5xzxu0g=,tag:zMfhlZr8LLHbz3AP7ryjIQ==,type:str]
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:cAfqzv314qosXdbt1G3X8qjBguobdbOAWfqq05oYRwAD/m++9ngQgq4n5GNxcJvzjV8Zfn6SKKC1yFfflc4kpFsFJd3nJtzuj+75Y2mUG659bFyGDvW4xQ==,iv:4fGQAAFPb7uBK8cpnwLB8JWnqRk4Ctgw4p3PN0uHajs=,tag:9WySOEcoKz1/hMMZfHWpMw==,type:str]
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:igsYjvPZGkN4gD/kiNFYUj4oQ4NItpfU2ueAAyq+bZ7BsEuuNVtEQSu+1icjawW5N9q4eim1e66BPg/a/qPaa8L7RylCQ5KKnNiY0jgI3qUISO5msnV8To3bLwhM0cwI8TSsHkB2nLzmLknxMdmR0gomRM4f9NexZvgyQ5P/yzs7hTQCJVMhc75j1KxwhAU1kMPcbXDBa9ZqTHPKdUIoiZ//x/HDg5sVFoYAAYNArwhd7Q08w9DuAe3zDSMcgxfGuwoNaKoLcrfDLM4J6gknAbgi+U7wdg2JNgMkaSok06W0xMN82RlavhY+7ZhkcRCIfQYvBBboAtyIfjPfzEVFLlwySEfVPJRIcOxmA2i0XHDHU9/PtXou7hSD2BaIXXY0PNPcmGg=,iv:kQzLVVabVLwAq7nlrS6rTC9pNg9cqg0sJ7kY/ce9JyE=,tag:AxZFd2dvPJ+CCeO+fGW6Rg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScnFoRXVUcUo4TjB3eDVN
        YlFCMjRucXAzMm1MNE9tOHJicUdBRUxSblR3CkVpdlFUaG5ZZ2lQZEVua2FxVFd4
        RENsT0Y3RG9XSHNjTk5rK2t2bTJSZWMKLS0tIFNqS1llek9SNjg1UjFCR29HWDAv
        K3kwenFpaWYvV2NNLy9ZV1hqamNCaHcKeNmUH8JcAg1yWDsap90TnewYqSCUuRo/
        D8qleJQf3iWxqhUGgm+ymz2JQz/B5xAvsrIAgr+9sgmaXSq2I61e4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYndsZjNMVGhYc3lnQS8r
        M1BpZk42MURoUW5nNnpUVFRjT2FsTmdldlEwCm9YaEVNcHlLTXhqaC9qd0s1MHpS
        OXFVV3N3MTd1MHVOZXB5NVlIanZrU2sKLS0tIEY0QnBPN3BVeEdvWHVaK2JRTE9o
        enpvbkdyNFhyL28ycVdGcU1HbytKancKBnZBCXaEgV7L4tLsu4OkCfBMzuQuKshQ
        oe/H4MgzvRC0tfL6QVslL7s0n3ADbNjj0vFWUx1azx99ZIfAsNK54A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZUhkKzRHOE5hWlZwTDhV
        SUFuNTdBNGE5cGtCWit6WWFzTlBadEJuQVhjCnFkQlF5d2lGVHl6Zis5dEREenE3
        NER4SitTajg4dVVUcVdMMTIrM1YzaTgKLS0tIE1YMTg0Q0JoRU80ZTY2SEhKNVZB
        YTFRV3pUSElZTEJySHZWS2owVWdFS1kKaftX9ZFXlONJ5n1dFW5XsiyFSPr7ifNf
        e4LxQPsijMPtJdgXwElfoPO75dqjBgviUqoMJeT9PJAQk1Ec50B59g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tdgfvwl4qdptyvgxju3rwz9uh45hz422txzcgsrwm4f4f96x558skzxklr
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RmRZdkhZVkNhZ3dXYUJM
        VHJiaGlKUS9KdTBYYXNCSUlHRVVoUSs2MUNBCnc4WmRoeGpKOFptRW5mdDlQRkhu
        aUtzQ0F3S1lWSEtuU21vZjdKK3M5dkkKLS0tIGNsSDQzcTFNVFVPaU91UDM1V3Fu
        YVFyZGRER2xCKzBZTG1tVTZiQzhPS1kKA/zzzJkttujP97YqHvJ7R61j0yobnoV/
        O0ttMmjW5lKz6yNjxmCzxi0gDMKiLJSbziIbPwln/A65MI26q2tVJw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZnRINEhUVUh0OWxFL0VH
        WnBJQnpSV3VueHMrRVg4Z2l4QnErVGMvdHo0CnM2MGVwRVJrQ0RRcDRiZzdiTTFw
        cFM4aTJEYWZQLzFIQ0hGZEh3T1lRM2sKLS0tIFFkb2JSVHI4TmtYdHpWSkQ4a3pN
        Q1hpaVVzelI5RC9QK1Y2VmZrcGJJNncKkmfpWQCZvyknwDDc9FlcXYuoMH8VaQZA
        1Fk7k3s3gQOuZN3TOHGfE7MuGHcpFZXMBrcTDJ1MNUcL7qtmfyBdlA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TkUyb1RpNXZldFpEQ3g4
        Q3IyclVybWh3MjNpR1VuSFJxSEtTZmtFaEM0CnJOU040OG1vQUtwZEZSS3dYYWJr
        SzQvOWs0cDFuOVVoYldmb2g0UTNyN3cKLS0tIGlUZW1qNTlvcmFaVjl2VGtVL0V0
        d3lKSXArUjJkMjRETXQyeDBtR0ZYVXMKd871KoBtB1I62+kQgAjIvUI0CpY2Uzz6
        if4EsqhFEN4qJ5nLz1zktyNz6fr9dbeJN65vGGFDuYJX240yymdBWQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cG44WGVVcnJYSUU5K05N
        dDlFb2VpS1IyaEFrTzA1cm03aVc1YXd1dUJJClhKb25TclBNK3BkV2JYN3Q3OUQ4
        T2ZGL3A4dUVUMmxzOTVWMVNESUVwaUkKLS0tIGR6RGpYaUNYL2xuTDRqWjk5WnY5
        b3Zka2dzRzR5NDdWbEhleGEwaVJTam8KeSala27bqRcomEQEJO68ieSjKyjKCfsg
        E7y10WCbuzyFY2JqGI6Yd9y2uHKbbBVqugPDqBBSKUp5nid7BcPL+A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNGZQcHRzeEM5bjNRdHJQ
        L3dUNDRpVUlWNklaVXlrTHgwZ2p3SW51OHdnClZna1lBOUk3ZnJPYnJCYWhKZDRz
        dGZ0aC9reVhOTkRxU0t5cDRieUx1MFUKLS0tIC8zcThkQ0hMQ0RrRDdtbFlzTlZr
        TDZnYWNXaytTMmNlNnlMWVZQWE5lZkkKTmfthWNZ3tWRAa5TBXJGFoNdxDRxc4cF
        CBtaYLX/9I6W4jn4YPsUQ3EECpoAmtpu3m+mFM6ubX22zehXl5atJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaHI0TkxDRWxSUUk5Wnpo
        ZDlwRWsrRElxcWcxT2RVbExpNGdFNzl1cG1NCjlXTEs3OHF2NVRxOG9PN1JqdkNM
        eGVUbEE5ODFFOExiS2V6dWQ4R2d2WW8KLS0tIEVYUnZtOFc4VFNGK2VEVEhJRzhZ
        TWxJZUJ1NmZlUWxkTERvdnMvVENPUjAKrTQgtliGcYv4CNrCP0fWC5zh84UbJcCY
        uJ9QBQUJGSUxuC8F/+nNdBlG8Kj+SFIJqmI7DCzdIsG57IsS+Ny0mA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMjgvcW9Od0JIRnNZZ1dy
        bWo1R0pSVGpkZjV0ZzFtTFYxRVZQMzZ3ZFdBCldNUjFSc2lLWUpBQ3ZvMG1ycnkr
        OFoxMGoveURHOVV6Kyt6Yk8wL0plbWcKLS0tIDBBUW5INVpvaFhRaVUwMTJidGQ1
        OCsrWXlhaDBkcTNiK1o1dGhURjNYa1EKaL/ZeKsMRrWksqc/wCLWLz/fu9DVSEui
        OsJecCzaWlOfD73IUow3+UHTklGiuBugCWVn3jHV7ZzpNzsjl9lTow==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1l5t62uzsj05pzftv9wg6s346csxyq202vxmmyyx8gwy8zu2nrfrs7v2a4z
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcG9tOHg3TnhLbzBKWUVC
        SGVZZnBvYUZleE9iNHdTMlR0WElRYnVwc0NjCmh2VjlPM1ptZVRHVkF2NjhrMEhu
        d2RKVmZNZ0hZNzJjdnNJdSswMldvamcKLS0tIHRiOC81QWJaS0N4TC95cnA3Mi9Y
        cFV2dE1LQngyODhoNE9XYkl5eWY1OEUKgF4DUtvGsAdgxT3uGky2pdYE5VqP3LoY
        NwN9wuegZ5iJL8x47FsFlkcx243XAvIgZeZyKEDDG8yZ9YRFRJgXRg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-18T20:34:58Z"
  mac: ENC[AES256_GCM,data:sSLc5/SvYQ2Q6zOOIDqHLeVxuqJ91BPPVmlWV1oxtBQd8qziE9zj4WgK+w4k/diy2jZCTLmYyEu/uQw0GL4lpmosC0jZh9WhAII29vNiE/PvmMibkKie0NcElPMy23H3G91NVPpoTBGVzNCRHbOPmIjTJK+4UoUiNU1M4nBKFq4=,iv:lPa4QvQF8CMFYPeNh5L/eyOvrG8Ur159rYKDTEMmI3c=,tag:rIJSe/y9/uiP5H3i3HLzBQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
