apiVersion: ENC[AES256_GCM,data:ljA=,iv:OsQhNYLjkiIzzk50E1qngiZqoKDtYzKGNWg65EICyow=,tag:ds5LsecaYExx9YULluzk9w==,type:str]
kind: ENC[AES256_GCM,data:lFuSjhb7,iv:1rpJCb0ZtSX7r11Cf5EkNMgLJbud2p5gGvL/f4jvJPA=,tag:2TFfB3gEPAp4XmGmgU8BOQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:HmdzqySSWu00Z+9K3Q==,iv:42LAVN205Y38ioltD8mqhKWapa+FlUvXdBNuBXzAWpQ=,tag:otTW267Q1PR/wY/joz04OQ==,type:str]
  namespace: ENC[AES256_GCM,data:47YR6Gc8ju2+,iv:aEkBhNKmMahYWbVSGwxSPwa0jAW54Smgzuep9RkgtYo=,tag:bCA70AeNQCtD+sPY5n1Rrg==,type:str]
type: ENC[AES256_GCM,data:IaBNUnxx,iv:ynVIWgAeh3Wchbp3PX8GMtocUHpFlqAR0+i7kbH/Bnw=,tag:7g9zyx50trLreNfPwsfHtw==,type:str]
stringData:
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:khUDdCsRpA3rddbYYIJlJaBOqgZeEidnxhGVgg4clb3aGBiGUFfnvPXfHp0=,iv:Cz6AyQvrLpFItDn8Ej2xX1OKwkoF6wFVNe5QnqhWuRI=,tag:q9/G7woxVCZ4cGA72u2Vig==,type:str]
  PAPERLESS_DBPASS: ENC[AES256_GCM,data:lbZ/iSrlxkW6HzossiIblwhmgDDsL+Syxq/ordcVX7G/5q+BR7BUw9tZSX3LzWeblR8llqXnBjNQjz0tDJQkjduPIlEwohKFcJWtYaS49Efj6jaE0cGQKQ==,iv:Oqj4svtXjqgXOudvDOfYKkYosuE6hfezbg3+5xzxu0g=,tag:zMfhlZr8LLHbz3AP7ryjIQ==,type:str]
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:cAfqzv314qosXdbt1G3X8qjBguobdbOAWfqq05oYRwAD/m++9ngQgq4n5GNxcJvzjV8Zfn6SKKC1yFfflc4kpFsFJd3nJtzuj+75Y2mUG659bFyGDvW4xQ==,iv:4fGQAAFPb7uBK8cpnwLB8JWnqRk4Ctgw4p3PN0uHajs=,tag:9WySOEcoKz1/hMMZfHWpMw==,type:str]
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:igsYjvPZGkN4gD/kiNFYUj4oQ4NItpfU2ueAAyq+bZ7BsEuuNVtEQSu+1icjawW5N9q4eim1e66BPg/a/qPaa8L7RylCQ5KKnNiY0jgI3qUISO5msnV8To3bLwhM0cwI8TSsHkB2nLzmLknxMdmR0gomRM4f9NexZvgyQ5P/yzs7hTQCJVMhc75j1KxwhAU1kMPcbXDBa9ZqTHPKdUIoiZ//x/HDg5sVFoYAAYNArwhd7Q08w9DuAe3zDSMcgxfGuwoNaKoLcrfDLM4J6gknAbgi+U7wdg2JNgMkaSok06W0xMN82RlavhY+7ZhkcRCIfQYvBBboAtyIfjPfzEVFLlwySEfVPJRIcOxmA2i0XHDHU9/PtXou7hSD2BaIXXY0PNPcmGg=,iv:kQzLVVabVLwAq7nlrS6rTC9pNg9cqg0sJ7kY/ce9JyE=,tag:AxZFd2dvPJ+CCeO+fGW6Rg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2THFXMkdXT05lYVFmMThj
        MTZSZmp4QXo1eFhQdlljOXoxZ1lxVXVublRnCnhXL0wwTnRmY3p4RmVIbkVZaTJY
        aHBXZnUxRDFTditFUHJqVEhGZERmZTAKLS0tIFc3Sm55ZUdWQXhSdjYvekxLVG1O
        RUdzS2QyaFVMb1lUdUUwU0tkcmZaaUEKk2z5b9NGWeKtrZwixrRwc4je+FvS9N/G
        2xaJ/Z9W0swU/YEmew2dna+NUr14/KGlAr1YCAxM/slBrumHH6yE1A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTWxJK2hoSXJHS3BhbGEz
        UW1jSjcyZk5Sb0JiZG5DVnZJbVBOMUQ3cmtzCm1kWmJvdm1HU0VnRjZCdWpxUnI3
        Nzl1VFVSR3hmSldndCt0MlVvcmcyWTgKLS0tIEc2czZZOFJ6SUNITmxsU2pBYjdj
        REl1ZkRsMUQxQVRrNWxZUXdQUGlLMnMKZU2SUI9w8czlzZa0qXBhlxNGtXJM3qZB
        YkptGm0qpm5V00aLvct9I2MEGW2Shue6ixBcqsIWScHNObQldOGMxg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZjNZK1RxaTZMWW4zYjVq
        YWRCYTZYR282czFlSWl0aDdpOFFuZGlEaldnCjB3Ulo3VzhJd2M3TFNYcC9pd2M2
        OWw3Y3VqYmxFMzkrYWhFaGREcU9EeUEKLS0tIGpaSEUyRHZ3VDZVeXE0RWcxMkxF
        bkFoY2pWdE12UjhzaExFNFpscGVsLzgKXaBbRYOM5GFmAomq9KgdXx+ORguLE/fz
        AI+DX2zrmBBbNEFCl11z8//jfH4/lbqJwBB+lIWMnHOoE3lWrtKveA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNEwzR3VUdXFxR01SUktW
        U3dYZzAwbmxYMHE2dDEyeFdnMWZqVS90MjFRCityN1VadnZaWjZwTlJLVHN5dHFZ
        QzRkdmZsS242UXVkMTc1bVRtUG9xZnMKLS0tIFpmYytneGc4TWFiQUlYZFRHTGQr
        T0ZyaTZNNjMzNTI4WnRycVdJdXJnRzgKYMSVVJAa/DeDIk6HKcGY5WRf7efk7wSy
        V0mrQbcAW60/jMapxu1+zgnq+P8avmXe2SHDWojrbqoSVUxoC5pU/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBId2tzbTd2UGM1ODZEdVN0
        c3RsVUpmcWl6Mzcra045M0VIVTZ0TVM3WDE4CmpFK04wNW8zUmpZZHA3SVBERkV1
        b1NVWnJteUU1aFpCWDlzaXA0Zy9PRXMKLS0tIFIyNXpocXZVQ3JLd3M5N2F5dldM
        LzAxc2ZGa2NXRkpqWDVXTklCR01GOHMK0S+0cbrfGL2EvwAc8yC7aUE5qBGBYaHQ
        4toTyMrt+fhjHgTY+EGlzAPX+/rHbmuIbymGQ5UgdjGFryC0IQYV8Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTUVSK1lxeWRvdVBScElJ
        VXhDSkRqc2RVNjZwS1RPUncvaXNmeHA5UzFrCjFrT084clM3VHowVDJ2ZXMzN1V2
        eFhqbXlsV0RERXYzbG9acUVzWjEzK28KLS0tIHgyeFBSaFZwM1ZVZTlQNFoyM1VT
        ZG5RY2tzamI4RFZGYitDYVRFb0xaSkEKzyu4nKGng7y4RVGNp23RLE9YyftPDA12
        xeTXVjJihnRznPW3VuR4rEP+Q9Wj9X5sdZHqkiXla+FPyzxwk8LHOw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMEJZWU02MDM1U1h4NlVC
        dGJvbklLbG5WVnpiNHc4T3N6OE5aVkRBQlhvCjQvNE1qcU5WcVV5SXEzT0JxellD
        bzJNT0R5Z05RajJJQUNJN09UdTJiYTgKLS0tIGRMeTlHTFBldWtrUDlFR0ZvNU9N
        OENiUFQ2d0FLT1g4SkdocTVrZG16ZkEKJFqiSrD+rdSHeAMrTpmtf0CIzp1vVXIX
        RePp7bViI6wcjzlGJItdr1irVCMhlH+R9z96L05bxYAaN1LokcTqAg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVXZKdEU3N3Q5Z1RHaHRY
        bTBKY2xNN0FwL1kxRXcxWjd0czV4VmZtSUNVClpwMmFTVW1wc2ZJUzhoVVlHR2JO
        ZzJDRmd5QXp6N0JnV0QxZ2d3cldSTVEKLS0tIE9nRHpWWjY3dlJ3N21VYTB2Zitt
        ZGVUZTMzbEVjZS9RbHRITHUyZ1lBYXcKGPDisdy+ElK8Y5yhGDKMtFsKxHp+JEkn
        4jUadj/+I5GNg/EKKKHh52s75K/HEWtniSabyzZzuLmSaRR4zLwp6g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-18T20:34:58Z"
  mac: ENC[AES256_GCM,data:sSLc5/SvYQ2Q6zOOIDqHLeVxuqJ91BPPVmlWV1oxtBQd8qziE9zj4WgK+w4k/diy2jZCTLmYyEu/uQw0GL4lpmosC0jZh9WhAII29vNiE/PvmMibkKie0NcElPMy23H3G91NVPpoTBGVzNCRHbOPmIjTJK+4UoUiNU1M4nBKFq4=,iv:lPa4QvQF8CMFYPeNh5L/eyOvrG8Ur159rYKDTEMmI3c=,tag:rIJSe/y9/uiP5H3i3HLzBQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
