apiVersion: ENC[AES256_GCM,data:yF0=,iv:CqrJpmToQynJAZx7LREOV1jumSWQfcX6nO9iy+9SJpg=,tag:d6bja5SXBRMQB40ysyNKcg==,type:str]
kind: ENC[AES256_GCM,data:R6wPKvLT,iv:pA7QYwnTe/jXw1UuvtLLjbanvQdk+3Yr9BAgjK3LLNg=,tag:SnCiY4lBkNOc5cKE3HaYhg==,type:str]
metadata:
  name: ENC[AES256_GCM,data:GDkisam0bw8BRun/GmhQMeom,iv:9S9w5aHWFQsj6+n61YexWD8av/bqEJDuzB/cFiedp6E=,tag:0NS4GGMkbfPtNiRSS3ntUw==,type:str]
  namespace: ENC[AES256_GCM,data:J31FNEFw8QQi3WI=,iv:K5XszIE/oPZve9/JhVlV/pLSaUrDbo8M6pdx1AJXps0=,tag:r7o8xHBz4S7kDF6dNvhbVA==,type:str]
type: ENC[AES256_GCM,data:qvoSZg0mjrRJ7rYCKqveif9Pee3RuYoR,iv:6+LZuTOWBAcbm2JzlxMMGu/FrFPdP3BMUwMq1vavhWo=,tag:54cW8f9Rf+qlMbnx45UOOA==,type:str]
stringData:
  username: ENC[AES256_GCM,data:Jkfj71Iekg7q,iv:/D6uTtaQbwAAlVMbfyMVQ6Bx9tfFpi/AvzkVAR7c1TQ=,tag:RTY33OElqRcT/GfbObGcBA==,type:str]
  password: ENC[AES256_GCM,data:ViFiG/DTh4cg1GgyZzplLeEk9WOM4FWqnENBaacICUqSzZq/o4RxZNlUoGHDnUaHiKgA4MQwEYzbKxwCCrDrXbzIL6x+yaAhWJlpq6oqv3cXi967J0HfOA==,iv:AbWTbdX8GoYbp0OGBXS14IaD6kHd0XqzMgHh95Ctlic=,tag:7rCH0ncXgKRjEz4QUtRI9A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdlJ2WnE0bFE2UWYvK1pn
        b1UzQWR3cGZudERpTDNlT0kyZUhYMGoyR3dnCk9kMTNtTmpZYXdkZGgxRnZ0ajBw
        WGFKYXZtdDdVVWU1ajJUVGlMT3c5em8KLS0tIDRHMklON1o2alB4V1pZcVViZjVQ
        V2c4SVZwSGdEUGFZUzc5cWQ0UUFiUGsKkTcrqP0nfh6f3Rs/OwppIoWIv/tdzex4
        BjjTMa7cGyt/pj54Kd9u1odFuI+h914AsXU2/eG+wOP5MiaFQs7BPw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaGFMVlVhYWFtejJqWE8x
        UHBmUnBqbUx2NkpQZ2VjSzBKZzg5bTlkRzNJClFUS2x4cVR1WWhhdi91K0VaaTJW
        Q1hwNTEzQUhNMFpPVHBDZkd6TzZiUVkKLS0tIDRYM2FwNStjUzJubzBYMnltQkhF
        a05TMGxnbTRWZ0JWemdLWE5pUmxLRVkKQG4wAazbYw6KYhn9ZEBGHMamxjLbLGwu
        RLnGSvqahffPECoK5+GAg6fTlqUUUefvK+qZqI4dzd965PPrKsa1Hg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OEJOQ3E5QVhFaDBsc0pZ
        SzFvMVhZdks1U1NjWnNVTms1dzV0bytSMUJZClVHOEtRcTZaeENQOEZDcFhyM2xO
        cG9sYTVNb2lTNVUrbmdKd05pTVJDZmsKLS0tIGRGK3ArM2NEUUhjdzkzT3dWQjhR
        RFFwR0NkZkFQSE1lWTB0RnpYbnAxMzAKp9gHf8nNYcIBEEi2VRC1jO3V1LEqVsRT
        g1oVE40PBGYmUg97KnH4m01+AMk4Qz1nswpRhmmZ6eerrfAaAoXkFw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6THNNWkZDRDRITEJhbGoy
        WnQ2NGdoNTExYUNzZG8vSFZrdHc3L081ZDBBCnFQM3AydnpnS3pLa3dTUFNpWVAw
        ZUs3NEF2enhjeHJzKzNrY2VMMmhZQzQKLS0tIEVQTjZzdTNEbHFkT1FISHRGVWl4
        eTFEcUpnM0pKMzM0L0Zqb3MrRmVyQzAKfefh78sJiJ/KXSWvNz1jGu1DQRFk9lMi
        A7tkX8Tz17FmTluaIMWfHmjK24EHKqOplW54SLUBIw/HlMsKylG5Eg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZ0ROV3M3aGx2cmk0SXk3
        UkljU2lmTk9MZzZsWnRGL1VEMWZlWk9LUjIwCjlVRU1MNUhUM2VlZ0dZWnlRSTBk
        NzVrblE1dUZSa3hzTWFVamJDM1RTV3cKLS0tIEc4dHBkb3dZb3pEQzZQandQT0lp
        TE1SSWd0U0ZWYkN0NHdMMW94NnFCRGcKrpYpdqc49mWKBLQTq0ca8RnPpic21SXt
        Z2ZZdfzE4xjp9X3+ZbNpXTZqPyPIErpXlSqX19SSfJngYQTAxdPiMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbkdITk04cXIvUmFWTnZu
        YTdoZGpYNDRjWHdTVVFoWXdsK2llY0VaS0ZjCmlpVUk0TDdPWUNOck9RSkFSTEJi
        dC83MWNUTE1iZmYwWlprNnJtQmk1ejAKLS0tIEhlbFFnRXRYdnQ5NDN0SGQxdVhp
        aXFHd212UUtPR2prRGRNZ1hick9XRFEKrAto//VnV/EYMvARLUoyqs2OlJormWtV
        jXkt/g2VTi9RxfqJarQmT87m7xAR4YFMRH5HK1OyZ0DXxFkZbAy6cg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1eXFCamxUWVF2YjB2Y1RI
        aU15NjhLVENHSmNvUzYxZU1xaU92UnlOQ1hVCjNNYzY0dEJ4R0tIZFN0bWRETFdB
        bElTMTJJZGpnMUFCQU1zR3BXMmZnRmcKLS0tIGhGeXlKaThtT0xReFF1TTllSkZP
        a3cveFdYNEg4d1dUNkNzUmp3elZQUXMKl7duZEfEVGgHTXnRybkJ0nNXCWTQ9yAL
        oSc7dAB6c0arKbBVMZkotSmUCht4Eb8s9607tSV/zLI6N4CW8GfdqQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSmF5Q3hlK1ZZRk1CRUxQ
        YW92SGFiSWJOVGpjK1U2d1BETDI5MzAyYUJVCjk4dUhXbjJYSVMyUnlUeStNM0NT
        UXBTS1RrdEtmUlhtbmxvMVNEUE1wSWsKLS0tIDZrRnpnOEx3ZHZnYWpmTVpsV1ZU
        cHpUN0FHNmU2TGhPZStJVjlqNW5aZ3cK0EFuSlw2N5YEOz+vsePCyRvudRTUk672
        Igqkf72NcWAm5A/h7XtFUWxIOkd+jtyRESw0Nyz9FIqqHpHc7VppGw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-18T20:34:43Z"
  mac: ENC[AES256_GCM,data:iVDFqXiQUpVdgBjd/E+qhS3yOQLOV3zwqOr8eJ6PIwlDCiMNvLB3p0Qxi6K3aOf6WIgPVJodEYz+BBZOP+KXFN+SDnofBlcPL/R4IpEmCA2futtmB0xSmN+UGJY/P1ZLFzmPPvuwOYB0EtlU8phoH6SIrpQ/YC51EhJtyQQsy1Y=,iv:ksp+U80oDgtIiz71Rej2CxcXcCSmD8QIFalJSVDOZHQ=,tag:nr7XJ4Nq7EkzL1gje+VSAA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
