apiVersion: ENC[AES256_GCM,data:oro=,iv:MXYEaC2Cu2oyOU3zNnyANjlqkXsOV8LYWT83zWHTEZw=,tag:JH9cdAvzUwQc4C/Wq2ii7g==,type:str]
kind: ENC[AES256_GCM,data:w3wWiuAm,iv:vtrn3mj9cL6Pogo1nDUYzp45NihHAYJ7VpzGeSayD80=,tag:gsFcGz60FHu6boafPKMKaA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:z+wOXp4je69AJzS57w==,iv:jWKQEBKGrPL4To1sbjpKGz0NxZwiEGPK9l1Js9JmeSU=,tag:HjgtcFvr1q8TfaoE5nJ1ew==,type:str]
    namespace: ENC[AES256_GCM,data:2UVScOA=,iv:0sRG4q+fLbU8nXGzw7qxghFHgByTpHMQue+D4I4GWdA=,tag:xhBroRZpg9vTytZ6jgt/fw==,type:str]
type: ENC[AES256_GCM,data:tcOavOFfLf2s767rJ2Sj27t01m2o9+8S,iv:2r3dDyfAJjswFre12AiVk2kZxUAz6rfNYa2mJtUncII=,tag:hcdaNyag+xMpFb9VOYxUDg==,type:str]
data:
    host: ENC[AES256_GCM,data:uJoYv6IUjW0GldguwzbTxW3G+sYtHcQ30fm09W7PfcwW1li/2VDUgg==,iv:TPfEdqVykUkxiPRPXftuuVwL0oI5jY74RKK5Ufbjo44=,tag:iGLWvsY+Scu3gL2wAPxvrg==,type:str]
    password: ENC[AES256_GCM,data:mY+LcJwVRwuHXQXPR6G322b+uB1vwyaKKWGx4udPwj6jSRO0X0UtVJCZ5fYZfDVhlbvSsz8cX/gKpYoa68XDOivl4+0xSPc7gPKj9i4RMbGD1tSFZBIvvg==,iv:UWOsr5lQcfaQbo9qkEgQXntr7Kae4CS5yb3/VHkqsJU=,tag:ExiWIozY8vN69Z1i3DVhuw==,type:str]
    port: ENC[AES256_GCM,data:I4wXwdNPALg=,iv:dTTHd/o63/BXoSrIQV+NwqJR7+wb6zqI7HqOTmYVFmM=,tag:uYExdKsJRLZ5tuSl+9Kczg==,type:str]
    username: ENC[AES256_GCM,data:/5XGfDGsELk=,iv:N+fvnSXBxNTa/Za/cLyP2pQxNkqhw8GwleALpHw69+I=,tag:ahW8tkzNmeETKunq5U160w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVjI2Z3B1aEFscnBWYkNN
            eGkwei8rSk82RjJIM09qRVgreDEyL21iMlgwCnB6eE9tK2xiOEhldUtRNExqbDhu
            Z1d0djVBNVdkRmxkRUZ1NmRWaGN6cTQKLS0tIElxclBQVUxIVVFmN3RFYlRXVEFU
            VkQ2NnNLNlBRR1RjemJDbGJ3THExeW8KUfYkzjM2MwrfhrLHcL24UECVSVvyEhD0
            jCOEBFS7TWRkueIAus6UfsJjV6hDjaP28b9lfJ0SsHnD/2xiLYI2nA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTHIwNHRuZDUvY3lKWmFC
            OEl6cEFabGdieVpjSTMwTUpPZ3l6NUJubW5VCmZUUStuZ20xRjlaWTJLTnVrU0ZI
            cFBNOGt2dHRLMm1oQ1I2N01pSU4vcWcKLS0tIFVrZkxjVzcvOGFhdUUvQy9obWY2
            dDdiUkRINm1xR2JLQWhvWnJ5Q29hUTQKKUMs4Djkrd64xhpaYrE83VfyNujaVDvP
            N9+uR2WytQuGTupoBVI1N4MYAQxc3ueRc588b69EPzmk854TIvgrNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbUZGLzErTldva0RTV1Fn
            bDNwRm0xdmd5S1NacW5GMjh6Wmhub0RicUhrCnZJbk43WERTWXZVRDFDNHpzanMv
            L3doTk94SWNTUjRBS1JWOTNMTGFNM0EKLS0tIG1uMEdUd3dvbHRJRnNDNURmOUtu
            aGJDbkhzenpRMGVVWFpRcVB4NFJnN00K0G192TY4ZLH8itapZ16CC2BSeMGkEWgs
            QFF5e00tYXGPhVebiY6h4LOhCLfP4DR7WvxMPoXO/oiL2qG9tG/GDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRzB5akU4N2hDeDI0cmtV
            bWlPdlA4VDdSOW5sSHV4bUNkcWRBdGFrZUVVCmVYQWp5ZXpseEgzRUZLT0wvYWZl
            TGlqbms3NUhQWWhQdGlORGliUjgyeEkKLS0tIG11R2RNUzAxVU9PUnpFR1I0WWFo
            RmZMRU1EK3lKSUFlWVhjZ1paaUo4NkkKaFyo3g/rx16Bp8u6XedefZlCuk/PClrl
            yVsBKDu+86EavUABbzRvi6WYHQRpywwDjloX2Fq2uBAVl7XJazlJDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VlFQQ0IwOVdJV0NvQWJv
            Wit0eTBYS1lxM2Y3VlBGbWprbWNSYWdZejE0CmxTRE9TT0x4bHFlTStmWFFCRWxY
            M1lPc3A5SW5tOVIycWF6Y093b0RsQXcKLS0tIDliRFpGeTduUDVmQUs1a0NDQ2Vu
            MFZjVzJCcDQwZFNLeGRMZTd4V29DZk0KBpcckeE3aX9w4gLjtq0LIy+6DmwZGg33
            IhNv3G60aaJQiyJmbxFyvpdidwIvHEyDF6vHnIpib8i5HiZkfD6rrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVFZnWUxBZWlXYXZFeDd5
            MURHN1FKSkt0VlBCRm04WUNDTHhaMlI3QXpvCm5QSS9FZlNqWDV6SHpRc3FvREpp
            SXk1TFFhaWdKelVrVmx3elJ2bDBuOUUKLS0tIFEzUTR3VDJRd3dVVEVMZjBQK3RG
            SHlZV2h6MVgyM3o2N0wwTzhmLzBTYncKs4GXYCjJpMzYOM36leKYs4buiRD64blD
            KXiOZyZkTzrWYFLAncIZkttiuWEwU5f4dB8t2buH+5/iGrELfXxqWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWN29USHZNaFVvTlZtelU0
            L3BLQXNnajE4VXU3a242RHc2UG5veHpSUDFZCnFZTzhGQ3hJLzFyL0tlaHVtVTZI
            VGRkT012N3U2OTdNNXFHbUpsSUkzTTQKLS0tIHJzaVliM2l2VU45cWN5Nzg3RVJu
            Y0g4SDljb3YvT2xpZVpMRUlrZ0xBbFkKPa2ksimEkN5rkwZfksXZlqXWmgfY6KJf
            DFOw92y1xnttjMpcOMDekYtnhxdeRHSGMExqcLKqs4l6wyFxyGeftA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVDRFaGxHRGQ0cVNBekJB
            RHFackJIUDdFTkt0SXhWMXAyL1FEMmRaSGpJCmZHTndLbm1nYWNqVUJzVXNCcUJo
            Q1ZlM0UxRzJqMERUaFFvS21HMkV4ZUEKLS0tIEs0eW1vMlRTZkttRWx0c041L1FJ
            WitoemtyN0FtVXI4NklLekx2Ry9QYUEKE92FtLeoMsqMXp/7cY8GqN2opssm6OYj
            tKGcf+qryU33QKTHqJ5CftKVj4r1PPAzkiXl99WTGDQNTuuZ1aP3Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
    lastmodified: "2026-08-18T21:58:48Z"
    mac: ENC[AES256_GCM,data:Y6I+ueHlVAXgjMMzSpsROSRsQak09CGD4eREbmI5FlwP3y+uUpy00KNi0n1ffpbqu5o/t9yqMRtlXnLWdDE6fk1CoeYTCm9Bx6eHWKzCeWWFkfuqAbfMg1MFJ0isoqKh4VsBKVopAH3IOWfXV3RTKAy+rth1oTYHoqWQgW3JfgE=,iv:E8pSFgYaWwE2i0pmyyEl8e3Xlh67JmFgwSf+K/ISuTc=,tag:ErAM+fmK84j7dlWqXsupnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
