apiVersion: ENC[AES256_GCM,data:/wU=,iv:j5RVzd+0Xjz6u7y1CglSGcX/SjhizyCm+O9+CIkI2Vo=,tag:4HcbiaDl9MBajxA581kdWQ==,type:str]
kind: ENC[AES256_GCM,data:HjxEbFHN,iv:4F0SmU6adpvGNXEDbkUIhBklY1EG3TYqunOKVz4O/SY=,tag:WaRKNH8EiTkKfyFy5AnWag==,type:str]
metadata:
  name: ENC[AES256_GCM,data:9mJtqmlVUEUI9PaM,iv:VI/lX7rT3VSn27DrHLgbxQ+iDKI66VB3GDLu3NYKdZk=,tag:SfJnTA9g6R1B3J0TtiYY3w==,type:str]
  namespace: ENC[AES256_GCM,data:S4VzuQfgsfU=,iv:FlU3hQDlBDrE7zWYxveJrl/nO+EH6zScfJSrQfyVgTk=,tag:bLhboYN8cO945U07DDhTDw==,type:str]
type: ENC[AES256_GCM,data:5oFKByTW,iv:th2CDWJwVLbcgnX8AGkmCBT161xoPlSaw+25mKM5akY=,tag:VffTaXZkb4/IjWPSo0Lblg==,type:str]
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:CNOUtsWh21PkhAWnpKwL92cu8w/TdqrGwZiaOANGdEx3VovmBbUQN+ydpThfkPnyqmQgKupA8/igz9sfbYnNvw==,iv:hUR7UsOWazRF/LZwXYEAhKjUNqkkviQcyR4v1KyagZo=,tag:cGAiRVMFtIYhz4cx57y6QQ==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:tmyYOV0mrsGKYx6MVvArfrSk/3+RFmZGI9uvlxQpwvU=,iv:PsgUhATJjvjtA+x7MtPwzM4pD5I7eo069NBUFP2f85E=,tag:xvnZsh+6sW8e/ECmbVaffw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOFh6eXR2MGx3TTJqNnNV
        NUcvZXV0TmdHRWxGeHA5QUQzWll1cXdxU3hJClNmWkdnc0dOakpYTUxhNW9mZUlK
        WXFUQnNMcWExbkdtMjBOM1NHL3NRMVUKLS0tIGt1em5SWFJkTnRoQjZST2ozVHUw
        WCs1VFdQMFhPR2xHUEM2WFJmUStkY00KY3+TucstojJzQOtb2gvWyckWqOXMPAIV
        foAmDmYI4OzONRTmKw4ezTvEnUJP+KZwTv1MSGJRmoh/gYGvX2boBQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZjFQaGQvcjVmVU1HMFJu
        NURtKzhrWnJGREdBTEh3RkFuL2pNS3Y4YldNCkNQb2VZRFJSc3JFSG9uRElSTzNT
        NzJrdnNLbnJvd2k0SjYyVG5TM2t5QmcKLS0tIG9Xd2ZrSU5WNmg4NGNqeWc4L1Er
        aGlpVWIzVE8vNnVLYnNhOFliZTZUSmsKLKXkTkFMwqnCAEhA1j8xabFKU3rDS+ow
        XZkeCPH1gQfyFpRtSDD0wtjZ2f0/n2IBPOZ37LXZQ1SL5OkIyVjOzw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZ0E0ZThZcXc4NTMvdEQ5
        ekR0TGFtOGljRWNGREtOQS85MmpxTzNoOFRBClhGY0psa2N6d2NVZzVsaHJZSlV4
        anZzcHh5YnpEUTlLbzVIUWovK09ybUkKLS0tIEdaMEF6c0Z2Y1k2a28zUy9qcVNp
        NnZhOXRZRG15d1hIYmd0b2ZVRjVnYVkKW5bhLu9GoiSBYEGpCCCo6OlIexkT7KNz
        d5SffARsvF8tHGHbR+/FAQOu7xeIWXKZ659WchDLFxvdYV9NzUWprg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tdgfvwl4qdptyvgxju3rwz9uh45hz422txzcgsrwm4f4f96x558skzxklr
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dXVJV3NLbEZVSWxEV2ND
        SEJzU05Hd3Y1eEp5QUNhYWtyUllMUTF0cmtFCkM2SFRkUWttSFN3UGNCUWVPVitt
        ay9NdHFHRU9hYlQ0RVNtb0ZONVp6akEKLS0tIC83TTVlNDdvTXJWeUNGOXNBYitE
        WFFad2h2NEh1dThxSU1qVVJJUVViaWcK5Hnn3+cEmacJ7F5Guah7i0KCfNgvrwWj
        WhWE3nvblf2rOWWFMbWMBGd56FbwDnuxrML5fvD5hHK3XdO64mg7WQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5KzVlV0NMVUJDK3ByaHFv
        TlhiQ0kwb3U2RithdkdZVVZISWlpYThwU25FCnEwcTFLR2NaZmJMbjN5L3V4UzBk
        ZjRGZTd2amxlOC9kenVIVncwMGEwUFkKLS0tIDJvckM2dGI0WlBTb2xUaGNGdGtw
        SW82OGgveEV3bVVVSWVGeXp2TXN0S28KdwbLcGcBQzeanpc9IaZv2RkQnLXwRfRP
        nS7PNiIHmSLriKdBPt4GRyVI8SFyxiGm28Ts6JMQNSBub5172xzsDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMFdqUTlQdGl5MHhkTnMr
        NHg3aXFFQjlsSkpFMlp2VUN3aVlKcWxoZzJJCjBXMXREbHVSeVM4dXppMkdNbSt5
        S0xYODBFbjVhK25IaTBkVXQvWDRvU1EKLS0tIDJwVHRER0hyVFZhUnFDUlNZVTZV
        ZTViVmw3dWp0VEc4NHNFaU1NYVlISGsK2G3cIamC9jjWwVGeyCoKj9d1ctV9LHqh
        biNJuVALfCiQE3K4CeSJPKEQCAhcS3Ki2Y2aZuKxgHwLgKinPOnPiw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTFZ0ZlZZdzRkRFpoVDhL
        RFZpU0RCZEY0RXliOXNXL1VzU2xNTGxyV2hzCitKcmZML3gwemR6OEl4TGV2dzVM
        Z2h1NmQyTGRXbzdQdnIxRmF6NjBWam8KLS0tIG9TbDBPQ2NuV2g1Q2ZmeWxUZzd4
        RU5TakYrQ284TVNrMWxDdi9WVGxVMjQK0TgXSC7vvOHb5V5PQgDqvVtliqDLUIe8
        EmLetbHdvqx/B40qvdUDM/Tl8JIkf+JrzXoEBZQlDWZVr56ASB3bMg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhM3RPaUNEWkJYeGVMak9s
        U29NWDUvYjF6d0xKZjlhU3J3b3lTSUk4TmtjCmZ1VFF3UUpmcXFvdXJTdFVZOE1m
        eDNUSURNOWlZV0g2bk9VN0RCcTNqaDgKLS0tIHIyVXZJelIwZ1cxNGUxbm1uMjBD
        ZFNTdWxUc1luSDNidmZGWlptNUtyTk0KEUbiOIGySvIhTdi7Z9h6tOWr7zY4pf51
        PvuRageJaEoN0sud4SNsK8LPKaj1xNRJ192sF5DmKKAEjddqoFA7EA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTVAwaU8wdXFqU2p1bzM4
        TU1IR2prcWtkc2dYalZ4R3R1NjM5N2s3OFdrCnBSN2ZubDRORHpZUEhyWWpCZ0tT
        YlZNcHpnTVlkNTRncE5SWjZCOThpaWsKLS0tIGV2S1Jlb1J4SnVyeG5nbjFjb0RR
        bXYvTlNWdkFUdUQrSXplNkF1ejh3WGMKk90Jc+2S/8aX30maJctLiCq0jkKWOzE/
        2fdkWB61VPEXul7Umu/IMXhsrn21UaDJMjPkD4xBc0HF1sugz9pwUA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZTVhM2EvTGx5Zk92SURU
        dWFxc1FLV2wyY2E0Yy85WWg1RlFFb09iYno4Cm9vdVZYcHdXUDhFbDNpQUF1bTdx
        YnBGSm5mN281dDdFalNsSHo1bk0yY2cKLS0tIGJiRUFpMk9LUWYzUGpoa00wWE5n
        eitXS2pubHc0OHU4QWNxZi8xN2JTalkK0jZe4SIqiwuB7wK92UYNyGDvr9NhIjME
        iHR2XQzQ74yzmLxivfT2xc8dNat3HE6oU5JkLV/U6/+2/32s1zuaBg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1l5t62uzsj05pzftv9wg6s346csxyq202vxmmyyx8gwy8zu2nrfrs7v2a4z
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVUZiWFhBNU81cjdaWVlR
        NVNFSEdYZFhMV0x6RjdvWTZBenB1allzdldJCldPY0h0YWw1eUtpbHJ6WG9WbW5z
        dlFzRmZPdEpwai9pelF2QVB5YlZCdHMKLS0tIDBUd1VaeG9iK1JQT2twRk1Kb3hk
        d3hYUWFsakdKTHprU2xLbTVPWGdhOWMKzTPIHodBMFor9xTc/VMexBO1U6nM9kWj
        s8ceuGGbSnD+tKKAiKnuNghA4sFTzQt1rm2V28zaT59eTGdlTMwBnA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-29T23:17:51Z"
  mac: ENC[AES256_GCM,data:EbO6ti0FdwGqMo4UCNQpiKNUvEBiHbJNqkSd9CHsYpHHzJKIVa08ykYvHBT9ZrplbtBaEnz2B/1j/2J9VfWR5iseIIMv4HI4Eth+69AR9+FciLvbR+/r987IJQni61q1X2wrGqX0lXuHFQPs+5OcRfZD/4LPwyZdgEpF3yUtck0=,iv:m7KCVT5dwjCZM3ktHTIkVwfp55xPkOIPAfzCwUEKrG4=,tag:nUyxEsi2A3PbTcodK1Ztag==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
