apiVersion: ENC[AES256_GCM,data:LI8=,iv:+MTSWat1yQmi2G6RhKqTtfuPXhIM6xggAlzQPHUdEF0=,tag:GSXiq9Ek1/aoXI7w3kqwBQ==,type:str]
kind: ENC[AES256_GCM,data:7zIJWGY1,iv:uNARdmcjBCkIwtFuCbjpFZCHRtXopkXzuiXhDnb4cEo=,tag:C5VoYGvIp8IwI8lX6dBqEQ==,type:str]
metadata:
  name: ENC[AES256_GCM,data:3YD4UIIG7EYpdqAA,iv:Zq06lKwjIm/zILgwa+KRMWrHDtocuAM5Kw2Twb0bloI=,tag:bxpnFStiFLIEIhBNI1gY1g==,type:str]
  namespace: ENC[AES256_GCM,data:+bg23kQwDJQ=,iv:SPg3+qWSqD/FjAMAi0tMPDU4hVZ/iuJnub2uQD409j0=,tag:iFlWVEdOpNZXM+BCU9Eueg==,type:str]
type: ENC[AES256_GCM,data:VEH9VWhv,iv:E0iRohkvm+Ljm0ePqcOBtTuj6ug8OZXhEqK5xZ/gOZw=,tag:Xs3Ki9DKXLQsNcTUcM0LJQ==,type:str]
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:BNrz1mfQVbOLl35U2IaDWiwfiUbQNK6b41ux3+kEUX/LNuInsokIijaOgNaEm+qfvjpAbRNQlNxt/Z3aUjevEA==,iv:+vEkD/EuPUUC2QD3q8cpPVenqwCVqGcTe+sEVG1vvYA=,tag:wpE+f6fhMBR5r4tf6Nq8cA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:y515To0zMlqcJuCXdbj4qUHO8e83e9MtVg9T1zWAzJJnTe2tsOZjmbKEDEXSUyAww/QbRATA332SosA4A7Tfeg==,iv:GGUrKNO5KOQ/+V0z1JDujVAF+Ixw8X9OucJZ/owcNSk=,tag:mP/opOOAFmKstt+9CDoY8Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnS25sVGxBRTJuVCszaTVs
        VytPZ0lTOVh1a3Zldi9iQ1cvTUkwekxCUGo0CklGUlBJdzM0Z0VicGVUQjR4N1dY
        Z0UwanpmMjdocUEvL2hVV3dXM0tGSDQKLS0tIHMrK0M0L3p6dVZTNFRuOTNLSHhL
        eExHaUdyNGxmM3A1bDNsOWhKRHFOUHcKjU0wAxR2gwWCFIBBbOd9J3DBUU8mGtDF
        E7rIlQaX/aRMY8cRhPKbk630fzp7aSM6+h6mIbZpxk0t79dNhJr9Kw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaFJuRm9wSndnaEZlVzFI
        TlpyU0VObjVPR09TbS9KK2pnbVE4V1IzU2h3CmxrQ2xqZHc5UXQxRWlkalhaOW5N
        bXAycFZ3QThhM1BuSytEeWZqL0J5ZkEKLS0tIENQZ2xCSDJ0RG9XMXJQMnA2S21K
        SmpPNkp1NFhldnJiV1ExY1QzQ2hDelUKZowJ17hnU8PSk6Idw8851egExOCDPMjY
        lOD5d42Q9VILz8RSVPpTv6w6QUB3g4yHDf3MhVNLymIEAZzYFVQ19g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdlBNcDlHSXpmbGFNS2VU
        eFB2REk0TGtZYktWQ3VVUXNHVEpWeU56Q1djClZrbVVWTURvOXREai9Bc09MTTNO
        ZFQ4YXBkN0lDckxSS3plb2dDUXdPc3cKLS0tIHdhNDFuTlBEUmYyNjJJN3JyVHJt
        ZUFyaWZFM1loQU1lcm00VTF6UHY0R1UKdNcr0ZLQMyopnbNyYU608GTBy0b2TQg+
        M69mN73Y/JF/+Rp4vj4coppjzuhQcvx3GsyANf5Bzr8+YHP2tR6USw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmN0VFanF1MnZ4LytDNVZW
        bHlITElKczBSclVEYU93QW85QWNNTmswNWpRClYrTy9kSEFxRlUza2w4SG1jMXM4
        MCswR24zOHBzVzBHcllocS9DZGlxWkEKLS0tIEN3cEdReDdGRzd1ZmVyQWpDbDZ4
        TEVrb0wyVmRmQUZJbi9CL3lKclFOSGsKKz2mtP5Bwjoe5OAc/nl20PzE6CNJnJMw
        hXiarYqA7Vc7nHaKMkrdMWUUlY67FIBZrrq/c1hfHEZaGTLrwq9hYg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT29BV0JRMXZ4Vnd6NjN6
        MEh3d2hVK3BvcXJKeVpacXNzMXZGUGpIcUFRCkloRTg3VjNYb0RpVndNVmsva1Er
        UGNLT2tYaTArbjN1dTJtWXg5elcxaEUKLS0tIG1FZlFUL1RiaVdEVUt2MnR4S05v
        WEROQ2p4Zk1Cams4ZEtjbmRORmZKWVEKzZFcojVObBa+b+nkICaeHJ+jdF3QA82o
        JQRJrxJIkw4VW9PvOEsdLkkfRHJpWuNZhKCw8ek3k60B3j4W/PHVrg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoS1JxZUlmOTE1dndWeFAz
        c243REg3VGh4ZVlNWk1YVXhwSU1lYm55S3hnCm9QdWtWbUtHakVVUzdUazQxbzdl
        eFBRRFRzeUJRQlJwREZwVW4rNTdXYkkKLS0tIC9IS3hqQUFkc050REZtTzU0amJx
        MnJhRjlUUDRYOW9DVUJLS1RjVHhDcU0Kb4+nSPjtpS26QXU4WxJ8A+NM/lblphKF
        9ajiFRE6veK5ZKNyr4eQoylV/3cgPFx7BGn+oyuxNlOIGONJ6eF8Bw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aVJHWDhuV2g2MDI3Smxj
        RjRzV1lFY2JXb2krL3JsWTl1emxNNWhKSG5zClRUcnE5OVpuUDJaMzdoMVUyWEJP
        VzljOXRkQjNGTithbHBKb2lmdkhFcHcKLS0tIGM3bHdMT3F3bHlPRjJzMHRHZFJB
        ckFIejhOc29mY2o5RVpReE8reTRCZW8KCPl8e5+pNgYeNP5fnIEqRGIGqCIOVdMV
        2kiahRLuuFSHCmEkq7OhgJBZliaeHGgxInN69cwr74IXqnJd5R7oIA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOVhpeTBkcWNDTkFtYzVv
        TDF5MEJQZ1lDbC9NY25kRWluUWVNekFTTlhzCmxwK2pmM2NER3g1b1ZDYjE4VXhJ
        dnlRNStraUl3cXdpU0dwdjcwNXc1d2cKLS0tIFdnNVhoQjRsUUVNZ1dzMlp2dURV
        akZBaDVxRG5mb1pPTGNkWm0yS2xhR2MK6JlJYvlQJ9/KiaQ7ElQg/RFalEEjWCyv
        S7FKBXSVtTXaIN2Uemgspl6P3ym3bzsGGriUOK46RrVaGyIBguyDdw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrc1B5SnQzaGN4Wm9LWm1D
        ZTFhYVc2ZXFMaTlxNkZyL2d0SzR5c2VBeUI0CmlTQ0FYaVpiSHV6NjlMZHlSVkxx
        cnlCdFg1ZTNsamVhakpodnNJSmM2b2sKLS0tIEpWdXE0MFNpUE5yQzVGN2Ria0F0
        ejRDVU85Um5lclVoNkhVaFNVLzVuSmcK4/zWkV7EnUqZbz87dN6Caq5x27NRfOGB
        aPhOm38lPLa4U7uZMn5momnOf80nUcBmKd7211Wx8Gndweo6Hrfytw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-29T23:12:52Z"
  mac: ENC[AES256_GCM,data:Sr8XCNp9KTReO1Y+ZSoukQpAJkfWR9Mb21ze7up8fWvevyERh5Mseh1rDhbR1o63u66VOH19Wac9qyvSq5Y9/9es6ky2pY9uxi0mZjvBuv+05J9sndBzLGE+CzDkR2Jsa/NPGFkm7D936ZSeqJh+wle4StEiRFf79M8mGcuc+1U=,iv:wwgs3EAjMSawiCAOWdOfRZHRVCnujtW3QqV0NVIbXl4=,tag:Aw0haJYfjVqtqxGkW4UosA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
