apiVersion: ENC[AES256_GCM,data:qfc=,iv:xjU8tWAjH+cNRF3H1zfitawbQ00PcuJHF4dMCd7u6Go=,tag:981AGZjYzuswiFOfPZwG6w==,type:str]
kind: ENC[AES256_GCM,data:CSk4ka4I,iv:hsFxj8jlS3cJHSyDD6ilZY5gfvD+6BgWTQ+mF/cD1Uc=,tag:K2UvC5LZH21eFPSKODcC8A==,type:str]
metadata:
  name: ENC[AES256_GCM,data:vHIkdTBYzgnZVW/mmRiAgRE=,iv:YQvO0u+eU54kZEbRfFwXLUg4iTFJHgHrwSIjkhjvqbI=,tag:n6i0q/bJSgD7G5xTBG7glA==,type:str]
  namespace: ENC[AES256_GCM,data:h56MZ0WFuCk6Ehg=,iv:FR4p+aGlLEGwOY1pxlEa0zSIy5LHEbNkyQR3NPqcAPs=,tag:0MTWl1i/FG4BRIzv6AzHRQ==,type:str]
type: ENC[AES256_GCM,data:YVdc1QYqcjzDNRR0hqIdPRlA3Dq4ViMw,iv:Yq5bFXf4Y+H3wp7k4iLoqrZu2oC/wqVOJupdFuSG488=,tag:yfUXykHPDsRr8mPX+T4WGQ==,type:str]
stringData:
  username: ENC[AES256_GCM,data:Vr6AOD0Guno=,iv:IPfsYkIc6Za2/CF7x5ggrS1Me8ODTHPNCua59W/Vx1U=,tag:pUQvoCyJ4jPpV+JuDmoIqA==,type:str]
  password: ENC[AES256_GCM,data:kNUQ9P8XTEZVBCbS6DpCUFppOK58hozUq6N55xgz1y/mB9yiNTVGmxBpmflz9O2G2CCwwJpAibB/dyxniMb8zw==,iv:I6W2SSuaATagTLvp1yF7N2W36r0oM/WwtroxWmO3kpw=,tag:vtMKl6Rq9uZ2NbXMxsyJfQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcUlHMFh3Vk5nM0ZLTGpH
        bkNCMXRMQ3krMitIcVFNMVdzYWQybk5pdEVRCjlsNlp1blJxVXQ4L1VPVSs0RUQ4
        eUdjY1FGUkRkVk9FOEt3cVM3UHVLUFkKLS0tIFpzakdzM0N6cHJNWHhybDlRd1RY
        WWJWT0xYeStYNEJGMmNVK3p0ZG5QRTgKnUkuGYivGUqHYUiuRS7TvFDRmEaIIFvt
        mn05yjANs2SBPEeiSoZp1A+DmpjZgi8cziptmWHmUzx7cz+EWLJiXg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZVE4V1lCY0tYbFVydTVt
        VkhHZ1lacXJEVVlJNGVPSjFyQ2pRNTUvZWhJCldYcGxLQzJ6R0ZsS0RubEJ3U1Ez
        SUlOVTM0ZlFZaVRLdEdldGJKak56SHcKLS0tIFYzU1RZbHQxK2tLMFpzWlJZNHNo
        YkNMc1dydE1KYjJzSUhIMzYvT1l5Zm8Kf9nHGDdE4ya2Kk2iPp7X0U7PJi8YLauq
        cfRxS8VoH8mvy2X4gG8dktxVdbtMsXEvziVoOpjfRwz5BrouLiToJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZy9CMEtMeVdrT084Mzdh
        MGFKNE5YTVFKRndJTlZLRitJTGNXT1l1M0JzCnZjaFlGTW9IREhMRzk2NTFwaUVC
        QUNOcWtaTmVEamh6T0thY3p3UmRsNncKLS0tIFUzN1B5UVk5bzErbXVXbkUyTG8x
        ZUxzRTFzUVltY3gzVFdYTFBESlM3RzQKvF+TzcAAFjnxmjrMBUZASgmjGW3dGI0b
        cfXfGvr0QR+66YXi4cI5JeGNSrXnxRkMfkf82oOBof09ljcBftyYBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tdgfvwl4qdptyvgxju3rwz9uh45hz422txzcgsrwm4f4f96x558skzxklr
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRHI2VjFyS1o0S0hhcjJo
        dlg4WTN6TEZFR0hWWWZabm9VL0UvSEE4WlNFCkFPUlU2NVFncThTb2FIdHpnNE4y
        QU4wSmtnSGk1VWdUR1lqU2puMnlWelUKLS0tIDBRVmNrOGpRZWdUWmxnRmtRZkw4
        cERJaWZ6VGlSR2UxbXZPWTJFMG1iK1kKKPLwsK1xPW7/IEoonld1DzS+gf+wfuRw
        UdIWTI8XXtQn+5kAPU2VWkZTWfZxCG+KppOVujNQsiyPZ3q6sakilA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OTJBcWlEZXErMWhGYkoz
        b1lGSkJXSXBZRW14M0lJczFnUk5QRTNRbkVrCjRTeURnYmtWRXZ0bjQyVjBpcW9Z
        ZnZWaGZzSDZ3MXNsOS9LTSt2NU50WUEKLS0tICtNNDQyaFZLMXpuSXE3d043cVhW
        ckxPWFkrUlErWEhTZUE5U29VajNaYWMKFaIh5FdPwtTNjVZ9elksdYBK+AudkOqo
        xxoECR1raxL1JDkAJknZGjaHclC7DNApKetVqcdLUXG29jawuN2a+Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWVpBUFk4ekxjQnpwZHp3
        bXZ5dnBPUE5LdUhrMGEycStoTUlnVGFxWjFzCkJuRE5xdVJBRXNOeGJMZ0ZtalQ5
        M0xnSzVHYTZkNGlHNjQ5RGVvTHRFRFUKLS0tIGlySmE5b3k1OHVoVWZ2aGN0VHNE
        UkJHak0xRjlxZ1VuOHpWRGhWeE1WWjgKcBBO/CTPE7zZlKfrKnn0eMcOmQMZn4IP
        bHXTvPzyRmdRWtlI30Djg4ZKYFca6ZdX/8Lrb/8E5vY+VyxugE26tQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bWFnaW5ZYnl1N1lieFhj
        Q0tYQ053RTU3b3RDd3hDbFlMaVpjY0hiM1RnClJBMHZ6ZDVZNXBRMUpUTzNINFo4
        eUJvQ1JqcGRtRWxsT3VpZXc2cFM0eWMKLS0tIFBxcS80WEgxY0NVZmpXbUd4ckZE
        bmlKQXA4OHJwdFAxM1NlVnY5akJrb0UKPXVUwaeTOozK1MsqhfHQ3key+TrqvLlH
        jHrZcBCOz0t7RnLJDPqVy7ZyErrGiGf2Uj0rBV5uwFzCMJYLL+p8vA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WHBINENOQmw0SWM0UDcz
        QmJFc0c0TUkvdWZJd0RENTBDNi9BemJqeWxBCjdzWXZmU1BoNktJZXNJblErejNF
        a3NjaFhSLzc0aS9hQk5kc3RiVm5ybHMKLS0tIDBzeVJ1ODRFNVgzZmlPTDk3OVdk
        R1RBdlFhUkxqbmE3ZHd3M3A0SGFZMW8KgWmXhzmjMcAZopd/pSvP2OYGiM3PWSn6
        AanHxDBWU10sPhKbFSDek2JgHe5aJ0PXDi0aedrVG9D7otD99rCynA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNWZNbU1qMG8xSVA5ckxm
        bWRLSjNNRk5LT1V4RGFCa094ZjdRbUhiWWdzCklicEJLb3VuckU3TlluTlJxeCt0
        dmtSUVM4aEJZMytJK01jT1JrV1A0eEkKLS0tIEFRSHpsSmpzRW5sd3UybURUb0th
        SURjanJCTUJCMWJDNG1INCtqMDJxdUEKdj9e9ChyWkVEkZIFk2WUWAAp1guyEsKO
        FIzpcz+C5fFmXNRb4bMEhWfIuE/GlLFgU4R9o/1U2vEkke1e665ZFQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNkpiT3ZXcTJIalJMeUNt
        a3BRK3Aydnd6SmxndkRXN0Y5V254K1FRSENNCmJKdWtyajNpS0NMTEVyeEcwb0Vj
        azFiNkJIUjBOaWU0UVltMWVzMXRWQkEKLS0tIFc5cU9TdFZiVkQ0eVhIVmRlY3hR
        aTJzVkxIbFdyY1Y4YXFkK013cGg4OWMKC0GTmoIoTDJW0u7SjJm3fZ/N59G8go1I
        g2IDMXOE7sPFwFabJ32xU2H3PxamfM7tWAR3xD3KsEW/o13VqmjyDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1l5t62uzsj05pzftv9wg6s346csxyq202vxmmyyx8gwy8zu2nrfrs7v2a4z
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweWk0RytvVDhWNEpxZFF0
        QktVSzd6c0paTC9wOTlDYkpzemdWYUpyNkdvCkF5Y1FZK2QyVmtYM3Vjc00wWk9P
        THBjcW9ISEV4dUlLQ2pUTlNFRWlZbVUKLS0tIEU4clBLb1hPYnFQTHR5NFExU3Ix
        dkM4ZkpJcEt0QXlDUGY4KzBZazB2QTgKnmjrNPoPv+nrh1YJ2kS+8hcsWbKaODYd
        DOquYhBJB21SQx617ZOHXMDJmPWBf+SB5h7O762Dyqv6t7a2JMC3TA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-29T23:12:52Z"
  mac: ENC[AES256_GCM,data:4qoa+YHj078nEiFizasrlKRQ+MOTKx1GpxV9WodpiiEMERoaZzVuuDWinh3LszR0GhHGd8N5fowR61nhHMm6tH+nNvtyd6+kFRg5ScrWyOiaW09W4+Eeh+ZVr0YsiNasuR9uQBIsFgMwssEM2FRwQNzMnFXnnDZn/6DJFHcby+4=,iv:9vcqhzYwSXvtxLd8G2BCGM5oqMj726M5IFimfgG2WG0=,tag:wQ1U2onSzagTXFo5l6yP2A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
