apiVersion: ENC[AES256_GCM,data:/wU=,iv:j5RVzd+0Xjz6u7y1CglSGcX/SjhizyCm+O9+CIkI2Vo=,tag:4HcbiaDl9MBajxA581kdWQ==,type:str]
kind: ENC[AES256_GCM,data:HjxEbFHN,iv:4F0SmU6adpvGNXEDbkUIhBklY1EG3TYqunOKVz4O/SY=,tag:WaRKNH8EiTkKfyFy5AnWag==,type:str]
metadata:
  name: ENC[AES256_GCM,data:9mJtqmlVUEUI9PaM,iv:VI/lX7rT3VSn27DrHLgbxQ+iDKI66VB3GDLu3NYKdZk=,tag:SfJnTA9g6R1B3J0TtiYY3w==,type:str]
  namespace: ENC[AES256_GCM,data:S4VzuQfgsfU=,iv:FlU3hQDlBDrE7zWYxveJrl/nO+EH6zScfJSrQfyVgTk=,tag:bLhboYN8cO945U07DDhTDw==,type:str]
type: ENC[AES256_GCM,data:5oFKByTW,iv:th2CDWJwVLbcgnX8AGkmCBT161xoPlSaw+25mKM5akY=,tag:VffTaXZkb4/IjWPSo0Lblg==,type:str]
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:CNOUtsWh21PkhAWnpKwL92cu8w/TdqrGwZiaOANGdEx3VovmBbUQN+ydpThfkPnyqmQgKupA8/igz9sfbYnNvw==,iv:hUR7UsOWazRF/LZwXYEAhKjUNqkkviQcyR4v1KyagZo=,tag:cGAiRVMFtIYhz4cx57y6QQ==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:tmyYOV0mrsGKYx6MVvArfrSk/3+RFmZGI9uvlxQpwvU=,iv:PsgUhATJjvjtA+x7MtPwzM4pD5I7eo069NBUFP2f85E=,tag:xvnZsh+6sW8e/ECmbVaffw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N3A0QmJLZStvdk1wTjdS
        WXk1UjVGRE1IM2tSMlRzYll0bGhGQzV3SWpnCkRhVXRzKzJvU1p0dW41Mm90QytP
        azJ6bXdFcDUxZFlHaFRNVG9GM3FLejQKLS0tIHcrWURERlBvb1pUT2Nxb1kwa05M
        RTN4Z0dsR2tzb1VxQ1c3VFNzVGpoNFEKcW+zppIoPhxheL2XxG75WZ1O06GO2jds
        PjfLRLJ9IkGB8CG8D5Vug8waFgKSC8El+ktPk9ia3B2pC4PXrfal1Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpa3hSMkN1eUg4U2pHbUZ3
        RXdOWUFMNElSS05uR0tXQm9tZmtJNm9MbGpvCjFJSTVtMThZSXJEZmV2eURXNHkr
        UFRzaHRtWitkOEZVZlUvNnNTUi9keVEKLS0tIFYxck5HWGtSTHMrMUxRY3BiaDRO
        WHRQcEU2NW81eXRtTU1UR01pQTlUcjgKLnFJKB6q3WsiLXo5Zx1b9qU3KJjrmBEE
        52OupU1aEtakfjx4/AQoKb/b0nceVyG7JzR9W+JlSAxl7400XyQqzw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0S2kvYXVCRVVIV1hUUjVQ
        WXhkZW1mZTBnZ0NsMTJGOEZ6RXFNTnBUNFNJCkU0Y1ZNZU4vRVdReXVSMFp6cHFs
        WGcyaXZGVjlxazAyV1hGVVVibTRSZ3MKLS0tIHVwVnVKcGlMdW12VFdQN1ptNHRn
        a3lzZVZ0M1A5ajJKdlBvNjdmUHlsS28KCk1pgieMq4YtZNEfttQH29/0GTqvdwKh
        i47JHvckmexMuMvpEH7NtfflNAgiPpkpQwhurwcdjOAW0vZF/2h5Wg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYnp2K0dpSDA1Qk9XRG5K
        SDZUWDBDT3BLTWM0T25na0dSNjRUSmxYUGpBCjJ3NjFNWUx0QlVNL29kT0VscW4v
        NnFBV3BGeU1TT1Fkc0VrK2VTR2V1dTAKLS0tIHBCNUhLQUIveVZIR1RRa0lIdnFq
        cVk3YTdMUTNDbkppdjMrZmlSaWZtek0KYN7s5CjELfY05Ops64U4kQ4DSLab2NN5
        ZLTYJ2DSORRP1XTif9a0Uz5ZAx67OfVeQmrb4PyIm7V3v41Aa6Pzww==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnK3VHUkdCN1VkZExqNFlL
        WFFFeC84M0Qvc2lkNzcxeVdKaFplN3JkNVRvCmExNnIrZXIzNFVqV3pmL0xTMWlp
        ZG5pRkh6UHpEMGQvbldKVXFIa3prLzQKLS0tIGM2dkE2RXE0bnd1ZlcxYWdHb3JZ
        b3Q3Q2ZFVWZaUHdobjBRZ2RMTnhLbzQKfMp89wz5kpc0kphFY9RybvbRjOEgjzkS
        +ypOV59V+jXKeI3G5qsHSmqV5Xz/FjxkXXvY0Q9fsUTaUL4V7SyyDQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbXEvT2x6WjlKV3JmdUVn
        bXFYYU8wVHIwZHJmbHdWS2xPK0pmNlNzV1VjCjFEVHpaeVBpdU9yOTkxUGFHeVdE
        Mllqam1JR1FPWGJka0lqQjJLaTNNdFkKLS0tIElMUmc5VFZWT3p5YW1SZmRDaUla
        eW9KZ21VZWhBZmg0eWV0dDFaRVNWelkKoPDS0aJ3Pk8D6hJ88HEIw4r7+OKOJb3J
        7A+4VBz9dbmopvCC5CH6MGi8UVseiwdFSlxy0ve1eplir8kOCli1TA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvS0xLeCtWeHdNU0RVYW9l
        QWo1bldPY09kWFFzcWR4dDVLK3ROSjZzL1VFCkE5RTRnZWJQMFAvdkZPMEllMmVa
        Y1ZtUXdZSmdFZ3JsNTNIQ0FHMjdJa3cKLS0tIEw1QTdrZlZPZyt6SW16K3NLQ3RL
        ZTdhQVJ5d084Ti9ZWGZNZGh5RkQwYVEKaqADkHgJL8EaKnjFX511t/J+9lrCS9I2
        TOmY4SWYfJRw+m3EEOx0kzz5NYmBE/azYt8JHnEtNeysapkkLPAypQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdEpTVXAwTVJkMUI1d3Y4
        WkxqbGlnc2hIYXBadzRrSmo3Z0h4dDJnV0Q0CnZTSVFGbEhLZGtpeGIvNFN1amJs
        d0xZOVQrWUtCditBeHRrUlJITnlOK3MKLS0tIFZjNWtXbmdKclNuUGNiUXl5Ukhl
        YjFtZEtVSmVDWlprcmc5eVVZcFU4Z1EKeVu/TcsBr9fvNL8QCHaG1Fqyd9AWwrEm
        q7gEfAFzW42UVImxWng+dTPDurvkAR9SnqTtvPZTo5DueNAi+ReMyg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzL3hwUnFPOXEyUFFKbWNB
        V0gxMFY5RG0zQk5CUkpPVFEwa0N2OWtQY2o4CnF5SitkTHIzTTg5MnlMZ1pSdjRo
        WFpjbmFrTFNXQyt1SWkrR2J2R1hEK3MKLS0tIHgzdXRnb1I1eEtWNTRmL3d6aE9H
        QnNBelV3VGZTc0pON2R3Q3ByekZLSjQKgYCUnEMZ8modwvIzXxAvWiUIM+jsZ9Hz
        PXNEnPhOq7njSXK0XqgEdIp89dkdU0Vn+QmJZD9bCRVyRzAe00enHA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-29T23:17:51Z"
  mac: ENC[AES256_GCM,data:EbO6ti0FdwGqMo4UCNQpiKNUvEBiHbJNqkSd9CHsYpHHzJKIVa08ykYvHBT9ZrplbtBaEnz2B/1j/2J9VfWR5iseIIMv4HI4Eth+69AR9+FciLvbR+/r987IJQni61q1X2wrGqX0lXuHFQPs+5OcRfZD/4LPwyZdgEpF3yUtck0=,iv:m7KCVT5dwjCZM3ktHTIkVwfp55xPkOIPAfzCwUEKrG4=,tag:nUyxEsi2A3PbTcodK1Ztag==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
