apiVersion: ENC[AES256_GCM,data:qfc=,iv:xjU8tWAjH+cNRF3H1zfitawbQ00PcuJHF4dMCd7u6Go=,tag:981AGZjYzuswiFOfPZwG6w==,type:str]
kind: ENC[AES256_GCM,data:CSk4ka4I,iv:hsFxj8jlS3cJHSyDD6ilZY5gfvD+6BgWTQ+mF/cD1Uc=,tag:K2UvC5LZH21eFPSKODcC8A==,type:str]
metadata:
  name: ENC[AES256_GCM,data:vHIkdTBYzgnZVW/mmRiAgRE=,iv:YQvO0u+eU54kZEbRfFwXLUg4iTFJHgHrwSIjkhjvqbI=,tag:n6i0q/bJSgD7G5xTBG7glA==,type:str]
  namespace: ENC[AES256_GCM,data:h56MZ0WFuCk6Ehg=,iv:FR4p+aGlLEGwOY1pxlEa0zSIy5LHEbNkyQR3NPqcAPs=,tag:0MTWl1i/FG4BRIzv6AzHRQ==,type:str]
type: ENC[AES256_GCM,data:YVdc1QYqcjzDNRR0hqIdPRlA3Dq4ViMw,iv:Yq5bFXf4Y+H3wp7k4iLoqrZu2oC/wqVOJupdFuSG488=,tag:yfUXykHPDsRr8mPX+T4WGQ==,type:str]
stringData:
  username: ENC[AES256_GCM,data:Vr6AOD0Guno=,iv:IPfsYkIc6Za2/CF7x5ggrS1Me8ODTHPNCua59W/Vx1U=,tag:pUQvoCyJ4jPpV+JuDmoIqA==,type:str]
  password: ENC[AES256_GCM,data:kNUQ9P8XTEZVBCbS6DpCUFppOK58hozUq6N55xgz1y/mB9yiNTVGmxBpmflz9O2G2CCwwJpAibB/dyxniMb8zw==,iv:I6W2SSuaATagTLvp1yF7N2W36r0oM/WwtroxWmO3kpw=,tag:vtMKl6Rq9uZ2NbXMxsyJfQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbmxsM2tiOVlKUVRYZ01v
        OGNLcTdZcmQ2eXVEQml1b2pGMlJNaGZrYWc4CmVSVHIrQUxkallDOGlSRStCQVBQ
        dTJmcUxKTE5UUE8wTWJ6SDZBbEdReVkKLS0tIFI5dDVERDVKYjY2M1IvNVZTQ1dH
        cHFjNFZXc2YveHArVnd2aUlnSUFwVFkKjcCpCVaHOqst6KE1mVbqZA0pFIo3fLcP
        jKCXDXR0GOX3KdJYcD+YRPwNjcYSVvuum+ZAsCj8/k0Hazz+6uk26Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Vm9xM3ZYaDE3QkF1YnMv
        UTFWWUx5UmhBdE56dHlyeDdFNEU0VktCYmpFCm11YVlzSkNtMGpMeU9temRNdTdl
        Q1A1R0lIMTRVdGJkTFBPV2RVUWhEaDQKLS0tIGpFK1hkK0JHMVAxbGJXdDcrZVl6
        UjIrMEk5aGNNZGpLTjgvTENQTThHU2sK+HT/gDuaNfHfWnP+E9SCt2maViPxuZHu
        vN/JCK7zMr1qq5od7SeQGPDdrKPH+qhBT1j7ZJ+NJ26oqB1m4nIpTw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQUJ2eWFhazNqOUwrRlhK
        L3hQcG8yN2ZIOVZRYkwzYzQyTVU5VjVkVXpVCkZLa09TMExJL2F2anRVdlJ0aFlv
        S2g4alAvQ1NRcDdkUEFrc0xUdnl5bFkKLS0tIHNlUW1PbFVRcUZON085YytSeUdz
        ZFdiN3BhN1ROMGVjSUpUSis1WURWRlUKvA0JFOrJh4UEplWvpxtfQ/9W6p43B1nD
        vkBWQztFGdrHqBDhDuqA8frzN3NXgw2jCHPyOGf+sCfCmfv5NK2GkQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGVndGE0c3YvbThhV3Z2
        ZkNFVWNWOCtRanJHbWtYbFBHcFVqY0VGWXhvCnE4WHZxTkRxSXRXVW9oOWh3bmN3
        SDFrKzJsNDV4bVhOSkpsTFNnbnA0SmcKLS0tIFcxYnZRa0lMdmFiSTNLYU81dlc5
        VTZLdW9rbUVkaU1zWGUxQXZIczl6cDQKcxht0WLCpOTY7B1AX6szc+E+dAI9h/8i
        FQkN8CWRynM6/wST6b+yhH7IYbkqY/oPMJfN4s392rH7aWw40IgFKw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3U0E4ajl0ZUc4cDJDbG1L
        eDQ5YWlrNXpFZ2NOcEJTSDFnUnRtdVpVZ2xZCllxT2hBQU9oZ3BlNWQ1R3VPUHhs
        Qy9sTzhyYTlLNkg3dTlkS0ZVZXJGZFEKLS0tIFdXRVdIOGc1V3p1NmZnaUxnTzBO
        RFdXdE5kc0hLMHdhdElWaWZzSjlpRWMKmPCtg/I2gG+f5eVfkbu8MqS7c8cc8v9k
        fid5cPRmCk2NZ/pA6X3/XDJYwQ1L7OLTmkmArX8Paa1rhUfaKeqqWg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwak42V2JSQ2pRZS9nYU5P
        c2lobER0cDYxY0NqQmpoRElDejZNRTN0RDF3Cng3bHJjOEZKRW9JUjMxVHRLWlE3
        c1NjUCtCaXQ2V2VnakVOYm1JNDhYQWcKLS0tICtjR3ZPMU1UNFNWa2ROaS9iblpH
        VURsZWh5RVFOMGZlc3h5MVlFRXNoOWcK7D47buWQ9O76y7ij1LXVtcNRLlsUXVC0
        /DKtuT3ofmFm4p91YXbpWZK79n6XJEp2DymBMyQmctrwZaKs8J6VDg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWThCYzhqY2NsVGlWTWQx
        bTM5SnFTbTlZaXFSQ1pKMUt0SllkOVlkNEcwCndyTGR3NTNVc2lTcGdPVVBYaDAx
        MjhudHJwVnE3eCt4dGZpZnd2ZklTb2sKLS0tIHZtbWFwbGt4MWxKekQ1UjNnUXYr
        VmpSMUFvU1JqcVQ4RHNMeUhKT0ViWkkKSInW7SjbByg+rvgflQKCJA022YETTubM
        5zDs72oVa4zXWzgk6EnKKHNPXd05TrP7KEMiYkhxE6pDl75hPKmflQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkazB3emRzUGNZdlN4am9z
        VTY2UjZOc1BYWHNNYXVLUlE1ODU2cFNIWVVrCnF5U1pvQk1rN053MGVpQkt6UmN5
        NjZrRDIrU1pwZnVVSXhYZnQ4eWsyRDAKLS0tIEQ3YUxhZ3dnYmYybWtCZFVQenJ1
        cU85TWgrdlE3NFZaSWFVMGRWT2g1eUUKMEfTORWn4ns9BsDbcmhwcvS7XhPxg6Ex
        UgoQGUTWVVh6AiemP0lHQ+fX4Bcijo7Qk/FF7gZmqZva5dhNCUHylQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Q01zd0I4eU5KWjRzSFBm
        TWEwSFBtVnpWbkh6Rlc3cW1ydjh1Qy9xa2lZCnBsQVZ1bVp1RnVqcGVNbGQ3dkNW
        VzRJV2tNdkN5bndUMU1sdGhlejh4VlUKLS0tIDhNUGd2blZ2TlR0ZzRZbU15ejFh
        cXl4OVZYbWZKVnpvWjc0L2R3WVJSUDAKvAinAjYSuAU1vqwlZSVsdeef70BZIPMg
        RKS9vRclrrQe+XclDo1VSnWCXUgTeSN7ReseS+XztQ46HOuN2wphFA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-29T23:12:52Z"
  mac: ENC[AES256_GCM,data:4qoa+YHj078nEiFizasrlKRQ+MOTKx1GpxV9WodpiiEMERoaZzVuuDWinh3LszR0GhHGd8N5fowR61nhHMm6tH+nNvtyd6+kFRg5ScrWyOiaW09W4+Eeh+ZVr0YsiNasuR9uQBIsFgMwssEM2FRwQNzMnFXnnDZn/6DJFHcby+4=,iv:9vcqhzYwSXvtxLd8G2BCGM5oqMj726M5IFimfgG2WG0=,tag:wQ1U2onSzagTXFo5l6yP2A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
