apiVersion: ENC[AES256_GCM,data:cqI=,iv:CRbQtPD5aOPoO6ejVoBQTT1RAm5Ama9UdLTqK4fwTAE=,tag:EqojrIM90cjFDhQe7O4tZQ==,type:str]
kind: ENC[AES256_GCM,data:ZN4DeQFj,iv:K3afZ6/C8A8r4sqk0/l6Dq2by1t9ghtJIZnr/nBBFfA=,tag:iwnMTsrVyn5TVj1j4L7q/Q==,type:str]
metadata:
  name: ENC[AES256_GCM,data:ssfhoEYAcxepkaNridJn0Ylx,iv:rRi65voLqZ4b1pkngf1X4NVYFZbLd7b13Qv8IWrYxcE=,tag:lFzTSnWnmOt6o76XbKkDog==,type:str]
  namespace: ENC[AES256_GCM,data:W4IxxItxAdV8nZo=,iv:CAcY/k2L2mMdvn9i3zt1nh2z26Hknc0d8av9DLZ6OLA=,tag:sjnBqPo5SYcj8A2GGOSxgA==,type:str]
type: ENC[AES256_GCM,data:1vaX9JzxkfZ+IAZ6cvmxNnLZGmgB6WRE,iv:Hgx9JKbSanBfqVQlLebU3NBRhatF7vzAfmlCnwMxX/E=,tag:ezcJAl4HF/HkMXyscuSmqg==,type:str]
stringData:
  username: ENC[AES256_GCM,data:kIO61cu/YUYu,iv:2YJA0B5k+Qwrh67ZJVBMbZBSIpuqMgK9qZV8LeijO+Q=,tag:54g5hS9AD79J9yn9192+yw==,type:str]
  password: ENC[AES256_GCM,data:xJUXI1fcVuAJMcBiJMCxjz7tXWBIQNl/j1WGF5pQF9y6+p+fjnTr9uA0rD7rjAjl7GxOJRrNBAiLMxvA/iGrzQ==,iv:kwvs1RoSvEkv/mUoVhT/OTjiLPa0IswzC+to3cannZ0=,tag:TvvXSXg+A8WVVpo5ok0wPw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OStCQ1Z5Q3lyeCtGenkr
        Szg2Vm9nT2ZidXE4ZkZWWUUzcXpOTEZMQ21JCmJ1RGgyd1dydjM1bHgxMzhrUndZ
        dHNacEUxY2RyQ2FWNkl4OVFWYzNSVmMKLS0tIHdveU1EM3hza0VDVTZrSzFCMFdY
        VUkxM1NTNDhSeTBNUm5uZGhpOHRxcjAKM89AhJaiX1G3UOIA0LvzJI+9cFJZ0RZm
        NThoEEqSJpaHn27mG09lx5ZkBPNsXyWtyvfRRrSQZJ0A2UW2xdaU8g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUDZRaWx5UHFJQ3ltczgv
        eVZLdmxSb08zaTRVRGo5b1cxSGpxK3g2QmhrClJXSlBBOGRKSGZ3UEdpZWMzWXRj
        TGoweUc4WUZqOW5vMCtBZVFJdnhUTzgKLS0tIGNOUklzQWdZK2ljbDJJOWhpMjd5
        RVdVQXRFZ3JkZWRnblI3MHpUVjJLTEEKl5DnbVjLF7zQwZqmQ+7y4YpQ7kOaOAIP
        bB+K3Yp9SC4jZ0tIvqS4M1p9aIEWy9XX7KAe+aObr5pDZby5g0OuWw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByd1BmVVhuZ3BmRFNST2dM
        b1RmeUNZbFd5YUcwbnpmYWNEWEhoNGZuNmxrCkVPQ0dndVc5WWVmZFJRclRKbmtT
        SSswOW5FNUd2aTFzbVIybE5iU25LQW8KLS0tIGVhOWQ0a1V3cUpKUmZBaWppbmtL
        dUc4V3FaeitOVXRKa2xKSys5OC8xQjQKEYYiRUpIRPryTY7R8w6EODjIFYiS7+Yt
        /xhnip4MvmOuerCORoCkzgf6NK44Af79ncrp//1y9X6Q4Yv7CwhMyQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tdgfvwl4qdptyvgxju3rwz9uh45hz422txzcgsrwm4f4f96x558skzxklr
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTR0tzaTF5SjYySmNqQjg2
        M0dNMUg4N2ltV1lkNjdhMjNBUklWVWVzOFE0CjdOMTVTK2VqQ09BamNHZmhBdnhp
        Z01sZk5SWlBaN29NYktKcUU2bFZ0QzgKLS0tIEpzaDl3SSsrdzNpQVRxN1ZadEFm
        a1pmc2JtV0JKQlZEMWtldm05K0tmOWcKB1W17ocaulRkIkJgvq0cIwybOfyKVIu4
        V2ttPHonxUnaCK2XgxpfkPfBub4+r7WZHCWHQEOiCOhtoWY4YT9bqg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVml0Z3dGakpFUVBDZnNn
        N09sTFJ0REZ3ZnRhbS9aVWFTbDlXNUdqVXpVCnZmc3NPUUM5ZWJiaHg5cTVuMVBE
        Y0lIMTJGVTJudHBjbjFmS0xvZStuZ2cKLS0tIFN2Q2g5Tzk0MnBCKzZ1aThSdW9r
        NVNsRU0wYjVDaUlUQjZFWEo0QzBhNTQKIxkXXwnkHDgWeqrsXz4LqjDAUXend4rN
        IPe07GaEmOqEATR5zkHOftXtSCJy+WpuiSwe6WEY1y7szM156NlUqA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWDFTVWpvbU5oR2JrZTNZ
        NWtKVitxL3BmUlJwUFJwUWdWTHRmekw1TFZNCkRMcGFwVExRTGJjSk5zQUhYUENs
        WTZtek03OXZ5ZkJKcnYrcWlzVXhYQ00KLS0tIHBJWEoxWnhsZUtHUEZqWHF6aG1Z
        S2V0b0VOZEV5Q3gwc215UE5HNDR2Y1kKhe/mwprssPIYWyENWV/LhufSCfbSXS4/
        Ca3mQib7Z/Ds5YUKu+HazwrJ0RskrA5FEcmddn3RumAk6m7zNksjZw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOCtiNUp4Qm4rVXYrcmJK
        VG1KVTNpVHNwL3BNei9ucjlFMEQwbjhuWEJBCnNlK0NjL0JTOFVKZmpOeDZpcVZS
        cnM5RXFoRER2NjBON0VKeVNJYjBwZGcKLS0tIC9DakRMOXNYdGtCaVNobVVNM0Z0
        UDNva24wM1JEUi8zU0FBYU1lVXFIaDQKeH868eZZBp5K9jEddEIzs80qjg2hU3RZ
        Pw3+cTxV+KSMK1RZHaN9KYo+mtnx/frsGGIVX/AFB5EtpaOFDKIewQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByU0VDdmxZeHc3VForcVhm
        STRZRy9LNUpDM3g0YlZ1U3AzVEhubjNpM1FrCk5hYndJMExiUmNxTVJwd1N2SzVT
        dksvZ1hKc0ZVbEYvYmprbnRaT05OTXMKLS0tIEUyM3VRR2FOWk9rQWNkbStGRGRM
        UWZOMFVZdkFucHh3KzI5L1czL2kyUVkKCAd+2O1BhPrV+73KL3koTunPJP/7L2hq
        CBEp9rswLX3DGwcpvKHatXJe3+v16zEY5IQeWsuTFm6LZlLzzsothQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOEVTOTh6alAyUm9yR1Rh
        Y0ViUzRVNndiaS9jYXpOK2FRZFZGcFdaNmcwCnIzL2tWQ3cwdlMzU1UxNmdTU1Zn
        ZUdZMk5YNHhUS3NtRGo0cUpjcGlDa3MKLS0tIFhTaXVWVGozNXdRb2RFcnNpV3NY
        QUxMbzBwQkJHc1E3aU1icVZpTmRyNGsKO6X9GXm1EVfOs9WrvdUqv/tn5XD4c3IP
        gzdBwxIQXwmEUwmfvl5DUtUfgFSEwUeqKFSpINQcSomKNppjI4z82g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXN3FrS1BrUEo2OG1oRi9O
        cWxPL21PMFVZOU5vSTJjSE1VOUkveUE5TWkwCjdNVXZxdytEaUY0cndaM2hOQ2hD
        WFdtQmJBUHAxYnFKbTJ0VkhRRnJVaUEKLS0tIEhlSXFBR2FrZGZWeU5uK1lRT3Z3
        STJjVEwvN3B2SDBBai9PZFZWLzZEbDgKr94XnRymc5n5cHaMTjlcZVX0/pOPQS0U
        q3AZSRxoDNNyg+qSmQvFDnlvw2BEmNxy3eGY7/xMfAPiJGTOB2apCA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1l5t62uzsj05pzftv9wg6s346csxyq202vxmmyyx8gwy8zu2nrfrs7v2a4z
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYanRKUXdzZXY5UkgrOEVt
        S3IvNElxZXdqRVFENnhUS1dvUVRrQ3NwaG5nClQ1RWMzK1ZBR0g2d0xVOUhwVjIz
        bUJETG8zS1cxdXUxU2VJZEFrc2Y3L3MKLS0tIFpST09aSXlBajBTZ0paRjM0UEx5
        Z0V4VDdzaUZHeEl0bDZCRWk0L3NUUEEKM+3tDuE0jj5r2QT0g+i9+bzx9L25gaR3
        nsYiWeAfqT822FEkcTItFvEK1tx5HPr+aXoS/R8q7rP1ptGbisKteA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-19T02:48:15Z"
  mac: ENC[AES256_GCM,data:HGwYEo/IbY+npVnXZg590aN32B6NM/p7B6rgz/rSkTb3QvQzBTeyRkaimFCEWRMmlFWKiW1iSmkI5Ui0jf+EeC4MWCl36NHhzJE+P/M1LgbkAuWKji0MZtCKYQzUY6ZztAfYl9YQRkMv43RlxIoI8XxHu3PLZ330qgtt53T13Ws=,iv:KYJu66Uk42VBRIBGi4iI2YYlbRIT8FzWABvtVAN780k=,tag:QEi3gqh5iubzJAihh5yO8g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
