apiVersion: ENC[AES256_GCM,data:cqI=,iv:CRbQtPD5aOPoO6ejVoBQTT1RAm5Ama9UdLTqK4fwTAE=,tag:EqojrIM90cjFDhQe7O4tZQ==,type:str]
kind: ENC[AES256_GCM,data:ZN4DeQFj,iv:K3afZ6/C8A8r4sqk0/l6Dq2by1t9ghtJIZnr/nBBFfA=,tag:iwnMTsrVyn5TVj1j4L7q/Q==,type:str]
metadata:
  name: ENC[AES256_GCM,data:ssfhoEYAcxepkaNridJn0Ylx,iv:rRi65voLqZ4b1pkngf1X4NVYFZbLd7b13Qv8IWrYxcE=,tag:lFzTSnWnmOt6o76XbKkDog==,type:str]
  namespace: ENC[AES256_GCM,data:W4IxxItxAdV8nZo=,iv:CAcY/k2L2mMdvn9i3zt1nh2z26Hknc0d8av9DLZ6OLA=,tag:sjnBqPo5SYcj8A2GGOSxgA==,type:str]
type: ENC[AES256_GCM,data:1vaX9JzxkfZ+IAZ6cvmxNnLZGmgB6WRE,iv:Hgx9JKbSanBfqVQlLebU3NBRhatF7vzAfmlCnwMxX/E=,tag:ezcJAl4HF/HkMXyscuSmqg==,type:str]
stringData:
  username: ENC[AES256_GCM,data:kIO61cu/YUYu,iv:2YJA0B5k+Qwrh67ZJVBMbZBSIpuqMgK9qZV8LeijO+Q=,tag:54g5hS9AD79J9yn9192+yw==,type:str]
  password: ENC[AES256_GCM,data:xJUXI1fcVuAJMcBiJMCxjz7tXWBIQNl/j1WGF5pQF9y6+p+fjnTr9uA0rD7rjAjl7GxOJRrNBAiLMxvA/iGrzQ==,iv:kwvs1RoSvEkv/mUoVhT/OTjiLPa0IswzC+to3cannZ0=,tag:TvvXSXg+A8WVVpo5ok0wPw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVamYxUTlTR3dzRDFEMzhW
        bWlPU09zR3BjalpiMjh6ZDlvaXZ3cHRvNmx3CitwM2l0MFVsQ3FVWVZJRkl4dW9X
        WVBHc1FybEJJZndUazFBY0xSd3UzRzQKLS0tIGVpNEJHYUZJQVRDZTE4YnMwMWVw
        THFSWDRYV1p2akd3NEI5M3lubU9zWjgKER2LNOol9hQAy/31tnT5iaM7P+7NyP6F
        FwjiA0NWRflvvoFrE4ZXBRkbqMSjj+3R/s+7sLPdQEUPiC76viK5BA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TFJyZ3FsdkpvSm9Sb05O
        bkY0akp1U0FNaXU0Rm1TdDY0YlM4aUhWMmtVCjY3T0hXeDhXNkFkcmY5RkFncjdI
        UkdNZWp4RnlPNC9ZOW1HRlh4YVRUOFkKLS0tIDhtdklNOHNkL2JqZStFYkVCWjNl
        c0dZbnMwNHd0bHQydStxRXhzYmd4TXMKyO5IUZagqswB681YfB5viGyaFxOf5VfH
        Jxa8uZGs4vNHQTEMAGxZAxkL84KccCZ/a7A6ty9W9Er1MtA3oMXoBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dDZIUGEvOXloUk1yK0lw
        QWNsL1lGcENlU0dhMlZXa0dlbjNnOXAvVGhjCjhtQmZJOExlVmNhUDljMnFUcFU3
        WTdETlZ3cWdxaWVLc29ySFhzY2gzZjQKLS0tIEtpNUxzcDkrWE55U20zZFh4SWVY
        cG5oWVJVdGNVNFhHOXB3YzNLaE1SUXMKMzVIenjtJ2peJNhFrFPVWAmZHGEsEdg2
        ft5EG8IiNYjQCmw05JR5Pdl+UBpp+JpmwCE7e9ihhE0AObVMBI0arw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXWFlDSkNyVmlpaGFraW85
        Z2hnZjRaNkNBcTZsVkxVVGNtQlNMUzZTYkFnCnZXWnpKOEJneGY3TDNMMEtZUUlH
        UldhN2JqRnlvOWtNakRzYU5tbDZOM2cKLS0tIDZZaVd5MmtFWDJPYlNUNkd0MHBK
        c21tUktmVGVVRjBXZzhYeW5WUFB1V3cKTt6ztZ0AjuT+vf7dl4v+Jdvf/69Y25Fa
        Tkdiui+YUg7Ko1gWsPAZqMDhS3sz2DOV52wS70TzQsNnq8rtH0NTOA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMlphNWlwVzVyLzExKzM2
        dXJMVmZQWlNWOEdzQStYNnA0cFFDYjVFZVFjCjZUcGNsMDB0bjhMQ01RZTFXcFpB
        SkdtUlRoR3J1cWtJZThlc2FtZ2VZT3MKLS0tIExsU1crbHhLeVUrM0xlUDVDN2wv
        NXpyZlVXWVRnN0ZVdzBIY0F3d085YU0KsOC+AWdHkeH8FRcB5CESsl+5yEgOb/bK
        H3AGc2xgCe2xxF1s/iwM4FDexV6/gKDUzXM6Sjb0BoNAqCmfOxMx0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAweGxzN2hmU3VSaXBoR3dj
        RjJwajRvQjJja2liM2dOb1ZjcW1ZcDM0Wm13CnlHRk0rc3ZKNVNabG81QU40UlNK
        dHRPQWFIVzJOamR2d0FvdXVNRU82bGcKLS0tIFJOYWhwTVBiUklIeXRnazVjcXFW
        aXhPYWFlYkMzNkdIbmlmQ29lOGhOYU0KW2/BOb4W+Fko/LzF/mOa5LKKMu/iLkca
        UuG5Vx5jvIbku3Ll1rsSjZvlv7JO5pChWM2yGl2tXPYabbBwexo9Ng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZG85SFFTN0c0aFZXK1dQ
        d04yVnUyUHRnT1lpSU52eFpkTnQ3MEQ1V1NFCmpxYkZlTDdJVUxaYkFYMTJjdWUx
        TVhzejdESlhCYmZhQ2VTU3BhUzBxVzAKLS0tIGdBWHk2WE5GcTlHOTNUYzlnTWpY
        RHdLbm1kWmUwalAzV0Qxai9RK1doWUkKYKsU1sYh5b4duxC4OL06mexJpMHTnrQ+
        faEGkJQV9/qIWRmGar3vzGhY8EOQY40PR8Rdld785vxnYsWeD6OPAg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOERPY1dtWmZTcjBKWThB
        Rjd2bGsvQ2t1Qy83Ty95bUhCdWNSV0FNWlVBCnJmV0RINGxQZ2xJUmlyazlPQmZH
        dzhKOHRYZEZPOFZ2VFNKclBWZ1k2UXMKLS0tIFFUZEU1blU5eG1JWVJ5SDRRVEJv
        MmVJaklFYTZObjV6L085YTdoS2RrUEkKf544wmIEZjM5Dpt3Zi+RSjyOw761DaE/
        9NRQGKDExjMNiQ15UdqGXYiaNxMQ6HUJCkSDdOFqdyAfQEKK84Af4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-08-19T02:48:15Z"
  mac: ENC[AES256_GCM,data:HGwYEo/IbY+npVnXZg590aN32B6NM/p7B6rgz/rSkTb3QvQzBTeyRkaimFCEWRMmlFWKiW1iSmkI5Ui0jf+EeC4MWCl36NHhzJE+P/M1LgbkAuWKji0MZtCKYQzUY6ZztAfYl9YQRkMv43RlxIoI8XxHu3PLZ330qgtt53T13Ws=,iv:KYJu66Uk42VBRIBGi4iI2YYlbRIT8FzWABvtVAN780k=,tag:QEi3gqh5iubzJAihh5yO8g==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
