apiVersion: ENC[AES256_GCM,data:Lks=,iv:6+/VnEROiBS9jvenyUqHwMDxHc+9XN4KCXDfbuZo0Bg=,tag:Qk7Qvcl7E6m13bsZxYp4Aw==,type:str]
kind: ENC[AES256_GCM,data:4GZgrNvc,iv:IZAyy7t8mI4EbaEAxuEUHcQc0XSLpoq71XgbvEN2npw=,tag:b4oFiq9ygtgNLKPU9f83Iw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:x/ubnYgBdJYOvqg=,iv:FmhvW3Ar++YiWtTPz//GQqaYolC7jwCDVEbr4VNrJhw=,tag:PyiEyWA6szdyfriOJXUvPA==,type:str]
  namespace: ENC[AES256_GCM,data:/Z2CTt/rEQ==,iv:c0AFpHBzRvNUfF4tf2FjwEHBDT7ddsSlw7YYX7CptEY=,tag:W4Kli/A7IsChdOYFYNnYMQ==,type:str]
type: ENC[AES256_GCM,data:vX4uC8E6,iv:SPko0uFOVrrhG/Iz6/EeL2y/RA0kZUli23XsgThHhqA=,tag:JeAnojyG6uBSUjfuOJTUew==,type:str]
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:4oLhFpEtdUOfgtYRCDLlbfWPhnanjaAlqQ+hIIvcPW8Bgq3M10keFAKIrqBPTIUMoffNLuqTTLwfM3xkZOPUMQ==,iv:UeTWC6YAzg0GJr9GGjiz5gM4iE6ZDg4ncV4o4rEuvAI=,tag:f1l+AUjK5Dsvy3CyXB37FQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWM1ZwT014UXVOV2FjMVAz
        R0J0Y3E2MG5EYmk0SElUQy92MGI3dDRldkVZClN1STVmaDhKdXFZVmU4VTF2QzdH
        ZXM3WllEcVVlUnc1aUFqemloNksvc00KLS0tIGUvRGhHSnp2UjVaRDRmUjloalY5
        dElMRjJHMURXM3dqQVJOZk5DZERCVmcKnMBFT4iQAT0YoOF8IBTRhkUn/oQK7zjf
        1Km8us0AL9tMphv54liOElW7nBnJJu7mDRCPCfTSXZZRvN4EG6/rcQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOV3dIWW0vanN6RWx6cmJ5
        d0JFdzhtMSt2OTVOMEovenBjalBKLzBxSWpZCmdPcDd5bUdWMG5scG9IekRHdHRI
        VVFYSFdtZUd3dFpZS0VFTUg2R1U4ZFEKLS0tIGdkWEdTWTQ5Z2RYOCs2Q1JvRXhH
        OW9jdDJLcW8yVzhyZTd4ZHFVdjJNaHMKxJqQp7xQV7x3Y+jWn1IjzawwIZXc1/N6
        5y4BAzJs1cgqilEMr4jNHH6oN3dO2E5my2sLegow9jRxnamzMudUpg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVDk3dTRPREd5SEdsbE5D
        VTBCcStNbkRRYWdkNWZBRVc4VE1yWk11d2pnCmdyM2RHdUMxMmpYdjlGSjgyUUpq
        U2NDNTZWYzhJaWZlSVJQNTQwWUwyMEUKLS0tIEZkVHd2OGhEcTh6Mmo1eHhMTG9N
        bzh1NnV2UEZFakYvMUozRG9HVStLdWMKoc6wfc2HzXM5QbqzHiy5PG50ihRPYX5E
        IvckFL6THGsBHJiw0vNoVoQ1Y2TBXaOjsZTa1t+v7kOy5wqgW9BC1w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tdgfvwl4qdptyvgxju3rwz9uh45hz422txzcgsrwm4f4f96x558skzxklr
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFakRkc3ZicU1kK2U4Nzl4
        WGRLYmk1S2I2SDU0Y3JaYzc3ZkdaUkxPTjFzCkpUUGVNTXE1bHQzZHZmQllKbzVK
        a1VMUDJnQ2ZwR25tdGYyVDNUMlQ5dFEKLS0tIDB4T0dCWHhGalNGWmFLazZoT2pQ
        SjIzUzMrSVlNbWM3N2t5ZE1WMWFaV0UKInQsyYzBTFBtZ/m/hbgfaSODLFWu84C1
        qUy26diFug57H29U1eLcfUEVwBEjoGZFfQq4TJryUQn7YJRARhlGWA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeUJmcE5yODhvakVMU1N4
        cmxnU3pRNVo2V2dmRXNjN25oVnMzT05kODFzCjdncjJJanRIcHQwT0NLZXg2UHRP
        NUJaZGkrVCsxSU54emYrNkM2Y3hIcXMKLS0tIEFsT0tSTkRveHA0czU4Vm0wV1Ra
        SUdmOGJBbTRrWmhJaXFkQktSMXpZUUkKBIgEQa3sA9F8ml8myzraujftAuU02J0H
        k6vXZoVQFL0ksiYTzDdcMc+j9efclLUArbG6zEhvJk1vIgGvaMlBJQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZHVzbmpLUWxWMHpjN1Ry
        TnBpbE1oMkJpWGZmSFVTdXFXYVFBbHZTNFY4Ckdza2NOYzVkeVA2MXljUXJyaWt5
        a2FyYUFadTZNN3IvN0dGSnVRdVJtM1kKLS0tIFRLZEwzL05yM3lyYnZCV0t0M0ZK
        ZWdoVm5sNVVVS3I5alViaCt5Q09YcmMKTpjBqh+CJAIWWlwSj1uG+0vlzX4vhZnA
        TqUmZfZAfDjUR5xoMViQW+X+Co3uAevOgRfe1cc7bjAOa1PeHMSX9Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNEpaOFNlbmFTYUVvNXRF
        elZ5WUtVS0d2dFJ6NHFWdEdRRHVGTDFjWjJzCndRNU11NTJvSjNGVmpNUUY4SWUy
        MlZ6SGxkcnNOcWxvZzlINzNOTWdmM0UKLS0tIDVaUUZaT2Jha2lPRU43N2F3U1FU
        UVZxWExaZnprWEhPSGhpMVJydC9TUWMK9KdUxxo+AbH2IwLtgrXY8i3OQNzObZAC
        u3d/ezxdsbBPufJvw3Vf9Q391/PsYO6dkUw5UIoE/DtpS1u+YBauaw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aHBPREFxcjBtUG15cEJG
        anIyUGQ4K2pOOG5VejBZMndKU0lBRUQ2Y0ZZCnZGTFA2VUZPZG96R25UZ0VGUDNM
        R3Rrc3B4MGcrTlB0ZFA3dXIvOWJUSGMKLS0tIEhuMXU5d2lEMXh6QkRhV1FtUWZn
        TzFWQlA5ejhDL2R5L1dvRmxqMXpJQmsKX/YxBo8F7dly6mgHcamkzuCqiiRKb2Fa
        UCLU3V9VSzrdPgaI7MrNGc9opi7Mu+XS9+IH2QOiuyzSkucl52TQOQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcVI2dkxBU2JESjVGN3BL
        K1ZLTTIySkVyWExHTDErcEZzOGh3VUJHdkZZCmEwRzB6dGIzRkUxWTczLzZEdHB0
        NFE0ZjFMOUV1ZTF1MlMrZVRxY29KUUkKLS0tIEpUUk5hb1VPRWV0SitLQTNGdjlV
        Z2pVWGN1OTgvQlZzWW81ck41TVFWeEEKeOVcLZyHQdMuP+hp6C1em8yePteKaxon
        VtbzG3eoWI9jCKIhRGLVSvxDorr77nqydMmQyIRMbmnA/JAE2wtUoA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTL0NocFJQR0NubUFlUVp2
        NWUxTzg2SEh4ejIyZXJIMVpmalNhOTNCSGtrCmRPNlJNTGZNVk14ZHB4ZUVCVmtF
        MStvd0NBaThZdy9jeUNPSWc3M0pRTzAKLS0tIGcvOEppN0JGdDlHeEJmRHo2SllE
        Z3RKdzREUlYzMWFrUmFmdXppMjdKUU0KYWHMP9GCmiUczP/yB8DszN+xZVfp7XJI
        cDL1kwOrzFh1LLQSIYix9vg3+B9gbtoqNEDTj2DG0ba1E+zVVKjUzQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1l5t62uzsj05pzftv9wg6s346csxyq202vxmmyyx8gwy8zu2nrfrs7v2a4z
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwV1h6ZGpYSkdVWFZWVFZy
        T0FtWlNBVk5tR3lQUS9VNzQxS2xmL1hYeUdjCkFBSCs0NjJNVDdJMlJEejhVLy9T
        dVNEZU9FaUgzT1NwV0ZET1p6S25tNkkKLS0tIDltL0lOcHVUZDBuMW51cjdWTWdV
        WVkvY0tzNCt1OFp3TjJ1bGtPZXpMRlkKV1r91iZTahlrG7wZv1ogH63aa32R3EWm
        vH2xwGhbgbDyfZyQM07gCAX7U3pq8IQJ4Irx4w/mzmhj3pzgeHCANQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-09-28T15:44:37Z"
  mac: ENC[AES256_GCM,data:icVxgqnaqvS0StaZTsoof1PlOjUUiLuB6S0FalegtiXodF3ASLmdbHIHXGxpXUJ5J8rUuF0FNVWWwvQyLZUONTRrDwsXN2f4UQzI/DHJb1foZv/2SjNoMtvEHvoTY1coF83DUIoqsjPMczQW8Frf7pBPdG04Q2fDm+pUcj+oDMI=,iv:8NDReLDPv9GqpQtTFcGizHnpBg/xC27hzxeU8+WdJiE=,tag:Ilhdxlwndcq5o0AlIUaxLg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
