apiVersion: ENC[AES256_GCM,data:Lks=,iv:6+/VnEROiBS9jvenyUqHwMDxHc+9XN4KCXDfbuZo0Bg=,tag:Qk7Qvcl7E6m13bsZxYp4Aw==,type:str]
kind: ENC[AES256_GCM,data:4GZgrNvc,iv:IZAyy7t8mI4EbaEAxuEUHcQc0XSLpoq71XgbvEN2npw=,tag:b4oFiq9ygtgNLKPU9f83Iw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:x/ubnYgBdJYOvqg=,iv:FmhvW3Ar++YiWtTPz//GQqaYolC7jwCDVEbr4VNrJhw=,tag:PyiEyWA6szdyfriOJXUvPA==,type:str]
  namespace: ENC[AES256_GCM,data:/Z2CTt/rEQ==,iv:c0AFpHBzRvNUfF4tf2FjwEHBDT7ddsSlw7YYX7CptEY=,tag:W4Kli/A7IsChdOYFYNnYMQ==,type:str]
type: ENC[AES256_GCM,data:vX4uC8E6,iv:SPko0uFOVrrhG/Iz6/EeL2y/RA0kZUli23XsgThHhqA=,tag:JeAnojyG6uBSUjfuOJTUew==,type:str]
stringData:
  SEARXNG_SECRET: ENC[AES256_GCM,data:4oLhFpEtdUOfgtYRCDLlbfWPhnanjaAlqQ+hIIvcPW8Bgq3M10keFAKIrqBPTIUMoffNLuqTTLwfM3xkZOPUMQ==,iv:UeTWC6YAzg0GJr9GGjiz5gM4iE6ZDg4ncV4o4rEuvAI=,tag:f1l+AUjK5Dsvy3CyXB37FQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YWR3WVYxTzkyRDBTaG5h
        T3JWaXVyS3RCOFdLZXdxVFV2U1NURE44U3hrCk1WSHpvcTM4eGs3Z05RMzFwbko2
        SlpuTnFkdWJ1Rm1KSy96Sm9MODNEVk0KLS0tIEF4RVNMN0xZZGdlaXlzbkk1RDdj
        MmN4OXJqN0I2VDlyT0hQQUV0V3VFRDgKIpHGZ/HGwX6PA+Zf+wxHn81HSYHP5SfK
        ugsUkM4frcBmAXjw/UQ6nkdZjx8AUqNtM9mr1qU99EUjE9UWsyBeVw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTWZ0N21oVlRNYnRSUW04
        NFc0bzljRUZ3aWszM0Y4aXZQVERjcmtZTTNRCmh6ZDI0UTRDV1hGRmtTVFZEQnBt
        ZTd3R0ZTaklOYnNUcTF1Lzc3cUViVEEKLS0tIHMrVTNqV0d5MkkvakJONnNob0JS
        c3oyZUJsMGg2RFhpZm1McnhSUWZQWVEKfc4stN4gZpEt9CA5PgLAn75KPT20PGr3
        PHd6Yj/iw99xsINOMbURWCIY8lFTonCEqiq7hWDuMZt+DNgyICHZXQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZ0VYWmRsS3lzelVMcUY0
        QUR1UVVwdkVRMk9nTFlxckVaZzM0cDNIeHdnCk1zWHhaRHBRUlVUaXlzQTZBTVJJ
        dGw0MXg4YWduS3IyUGMxMFR6VURENkUKLS0tIGNheXoyenRkSjAyM3BNaThNR2JM
        YXlab0YwZEY3NW1lWU5FVFBLVjAyMWcKeHkwVM4/+Nk223+rItZhK3qvq4g2EWqQ
        fWvrDTAuxO4A30PbwEZdccDHXztvEzLWsL/amXdyqFzRYnZ8dQb5VA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoR0x4U05yZER2eEZ4Zi9U
        RENuZ1ZaeDFHQktyNDBvMWdqU3V5ZUsrVDE4ClNpbnhMa0dFQjhWc20zbjNNamdK
        Wjh0akwvZ0dIeGcxZkNsZGJMSzhsREUKLS0tIHZ0eDVtQVZoN2lXWjV6aDJNeDFM
        QnZvWkRjYU9NM2F0bkIvbUpOYm9GOHcKHywrlAbGJQkIFKQy9PkkyMuR0/mBJRV+
        w+GPI5wMejuTxSNcQqbl8LxM1sVUy5c0rwEUNdCRxOD+BC8rAghrUg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOXdmWW1IZFFnV0lRNmEx
        Y3I0SEk1MmNBRDZTRlFzWFRhOUNNak1rZFVJCktzYXluV3R0L1FZRXB4WUNuUmwy
        ZUcrdXhxK1pVYXUrQjVkbDdybk5WNzQKLS0tIFdUbEEyaGFiYVNpRHhmaWx1WUFS
        UGV5UXNTNlBRL25IZWcvOFpzN3o5cmcKK3LmHCtYQBMemMwpb791nOGKFxoWQmrR
        /aR0hVB+WTYLTfHsSxFGjr7wQ3H2eYLA32J0mUGwGxhplo8NtKUiBA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGL1hET28vTVJ0RXg1U2tx
        OEVGTW9jZEh0NS9ObW00dzN0Nk41M0FhbUNRClIyTzg3dXA5L1FqT3VJc01IRzNI
        YUVReS8rSmxIZnBNWEdZQXFQUU84ejAKLS0tIDk2emVxcE9vc0FBaXpZcWxxeDdI
        QTlLSURSbHpoOFZsV1BySHhRbVpZRFkKl4qTyrVub51lIqy/8GPLtIK//7RVyppx
        +WeGF9EKpyBzpJHjWczTvt5FlbXwkeHws1pvCGg0uZVlhzyUQbglRQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UzdZK0QrNEJoT1ZzWDhD
        U0JNcFJLZGZkdHgvT2t1N0g1eVhKZGRIQkF3CjdxcXB4UUhZdk0wckhOQmJ4dENk
        N1RtVTFsY09LMy9mTzd6L2FTSHFBTFEKLS0tIDRPeHRhcWRmL0hwR3lXM2o4NFI5
        VFQ2dDZVU0hIVWVRdWlDWUdKbnRNbEEK77jBPbNGZSgOQRbhTJ1zqC9aNKhvAYcB
        jj/iX0xbyKwAFeYINHYb3wobZ/oNJ9QwQP+Cht5+Ow8gcJvfUvpflQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYXJhYy94b2tJaVZtUnNi
        bXo3eHR3cWRoeURBZTJuWFNmWk1vdUkxY0NVCmJVd3c5NFlqTWVOb3lYNUM2Q3RS
        RFl0QnloYTIwV2sxRld5dzFEeVdQdGMKLS0tIFY1SXVELzlEbXRYUUZod2tBN2hI
        TkorcFN4Q1pFamV1aGFxR3BEdTRRdzgKV/MfyVxRvL6IcYIIf6bAcWhfIG+6jAfE
        dzHpatHrYcHRYmw0+6Cm1shjsEexkWNrDuKmGSL0CXETDF2ido/HNA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacGUxTGtMbW4xbnJuOVNo
        WWZNM1pkNkE2Rkxtdk4ycm9BR2p2MlJVbDE4CnJhTnZRbkxmZUpSM2UwRnlJVE1F
        ejFrbDVKQ3RiYmxRdU1GMFRUV3BCdFEKLS0tIEVQRytmbHlHK0ZnMG81NituRjJm
        eEE2bCt4dmxjTGRhVWkwbk54eGNUQ2cKjjEdTDZL/7d038xkqo8XDoPFvzGfBBZP
        Ksh6R6FZqcYO4S/xiwSP0JHCvTKhUMUDHVnBHqweNHfXd5297yLBpA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
  lastmodified: "2026-09-28T15:44:37Z"
  mac: ENC[AES256_GCM,data:icVxgqnaqvS0StaZTsoof1PlOjUUiLuB6S0FalegtiXodF3ASLmdbHIHXGxpXUJ5J8rUuF0FNVWWwvQyLZUONTRrDwsXN2f4UQzI/DHJb1foZv/2SjNoMtvEHvoTY1coF83DUIoqsjPMczQW8Frf7pBPdG04Q2fDm+pUcj+oDMI=,iv:8NDReLDPv9GqpQtTFcGizHnpBg/xC27hzxeU8+WdJiE=,tag:Ilhdxlwndcq5o0AlIUaxLg==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
