apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Ti
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /mnt/Media
    server: 10.254.2.3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: media-nfs
  volumeName: media-library
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Ti
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /mnt/Data
    server: 10.254.2.3
  persistentVolumeReclaimPolicy: Retain
  storageClassName: media-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-data
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: media-nfs
  volumeName: media-data
