apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-kuma
  namespace: default
spec:
  dnsNames:
    - kuma.cute.haus
    - status.cute.haus
    - status.aly.social
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: uptime-kuma-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  namespace: default
spec:
  ingressClassName: traefik
  rules:
    - host: kuma.cute.haus
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  name: http
    - host: status.cute.haus
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  name: http
    - host: status.aly.social
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  name: http
  tls:
    - hosts:
        - kuma.cute.haus
        - status.cute.haus
        - status.aly.social
      secretName: uptime-kuma-tls
