apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: morsels
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.certificate.clusterIssuer }}
  dnsNames:
    {{- range .Values.hosts }}
    - {{ . | quote }}
    {{- end }}
