apiVersion: apps/v1
kind: Deployment
metadata:
  name: morsels
  labels:
    app: morsels
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: morsels
  template:
    metadata:
      labels:
        app: morsels
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      containers:
        - name: morsels
          image: {{ .Values.image | quote }}
          ports:
            - name: http
              containerPort: 8000
          resources: {{ .Values.resources | toYaml | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
          startupProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
      volumes:
        - name: data
          emptyDir: {}
