apiVersion: apps/v1
kind: Deployment
metadata:
  name: switchyard
  labels:
    app: switchyard
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: switchyard
  template:
    metadata:
      labels:
        app: switchyard
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: switchyard
      containers:
        - name: switchyard
          image: {{ .Values.image | quote }}
          ports:
            - name: http
              containerPort: 80
          resources: {{ .Values.resources | toYaml | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
