apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alby-johto
  namespace: alby
  annotations:
    tailscale.com/proxy-group: private-ingress
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - alby
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: albyhub
                port:
                  name: http
