apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pinepods-johto
  namespace: pinepods
  annotations:
    tailscale.com/proxy-group: private-ingress
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - pinepods
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pinepods
                port:
                  name: http
