title = "watsup"

[[sections]]
type = "widgets"
columns = 4

[[sections.widgets]]
type = "weather"

[[sections.widgets]]
type = "search"
span = 3

[[sections]]
type = "widgets"
columns = 2

[[sections.widgets]]
type = "lobsters"
title = "Lobsters"

[[sections.widgets]]
type = "hacker-news"
title = "Hacker News"

[[sections]]
type = "services"
title = "Johto"
columns = 4

[[sections.services]]
name = "Immich"
url = "https://immich.cute.haus"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png"

[[sections.services]]
name = "Nextcloud"
url = "https://nextcloud.cute.haus"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/nextcloud.png"

[[sections.services]]
name = "Paperless"
url = "https://paperless.cute.haus"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/paperless-ngx.png"

[[sections.services]]
name = "Plex"
url = "https://plex.cute.haus"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/plex.png"

[[sections.services]]
name = "Uptime Kuma"
url = "https://kuma.cute.haus"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/uptime-kuma.png"

[[sections.services]]
name = "Navidrome"
url = "https://navidrome.narwhal-snapper.ts.net"
healthUrl = "http://navidrome.arr.svc.cluster.local/"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/navidrome.png"

[[sections.services]]
name = "Prowlarr"
url = "https://prowlarr.narwhal-snapper.ts.net"
healthUrl = "http://prowlarr.arr.svc.cluster.local:9696/"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/prowlarr.png"

[[sections.services]]
name = "Radarr"
url = "https://radarr.narwhal-snapper.ts.net"
healthUrl = "http://radarr.arr.svc.cluster.local:7878/"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/radarr.png"

[[sections.services]]
name = "Sonarr"
url = "https://sonarr.narwhal-snapper.ts.net"
healthUrl = "http://sonarr.arr.svc.cluster.local:8989/"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/sonarr.png"

[[sections.services]]
name = "Lidarr"
url = "https://lidarr.narwhal-snapper.ts.net"
healthUrl = "http://lidarr.arr.svc.cluster.local:8686/"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/lidarr.png"

[[sections.services]]
name = "Bazarr"
url = "https://bazarr.narwhal-snapper.ts.net"
healthUrl = "http://bazarr.arr.svc.cluster.local:6767/"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/bazarr.png"

[[sections.services]]
name = "Tautulli"
url = "https://tautulli.narwhal-snapper.ts.net"
healthUrl = "http://tautulli.plex.svc.cluster.local:8181/"
icon = "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/tautulli.png"
