apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  tailscale.server: |
    narwhal-snapper.ts.net:53 {
      forward . 100.100.100.100
      cache 30
    }
