apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: private-ingress
spec:
  staticEndpoints:
    nodePort:
      ports:
        - port: 31667
          endPort: 31680
      selector:
        johto.narwhal-snapper-ts.net/private-ingress: "true"
  statefulSet:
    pod:
      nodeSelector:
        johto.narwhal-snapper-ts.net/private-ingress: "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  tailscale.com/parent-resource: private-ingress
              topologyKey: kubernetes.io/hostname
      tailscaleContainer:
        env:
          - name: TS_EXPERIMENTAL_SERVICE_AUTO_ADVERTISEMENT
            value: "true"
      tolerations:
        - effect: NoSchedule
          key: johto.narwhal-snapper-ts.net/workload
          operator: Equal
          value: ingress
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: private-ingress
spec:
  proxyClass: private-ingress
  replicas: 2
  type: ingress
