apiVersion: ENC[AES256_GCM,data:Fug=,iv:DGlBdCFb0oNdD5gOeY/2ysxoGUEWAfvWDW74rwK4pFY=,tag:nC8fT8Rn0l9mPkKgJxRPuw==,type:str]
kind: ENC[AES256_GCM,data:RxVqs2QV,iv:njgwtgwMtTvUt19TQ2vk0CyNX3aH13IzMm4PRJ8AELk=,tag:NZyOcrqFNLo3c1UAM/XuVg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iuIDQmoUMvo3yTuCjoVEXDRD7dq25LjGTiT6,iv:kxazCfjpAnf444I3FH3xPyC7yTcinDpXMjqjOz5c0T8=,tag:O8hfL3jCYJ7xX5bgF91wsw==,type:str]
    namespace: ENC[AES256_GCM,data:YvD8Jg==,iv:GcTFfOtoXaMJln2IxdeBMk5uUQOBF/eOPqJDD1LlQKY=,tag:fhu1xHU8T+ZolWHRlQuzBw==,type:str]
type: ENC[AES256_GCM,data:SZCHSJvl,iv:Zj2ddbVmY9BdE1P3VdFrbVHVeFO4nuVTtS5swl7AuQ8=,tag:bMbbjF/q23cKCJvxj3YMCw==,type:str]
stringData:
    database.json: ENC[AES256_GCM,data:ZMdmRzf3YC6xG/mJcPRgOcY3AHvvYiuYGJQmqDTFKTJsHInB1rMprxc9vxE9dLzaiXkzSFo4vRaYRkzeC8MsEYLxAilQpnDZpsQ9gD9TsasrUu7GNGijoFFkRqLBfszfyNpVWznrrpZEC8p+8ui6s1xaaNPJyeWOXX99VEG1nkAuHIO2m/vKoCzcDrd5MVEei/Xmv85FrOJjtjaEFANYbl+4OiZfLMvKUvVvDYQjFsTTC2FuwQ9dCx3fwpe0X7CdBAT7URtU6x6m+/OSiIEzFDN827L9FjL0b+cHshk1xw7ChOFKbb/7IdOGOlBCex1PNa6pdEiVxvyectQDI403GMNWmxjpVZSByDJiAvntIHDNSteSZoUbYQxKyQb4UVaQm0AxdCiDKl+B8EDbPsBXtvQiDV207RScPdJx3+3pI9yQ5Mzs59f59bId0txPvOzfpfcbX4Gav2+x2F1VXpQStCG/k2a9cgHhK7NWXDLPqfkn+rfcISNrExHVUFM8Q4lPRA5HqViqPQc9XalDdH281BzW4QkoMoaf+4ZLdfogZqpY8CtjYRk6qkKOdwRwRwwejypaeP2ejjaRm+/lGyer7F69VfFaws1lULKXpAxowKnULcuJARUGJyWewxv7mhVtcN7OJFOXotHgEBWFvEq6CiXu0dLN1Vn5MJ7CzgaVSrmakm7CaxigrgkZL2gv87tC6J7EsQbQ3U9s0/Yn7MeyF83s8KHQjeP5n0q/gszJ7JEdWP2K/8qVwxjA08h9HrMynB+efpPnxjKF2NS1p9dFso6JAaOmQ8tfEozfk8v7QI3vZvJIhGLIqnrVvDvOoun6IFDUtAvH/8+Chnp8DvZtk+ieWVI=,iv:kMa9Ahrsg1+cEzo0qZZDX2Pjz4BTTwdxZ6P7JozqlY0=,tag:fA96T123ANRUV3rsS4eGBQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnYzBRM3FXcDBCdE8relBk
            VHJxM0s1YkdpMnIrMEFMazRCVE5vV1ZMTFc0CnVLeXlPN2QxVFlZQmZvaU9VMitD
            bklscWlEKzNiUmZETzZLRzd2ZGh5bjgKLS0tIC81Wk9vRmJzRDFNU1NmMnJEZlhs
            a2RLTlVqZHlZZ0RPc0pxb25haXRuTVEKrmtRSoR0FZew7RmKsiWguVniBUQoN5Gg
            ZA5XUJnEM5r7qA4CYsT5PRDgqOSq9+AtZtIYF1BAEzvbi2Wtj0KjHA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zj2aq2a2v3ngcer7s3jz6pufhh8ula8pw56etmy28dy25wrkk3vq59hu2s
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRllhYnE4dTFuaEVTR01o
            YlFWTTdaemE5MldXU2s5UEc4SVhocXFsM1Y4CkFBMUFYYThteEI5OEJUV1NZQzV4
            RnphL2ZTcG9yMVkyTmJzZ1Z3SXNSbDgKLS0tIFFDcW9HOWZJMy9LdlFVU3VxUk5C
            SGE3M0MrMGIrL2NtUzNBZnRRaFhYQWsKJP2ycXg0ouz186y7ISImXrx/jlQU4/Pk
            hjJvL/gbHVTRWVjKytMRGc/XGN8T/K+ZxS49OHmuLxHI+FfHgcGHoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNXR0OEJzQTY0ZnZQZzBs
            OXRqalprQTR5UW8zYVRhdnY3WURVTFJzSlNzClRjSDRhc0o0bXZKV1NnREpUaXFB
            V1dwRE9xaXNXSDZUWGdRQlh4TGRxVmcKLS0tIDQrU0x1VXBqeVB5akJZZUNQVVJV
            bUgzMDdCK2daTlJWd0tXVEY1K0R1aG8Kh4eDlV0c6ceOxekM8QujpD4jcwIfRhLt
            61aTn4bOLNNVD9clqy7dIwpeS6BofftfX55Ak3bauyaVAfIbcyAO5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZXJWMk5ybE9nYWJINlpW
            dFRCQkRCRndpM3ZjVmUvRFIzTTU4Z2huVnlvCk9WcU03VjBsWVlhY2NKMkwvRGFx
            ZEViaHFNQVpoUVBZN0FZeXZ3cndZbGMKLS0tIEp3N1FJR0VwQ25ENUZrOTVuc3ZX
            S1lNRTR0WVZzbkJCdkxFN0E4VGtCVHcK9kLfUHRuhtUD0LP66KBRwKCZVExSDT/j
            bJL7QCnC+c6Hc4BsuIvfW9Q5Wz2/bo2DHlY69LuPJ+2hG5u926PZog==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0QWErcndLVm9yekpldlVq
            MzVVM0tmQmMxQ2xNTjBYalJabEg3eCtrMnpRCmZ6a2c4c0dOK2EyTDVKQ1Izd0dN
            eEpsemhwdGg3eVh2SXpNMy9zMzNvLzgKLS0tIGxacDRXTnBLK1o3bFRFUE5aeDVJ
            T1dzN2tVZXNrdytET1ZDZDdzTzNwWVEKdI4kp9LE4grU326EbdxQthYmUzSYcMiq
            JdHXI7QwGO311kbYlLa0ELB9pH5m9wyKA6MHVc7dKR0OeCBwAM0TXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRTh0Z1FPNHEwbU0rdUsv
            dmdCdnVIeUNLMEtxd2dTVlVwVnpybkxFdzJRCllrdndQbDVLQW5aMFAxQkMyc3FH
            cy9kRk5CbzE1Qnc0R094Yy9kQm1LNWcKLS0tIDFlTHYrOGVwWXA3Y09CTXJyVTcw
            SGczeGljYXY2TkZ4NGU5a1Vqc1dva1kKwMnD82kgoGE/V8kGhZJVX42Xy4/njmeW
            hLrV1+NkC6GHVIgfh3uuooeCCAsc+dVtIm2FqfJvrk6qJd3xZgSXrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTlAvSW9iYVlSamhrL0xq
            Tk1VRjgwbkozWHYwT1F0U0g2L2Mwb2pJaFVJCmdqNkN3S1JvbkF3Q2s4NWhRNXFE
            cElRVG9rakZlYVBXWTFsL3A5dGd5N3cKLS0tIFVjQlIxWWRHOXhBWnQ5TVNoVWZ6
            bEZvOTkrNUJ0ZFAxTmNpZXk1OU5heHcK1vh6xs1ecDjYHy6uVVGPVEcon6x5fFB6
            WbxYWRWetEw4Nu5c4nUdFxMEpHdt5jTq03M6tuAo6vFJjHjRpUEM8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYSs3S2R6QjFEMUlqR3lo
            M2FKWW00SUtWdzhVMWN4SCtWUzdQUytUVTNNCm5Cb28xVEd4dmNIMGxWcFRzTW5q
            dm9CQnpsOUh1Qk1OS1VXMC9FVEIzU28KLS0tIFkyWU1YdXhZc0RGcWNNRmNoZ09q
            M2dpbm9aQ2VmMHJBKy9DbmZ0SlI3ZGsK+TYEwTu6rA1zpV7IdNthSnLw+EamOdfi
            yRmq85CIzz/r3ljR9vx+8s4aksNqT+iGsnptq+rmewx0ZiHirvo0nA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwejNBVTRMbjlFM0tYb0NO
            cmVlL2NZK0dUSG9MTmRyV2FsZ21pTGgyL25vCmpzamtCSEszMksxekZ4ZXRuM0Rr
            RTRMekdHQ010dVh1dUZiQm5XakFXY1EKLS0tIDhSamFjckVFUTloVzB6ejBEdWdv
            SjVSa0hLaDRPTjlXSUovRi9sT3kxajgKBeofDxAn5c8p3h8uMuJyjndO5M8Xm33E
            ZWMnL2jLLVcMs9oLmA2zEfAQAXab3idwGKHbfuPwFsU/YdTGsB6DWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age198xvgu5frdusj6gnmducql6h634uapkcznnf704wn8wfqcumu98sttjlrc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVHUxUEt6dElwdTI2NEtx
            VUFiOGNsR0RUNHdPUUpMcnVJRkViekU0QW5RCmdLbktMSjliWDk2emhnTk44Nm41
            TzRyd3FnQUhzMUh4VUxIK0tYM29uaG8KLS0tIGZjWjRNelpUZjdJRUowejh3elM0
            QXd3bC9kSTMzOUxNVEpPYzlLWEJzNlUKTWPla6v/e9H3ktNeb2RFfkzyuvpFKEKu
            mi3pmF2Jd/qPZ5ahq4WX04gyWqyJcxpiXfQE+bm2r++Li5RWKDpJKg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4x5alkmvxsx5jsrwpecx0tne0ch2rwfkk0rq5w8x578j2pf5urssg5gx2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHT3RwQ3BMYlU4eFUrZ3hQ
            MlFvSFM4OHU5UzJ5R3BRV3JOQ2pwdUVVK2w0CnlzMklUS0lXNjZZUm1XOHZuWWN3
            ZmJpdmE1RldLUERkamxxODRqdFdtb2MKLS0tIHBUVW9pLzhCNk1nay9pL1FOZ2Er
            YlMvSlJWYmQ0Zlc3c25MNlRSU29uQzAKI5cIhpWgTooX6rTbzZ9nUzz587cft/oE
            1gghZFRu0ahVSySu9tSKeijqRCebNTTzUJW3W6NFEKoVVLl5C5lV3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl6m6gpea4kxr53c35y2tp0dd26nz8jurd7058nf0fmf2wqzxu0qsdg2fk
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cWdseHA5L2pwa202cFRp
            Yk10UW1BM2lkSVpNbzB0eW9FQThBTjFPbWpNCkdWSmJxR0xSVk05R2tvaDV3U2dH
            ZVp6K2ZJbnV3eGVEQzlWb2lKeC92R0EKLS0tIGg2RHhTWDZnZnc0TEsyb29sR0dp
            MzNDK0hscUtGc1hDSUlEOWplTTRWb2sKKLv4C0KtCvmCZiad2qny7PvRnMiHHPNq
            cqMgVrRAG/Ais/3gPNfBi+e9X6jutuCpL1pKNbGgpsOOg6ZmjwMAVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUkhxUmpNWmYybHB6UG5i
            OXhRL1JXY09HaGYxMmdLRnRKNFljVUdnUWlJCkFKUFVFblBJL09GVlZBOFlrR2N5
            dGJPMklRMGhqOWRXRUxaTjc3U0JFbmMKLS0tIG1hcnVUS2ZoaFM2Yi9xUW9lZ0tp
            dkFDTXFXSE1reitvdExjaERiMTVlbE0KBV9fFNh6zJ8YTxXxrRxoCTCiqX0TH8yO
            yNcs0ZS7GAN9rJr7KhGPvajQ9CqIUQ17vi8lmRfuEbuHXC1p9gpnMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucEI0TWlxTHdQSWtCTUps
            bStLU1A3VHljQk5FV2Vwb3RiU0ZUa2NqM3hBCjNGRlQ0aGpyYUdUUkZ5cmRJNjNz
            U2IrMm45S3JEbGZqQzRUNkRwM0llNjAKLS0tIGhjNnU5TEs0Z1lTOHRoaDJwNTc1
            N0pYM2IvK1lNRWdhRHVsVXo5L05JdHMKhd36gZPqF+3jP9igwkwhSzmFOX+Ww2XR
            Z8NpkT+4X0bF9uqblYqjtm/J6VQrDeEeaushPKf2SetYuNZ02tpnsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1axn36h9356ena7rq6y2xa4rcm250w9h0m9pz6x0677gla0v4f4dsj92yfm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkV21SY2FEY28zbVNKSThG
            WnhGWFZTNG1XV3l3SVV6TnpaT2tOMFQrNTJJCk56NE5GdkZqYlpFVWlJMXFERDdw
            VXdCenJjTGl4TTVLNjQ2RkFqWnk0bWMKLS0tIENPTUo2VFB3d2xycjFlTHNidmh4
            YUd3aC85b0FhR3JaS0owd3UzRklNR00KqKLgZuNCjCr0tiL6cdF6LDubyAl/Cjpj
            q+I9udHn6113KO6eBgBhav7cDbtN7YEmHZaqN7PGhqO+6rhtvdmP2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OWVVRzVyenk0WkFPQlVv
            TEUyOHR6SHBvQXpJZXE2Yi9qTTY4NEw4QmxrCllsdjl5eFMzWUgrNFhLZWd5N0pX
            M1FYVVF2YVFSN1dMZTFUOERJOTNERG8KLS0tIHlhMjdEL0c2MVU3cTcwUUFpOFFp
            ZHY2ZGs1TlczSm9tL0s1MW5nckJ5enMKRkRfmcyS5yS+NhscGV8a6Fh6Lhx4P3h1
            T71LXkA7bdRyC3ODDtQogfMBBuK2VxmMRpgmP8ktATd9245P4AUPdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c62ajygt7yx5k0f85h6w3tquu4ak0gg5c9drrhh34yyyea3xtpas8knau3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWDV0MnM1UnFXWGNaNVdn
            UDZleGlGK0JTajJ2Y1ZGS3RkbHZvVW5MWVRRCktjQ1NVTmJ5SnZPRU82MXdFRjFp
            ZXkwN3FxdE9OWEhXNEJQc0hzejJkMFEKLS0tICtXTmF1K0ExQW9vdFFKRFAvbnhT
            bjBSRXExbGRxblhvMWVlY05ZU1RUQU0KwR9dYucK/jk/OA8p3mxMxNKqiT/4gXP0
            7iXwmWLxrm+1L/ctgRiA7rPQtZdmenjVznVgEVXBOkhVy/rKKI6msw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gz3835qckr54gn44znlefa6m7yvjx83gptq8keslyq944nfxsfzqndenmt
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cnBYSTA5SGtFY3YvMGtt
            KzRmZ3NGVStNeXhRWU9xUFJTdHdEbnlobnhrCklUZGl5UCswbGxSUUxVNEU5VEF3
            L1dTaWNwY01JT01RV0IwMmdKNFZuSU0KLS0tIExReFIvbzRrbGN1YTV2M3l3a2I0
            Wno0Q1lVZ2pWZ2hqZHdZRDJZRWpMazQKDak3RPxfDKyWtU5MoPtYUQw6HlYPJO+5
            xtmxjqUsDjFKgQT4MHauxGn0ypfih0an3bkyGF9c4o6kP5h4jCLzhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age195mcxysuh5yxcuvpmftsfya3xgh9m2ehusnfsxthe5k8sd4kjv6s4upyl0
    lastmodified: "2026-08-18T10:38:28Z"
    mac: ENC[AES256_GCM,data:NxwEihmh/oF3NQ4469LGmjcEjKwlmMb07DQyY8NTGJ5pRdGXo3irZ6gVTZp1Iwvw6Ja+f5G0SkE/qtVybBJaTbCEkpXcg2MroouRwt2t+f0FtlH6ON8fVvcEfhj9fLl32dFAnc1LJfYv+gzVxrwZ4E4sY4SJSOMI6d4cBc4ItgY=,iv:EiyqFmLctw35XlTSRbJNQA+E4x50zjs+jweBiveSsfc=,tag:sN9NJJEzsxRcdbK63naCzA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
