apiVersion: ENC[AES256_GCM,data:8iQ=,iv:juaB9usSodvX574DLlb7JBcCLxwRqLnVwD79/7Ka6iw=,tag:qz5aEM+5VXK8EjodnaHEWg==,type:str]
kind: ENC[AES256_GCM,data:y8K4l8nU,iv:5LgUrlg40tR5dPezYHnrw+FTW4vNtJM2seu+o8D5OEs=,tag:ikcSoilmizJ+ljQozQHe4g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iY4iQd8wf53bRYINLW9Y7DNv,iv:Ce9ZxO2a1+Hw4n6Po/EQ0jnahLOmt3abeRw3HxkSnXY=,tag:U4fuIjQq/iAsl2zbiyC8Tg==,type:str]
    namespace: ENC[AES256_GCM,data:uXymb4Xv5dh29Wc=,iv:wElN/XRVOLBp93k3dh7xClbP+BTUIc6f8SUgyuXRO3I=,tag:/fugRFk9wq/wN8IrFTbhbw==,type:str]
type: ENC[AES256_GCM,data:kpf6n9zz2ampsydbbf7zq+jAlxI5WClE,iv:EepPhMw/7K7pkHNA9l6A1Nxl472ju6UZue0bKGD2Tx8=,tag:ZDW+klc/bD6ig2cl5No+/g==,type:str]
stringData:
    username: ENC[AES256_GCM,data:4YHxFXXNLvEe,iv:5/0W90N+m+hFn/iO2xkXIq4qol/LdwC8kXsDg8LJu4k=,tag:NHP5IQ99g+SR5vmg0CFhxg==,type:str]
    password: ENC[AES256_GCM,data:SjR3mgr/NDoyVTkuxSTtKjIWCCckFe1cl7kj3RPSYDFGpzu1a+O289LTR64=,iv:l/ooQ9xNUxqg06NDjUAnnC2d+LEcPD4IOKgk6PiGdJo=,tag:AQdEieGaePCapBS7CcMatg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWlJZS3RPRXVmWkRqWk1C
            dkhVRENnSDIrN1EwL1J0RmFiS3ZINmtDWmdJCkQxTTBMWDg0NklGdzBDaFdqdlRN
            NFBwZlVVVThmRXF4QXl0amZHbnFpU0UKLS0tIGFOL0UwQTROMEVlVkxHdVJ5Sy85
            VUo1dlovY1MxRTU4SFBMS3pldnpuQmsKUaFomwjA8vynON2kLOEnJB5Z0R5yHb5J
            8LpwxHjZXBQzsB3ep0HnPbsAUJ/Gr7OrOsQJczgJjWyqbKLAPKQRiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDRm4rSnlDdHBxcHM3dnA1
            TnlCWjJJK1grYkFSbHhwaDZWNUNCVEQrbWg0CmtreUN6LzZRdjZSVm1rckNmVmUx
            ZGdRNlY2bXZZSDBIYk1vZUxwY2NPU3MKLS0tIEFxT1JHbWVBOFpWME8xS1I1ZWNt
            K0t6SWlHZXhrMFFhUUNHUEpWNVUrcDQKeal7WAuB2T/03x3GtJU90UU5FI8SCtFi
            SiduvyXEn+M4Q8ic/MI92kIJ0O0QzHWPLZTH3jYtJ6CbrTB31b9Nlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SFd4Y3FZNFUxSkRiTEhl
            K3RpaHhIVXJsYVF0S01pV1RSbVJDdVc1OUU0CjF5Ymt0SzFGVFV6ckdGUTkwN0dV
            eXpjenQ3eHMxK2pCNG56MUpsOU5xQXcKLS0tIGQ5UXAxeHg3cWUxd0FZeHN2TXJ5
            TFhSdW55N3B1Mys1UEo1SFo1QWdnV1EKLOMcr9EyshOW7XgA/y6F7vu+IHKFjLkA
            Apa/XXitEYglCovqScyrtTbOFr6kG3RALPUzO1LqpKhQfmRZQ0g4Mg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tdgfvwl4qdptyvgxju3rwz9uh45hz422txzcgsrwm4f4f96x558skzxklr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQmNRNmhWbk45dFNMaWdB
            Y05ZQUxNMDlMOXFHcktXUjZ1L1ZtUzZTTXk0CmdDNlNWcmYwKzZPTjVSV0YvNEZz
            Zk0wQXZGN3FFY29rTjA1TFZaQ2RwU1kKLS0tIGdzMUVoQkZFNW51b3J5UWdMVldT
            b2gxY3RTcTRQeG00dzdtRjBUMk5OWjgKQ7mApVS1r1866ba3+6LBZn0WLBxBmBaS
            9GyR52/eEIUzpxrCJD7FQ0xQowzAZpigCzxgwS9/gAoeBbnM5PFTfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXLzJHZXJmRkcrc2VRbXhF
            MlZNVVVqblpDUkdVbUd4UlZiQVBFTFMyVnlJCkdtdXJEWndBdDNScnZaWkdzUXdR
            dTZtSjV4VVREbDFFdXFFVU54MnBSU0EKLS0tIGNEWEVtSFZSVVo0VnBLeGpKOEhD
            V2ljK09EUXI5a1Nscy9UUGg4bUlQeGcKskof2VTcs0IJlwXsY4RkZ/h/1clmdEym
            BcUy1UbNf6GUPOs+GxSZxL/tpR/C2Tbq7WnzgMbJAbnaPI74OPXsEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdVF2dXN5eHYvSWI2TEJC
            NlpTS0x3enJWTmtvbTdiajBXNDRYTHVkZkRVCjhPYVdNQWhnSXRYYWR3bTUxNkZj
            a3Zadm9PUTA4cEJGN0YyY1ovVFdjNVkKLS0tIFc0NHhyRjNtb05BTCt1T1ZhUXhC
            WEtWaEFzeUZmVlhTYVk3NDBzcEViWkUKUaFKpVWO3j4vqfXpBjdOArx7SceJ48Rv
            fKldiKWZBRoihBcTN90rbfuvy/AVh5HxzicxcTEad87hssaC0BWnug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSjlhdisvdU1Hd0pnNEJp
            c2xLMnIvWUdsM0lNdlNhc2dNL3RnVWl5WkVnCldBd2k0OHJZdWJuZEhlaUtYYnJm
            UVNNMnlXZ3NIYVN4bnZ5SjE2NGJydG8KLS0tIHpLN3JWVlU0R3FwcmNJNkI4eEUr
            d0pldXhVb1J4c0ppcjhZWDZCZHcyVTAK1aXTvdH4rCMXjBBsjKjt8ghynNw6vsJL
            KjPK0OB4H2mN/KvzikAAqB4XL8hNjHEANwC/V+dqXPu2RUymWBTP9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYUlSQkhqbEJKcE1qT0J6
            ZzVZSzFyMlpQT3FEY3ZIWjBZWG1FUkFyWjNBCjZCSU1DRndFcGQ4S1ZqZm9oZlY5
            MkdCMmsrb2twb2FVRXgvUnhianlaVGcKLS0tIFVwUlUxOHgrRXdmUVRCSWxwT2Jn
            V0F1eFEyWWlhNHJ5Y05Ia3B3T0IveVkKNOr6eh6hfqW4lBS4IIgG1SJZaVhfXxSN
            YLCYvsPL7HgYztcKW+/rEjD02k/e0MfODqDwiOWWiyZNaTuB71KVpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcjFNRjlqN1VkcHQxeGk0
            TXJCclJRajZneW5RMGNKbXZFd2VFRWxpRWpjCkJlR0RCYmdmQzJqSWMrbkxJRGFS
            WkZPRElxZHNyaUNTUmtyVkpYa1Q0UWMKLS0tIHRzR21CRmJEaXBRcE96dHFiNGh4
            b1IwTjNkZmx4Tm04WkxaODlqbEZEVEkKYzeEEuAwF5soMRf/k8z7Ckza02NdDOEl
            P85jC3rgo4IrOWbiejAzz0eckO7AtekJ0PuN+gTHk2M5hT/xKH2RSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkS0JRdXhFOWF3ZVRaYlR5
            SWl5TDFvbzdDOEY5c1Z4L1FOT2hET2pCY1NjCk9WV1AwcjV5ZEhyTktia3NqOVB5
            eWZSUlRSSWZWQjVpT0hTUzl0cCtQMGcKLS0tIDA4SEhYR0JINjFKd25RMkFEeCtT
            MFVRVkdYUC8zWVUvWWwrSWtaMmgwUWsKg1iqlJaHBVxuMh4IspP0jzLIluzxNmtQ
            dCIM2Xon8glRW12II5dvEAGSAFceusu4KiAZgijnSpEIshgeQ5jYuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l5t62uzsj05pzftv9wg6s346csxyq202vxmmyyx8gwy8zu2nrfrs7v2a4z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrT0pPZWd6S3lrc1JJUFha
            OE1uUGFndEUxeFg2cFhBUVpWUTRNNlpaZEVNCnVlMTNGamhDanZQRytTQkRCQzNv
            d0htZUg1TDFoVkpFY0FudldudDMvTDAKLS0tIE5Cb1k5L2RTZkF4aFRZMkdJQzJZ
            WWFPcGVkdHdNUjZFZ3VIZ041M3Z5U2cKrv7O7qrdngcGhCdTWVK7pZ5SQ73nkCyT
            AwNJm9wZ65dfkJlWjyLPg48H1oPHPFvUHF+2ym+Pc/wI7LpMS4FIoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
    lastmodified: "2026-08-18T04:04:00Z"
    mac: ENC[AES256_GCM,data:GtmqFr30tkyg1FFjZmq6J3fkQ2BocCx72ftxN1lSOG+g6dLnT/VhtBKa02cqE0wJzbRpxKXNgTeMf2eW3xb/m/ROmd2aR62YiC0BKrSe3FWGmhWBL/17Zh6nAIygI+cA46Pm04F+jpuWiL3l38VVHFyDnWz+RbPoSRIrhjpW6qM=,iv:lhRyWV60hZGrVNNBA5vQbP8PnSRWxQim0vTApQ6uAaw=,tag:uT9wS8GG8y903cskjoFvqg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
