apiVersion: ENC[AES256_GCM,data:8iQ=,iv:juaB9usSodvX574DLlb7JBcCLxwRqLnVwD79/7Ka6iw=,tag:qz5aEM+5VXK8EjodnaHEWg==,type:str]
kind: ENC[AES256_GCM,data:y8K4l8nU,iv:5LgUrlg40tR5dPezYHnrw+FTW4vNtJM2seu+o8D5OEs=,tag:ikcSoilmizJ+ljQozQHe4g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iY4iQd8wf53bRYINLW9Y7DNv,iv:Ce9ZxO2a1+Hw4n6Po/EQ0jnahLOmt3abeRw3HxkSnXY=,tag:U4fuIjQq/iAsl2zbiyC8Tg==,type:str]
    namespace: ENC[AES256_GCM,data:uXymb4Xv5dh29Wc=,iv:wElN/XRVOLBp93k3dh7xClbP+BTUIc6f8SUgyuXRO3I=,tag:/fugRFk9wq/wN8IrFTbhbw==,type:str]
type: ENC[AES256_GCM,data:kpf6n9zz2ampsydbbf7zq+jAlxI5WClE,iv:EepPhMw/7K7pkHNA9l6A1Nxl472ju6UZue0bKGD2Tx8=,tag:ZDW+klc/bD6ig2cl5No+/g==,type:str]
stringData:
    username: ENC[AES256_GCM,data:4YHxFXXNLvEe,iv:5/0W90N+m+hFn/iO2xkXIq4qol/LdwC8kXsDg8LJu4k=,tag:NHP5IQ99g+SR5vmg0CFhxg==,type:str]
    password: ENC[AES256_GCM,data:SjR3mgr/NDoyVTkuxSTtKjIWCCckFe1cl7kj3RPSYDFGpzu1a+O289LTR64=,iv:l/ooQ9xNUxqg06NDjUAnnC2d+LEcPD4IOKgk6PiGdJo=,tag:AQdEieGaePCapBS7CcMatg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cWpLYTF3d1J0c0xYb3p3
            cDBsMnpEazZMNCtZU21LK3dBVlUvVXNndVdJCitLSUdOT3NFSnJod2tYTTlyUzRh
            dnllbFU3TnhlS2cxdEFsaEExUXJGaGsKLS0tIGFZeXpkMXJ6MFFVdzFvWE8wd0RL
            dXRKcFh3U29sSHB5dzZ6TGsvc3cxS0EKCoJQGWktLW+F+n3mXR2oR/zO0n1TH7Hf
            owp/XxsICNqKOByi3syN3j04HIn0TRqW++zZOLOfGReEa0GM8RKa0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaVNtVHQybzBYWHBScjNN
            Ym9GeHVRWHR5QUJQbXVqZUFSQnVzMGN0SlQwCkZTcTkwS3NiZGNnY3VndXZZU3d4
            ZEVIWVBOaXc2NVpza0h6QjlGTStJNjQKLS0tIHcxNWlueXFlSzQ1R2YyOG9CdDRP
            TjF4NVdvRUs2RFc5ZDVMSk1kOCtjOVEKp0kh6nKFIRxDW1Iu0N8zDeKVGoQ3idmC
            I6UHJ/yBgCyewECAmxq97ewTn+pUYnXdF2yzXFRf0LRjWs8v3W/JTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQN1g5VTdNR0NwN0RjWlly
            ZjhpN0pqbm50c0NpOWszMlpkdDFHSlJsWGtrCjhDNWp1Q0dadE1vcExCd2xJZ2lC
            TzAyUDh5ZUJQcXVxM3hSWTQ5cnh4YjAKLS0tIDg3R1F2dHUxV0NYcGhYQndJeEFM
            YmxtUmhtRlkyR3FXK1BjNG1nZ2VUVFUKRQvpxypX9wnpS5tCZrj7OStJcN6QlnoE
            6kBz5FV+yzayawBCdur8/WZQw1YtQMWBNGEdin8N+CCgb2cLekdLEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbS8rSlF5VzU3NlBFMTJh
            R3BJUm5KYjVUMTFDcUhhUXQxM3oxbk52aG1zCmFkalhnVU1qT0VERkZEMlJsNVpH
            Q3BxYWdKRkhGSGo4OGMwY1pHWHhBQncKLS0tIGR6RXNDWEgva2hmTTZDTG94c1lY
            ckVscFp0cFMxMDNMUG9LK3RqbWhtUFUKf9wQ23d8kkCN8d01udfd7Mgre1eyrD+w
            Rmi2j5xyoL3pyeC0uxHKcfFeGVTJu1Vb+jSfbkcZ1XwdafLzcN3HUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZkNjek1SeWFZMUplMFpI
            d05wb1hGYnVqT3hYRmo5alFUVUlVT2JIMm5FClRIaHhyVkI4Ykxsb1c5KzI3cUd2
            MVk3WTNvRHViMkdNanpINERIcWN5bmsKLS0tIGlJZzRKR0lmbDhCSmFjQUIxOGJR
            cnQxODcwUURDVDlyZmlNbkpoYW1rbkkKxrP1C49j8pqN2x2KwLUmudONzhC7PX2R
            Q70qhUhIOXHhUKvVSs+XcCdtxaQ3gUqBD80l16F11d25FI2JprxxKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMEVRY1RJemZXN1YvcGs0
            NG13azRVMVhUS09LTEhHckxRa1FlSjdreTNFCjA2cVNQbmJvc2pFaFB1ZzFFWHFE
            Y3p1NHhUTUtVaEQrUWFHT1BEdTFsZTQKLS0tIHpmZlplK3cxM3daeFlwY1pPU0h0
            QzF3OU15dDlITEpsTzlIWm9Zb0EvcFUKvDJBjMokx3qT4LajGKLmaqt3ZcE2F8Du
            J0Tz4wSk1G60HvIGXwcuxg1IqAZmLM7PAEbzY/c/8HFdY+ZJ/Hjs+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TkpvenhldWFWZHh5Ujh5
            cTlXTnZlMXRaWm5yY3lMTThWMjdOcnZpRWhjCnIvQUJYSjNIVWwydXF1VTNTVEgz
            eWFNTndDYkNZS0dnU2FiYmxoYThrSFEKLS0tIFRkVVFOc2pmcVNxM1o0ckk1MDBW
            YkZpMEdMeVd4cWcwUWN4S2R4b2tmRjgKO7DTUNM9Bzy5tlfzU3C99tHHYx2nFm/g
            IUDFNRcObzguS0bNI2VJQ/DNE1mmakEGO6Bvkl2tWzwvc4JCzQiHuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3R1NKZi9FVmJONE5xWk1B
            N0swcmh3bzFzMW5nZGFZbk15OUdNSFBDMW00ClludVByVC9BV2x5T1dXQ09lT3Q0
            UTcyYzBSakV1ZGttRnRGT1MyMnp1Ym8KLS0tIGtVazhDRTRUaSsxc0VpVmttc2Zp
            R21hdk5JUUR6dWM4Rlg1QWwva2VTd28K830ewROTPiPiIDV/USx8HaU7ndQfU9ys
            j0/up8v2jIoWRkH9/T9fTtLtKGEMD2n8Yo994QtWk2rqIcAX897Orw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUEUwU1duUTNYVlVlaXNl
            anpINTVHU3JtbnVxRjRleUdrTUtiL0MzS1hzCjk3US92bmI2WUdSZXdERndxNU5a
            bUNRUFVzTyttcmREcXhMZU9HOHpjS00KLS0tIEg4ZUR3Z3E0QkdveEN3N3JWK3c1
            MEJmOVMrTUlKaVVyVTVuVFR2clB5MjAKaT3MB7uFFEnKgrhYwGV6NCiUDUcWv1pF
            LTSyJF10efYDskEZIhbBPk2za6ZhiKN8O/+OnTjZimv2wpySXJ0tVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
    lastmodified: "2026-08-18T04:04:00Z"
    mac: ENC[AES256_GCM,data:GtmqFr30tkyg1FFjZmq6J3fkQ2BocCx72ftxN1lSOG+g6dLnT/VhtBKa02cqE0wJzbRpxKXNgTeMf2eW3xb/m/ROmd2aR62YiC0BKrSe3FWGmhWBL/17Zh6nAIygI+cA46Pm04F+jpuWiL3l38VVHFyDnWz+RbPoSRIrhjpW6qM=,iv:lhRyWV60hZGrVNNBA5vQbP8PnSRWxQim0vTApQ6uAaw=,tag:uT9wS8GG8y903cskjoFvqg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
