apiVersion: ENC[AES256_GCM,data:pok=,iv:l9iB2/EczVOF9rp3leTqH342hQOriIT9PRPUTrMdRgI=,tag:d36SIakYwzDfbLwCeDg6Uw==,type:str]
data:
    SSO_OIDC_CLIENT_ID: ENC[AES256_GCM,data:wadHXoT+RnKAK3b8PV29yz+7+/cbnuB4gmACUvxcHPI0uD1E9x9igvyh27TGzirl,iv:q6MXnMR7TJkHr0mubmK+6tsHRvd/B4B9GfuLB+xSG+4=,tag:S694LXj1A+8Q8xJyhkCZGA==,type:str]
    SSO_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:3Sq5b+yUvJWKoU0S2zuikFScq2J0ldviiupOmmfMz1BXTGAmumYaAv+b5j4=,iv:vWFsKPKZ4JCEyvLoePC9NjpWuG/lKdB5HIqY2Sunxmc=,tag:aYQjililWnlS0l+lbnrGnw==,type:str]
kind: ENC[AES256_GCM,data:Q5IF8h5n,iv:xVKWwJ0WBu6SuiW+16efm7gS4nQoMlcW1naQ5UjvcmA=,tag:lK28X9FtrteEs6JHBW4TFQ==,type:str]
metadata:
    annotations:
        helm.sh/resource-policy: ENC[AES256_GCM,data:5xfsBA==,iv:ky1NzJgiv/F0DLWpkOdgdThtBLyuOCGXcCOmOrtYdOM=,tag:0WPFSw8ihl+0Htm10INyfA==,type:str]
    labels:
        app.kubernetes.io/component: ENC[AES256_GCM,data:Ngw2GyhNMg==,iv:DPAMYbxfxs4UFW5Fy3POjKURlfpfEovfWkiGvmx3J+8=,tag:VaPv5vx6i0PLm7b+e83IiQ==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:gejmzOmIO0UmhKlEgIgiTY+jMmHlBw==,iv:LQrq+VgPOqmkQCG8xQ4QCis/ZkUn4pS/gcHU0dIRj70=,tag:1L32PeEZLALPVfsz4vOjrg==,type:str]
    name: ENC[AES256_GCM,data:fBOy5r8DWd6uV0sT5L1+I+0ZBhk=,iv:67PSzwP0egwF278ykZJklEHMs3fUSH0UXcmBxxWuQ4U=,tag:IahwoQwdzWjgukswP5LTMA==,type:str]
    namespace: ENC[AES256_GCM,data:/VlGyBiK9JdJI8Zo,iv:yGtSqrV0xYjJOfoRYMnEt88DBv40qTZwaULuPd9QcGg=,tag:wFsJGEsFXYVjJLF02x34dw==,type:str]
type: ENC[AES256_GCM,data:6E4C4z1j,iv:JO7EzH/zwi3/iG0TUwf7mDl2NXlSokE9rC7CDNyhdAE=,tag:7hm+wOdVYKFRhhb/akgvNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWjhTaEZUOGpUZTFkbkZR
            MDgvK2Z5OTB4MUtGdG0xbm1HUGlCdTcrOWpzCkVjZ3VaYVI0bG9sS09ZV2lvTTVr
            V01sZ1ZabEpHWStNRE4vSkhuOFJSQ00KLS0tIFE3T2Z0bkRaaWRvcGs1djZzU2NZ
            dFZiS3F3QW9iTGdDNGtmK251T1pxS0kKMtvPHBjaSXgn13kTOFtdH4Zadh25aKNj
            CE5V/7aalzrih3RDrS4Iv8WAWEiMo+H8V9QuGjzUI6kW0rxKJf34tA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWb1NIZ2VWdzRvbDVqN3gv
            R1BGaXhJZjhXeEJYMjNzU0NrZUlVWkwwQXdVCjF6NThNbys2S1F3S1hJdVdpNXZn
            SHFXSXV0SFZFMzVtUEp4R1pzTlhhR2sKLS0tIDBFamYyMVY1YW5BT2hDdm9WVmxH
            SjdCTFFkRzhmaytpN3BUVDcrRmF2OGMKAM01i2/nhuSvXrmwl4c/eJ0AZq93Hipr
            088UaAcRN/GgQLfemp5Zdl8cu87DM28wHscEFOFGlKi7Z5qaj6UQNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdkU2bHJVcXpSVG9YYmI0
            TzBXTFB4Z2tKUHV4MjArZktieUZrVk9kSUZJClhCRlVBVGdBMFdjSGh0UlllU3Rq
            VCtBTWdyL3dMTnkvNUNFTEwyaXYxYlEKLS0tIEl3a3h2S2xaWXFsQXFDeU9oWUZL
            M3lIZ2lkbEJTSCtkZE1Qc0owRWxnejgKdkqVuOc5xzgMPTrJCkBIgsw1JuDKs87p
            Rb0gga7UiFe/OTnc+99yx8nt9PVo1iF3E7O8JEQcWgyuw7XqFikqLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tdgfvwl4qdptyvgxju3rwz9uh45hz422txzcgsrwm4f4f96x558skzxklr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZEtDTnZYUHo3WkhTMFBz
            VEJuWk1ZSFQvWDFuenJvVERScTRlTnNZOGtvCit0M1lpRDVySVhHVEZPVTdXaURi
            ekZ5NDV0alg4YU43MGRZYURUMDQxd1UKLS0tIFdVM093aHkxWHpPczlRZnZwalFK
            WGM5U2ZQQnFsMXlma0VHeTB4Zkk3dm8KJtReeGzC6E+MjQLor6NGkWZbk9G07NZF
            35tt+uA3re1gPJmRrQJqwlynsAC48Oe2tAOU3mTpznl2proPLjZAqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFa1gyYTVSWXpRWlpKdUd4
            U3dHQmQrMlZDYS8wdVorNEZSdlFNdDU0MnpnClBaNmRjV1JqbjRlVmY5aFJmYXA5
            S1JOeXd2YkppQ2lLbWNUa1RrQXY5TU0KLS0tIGlCNFVuSWc0cTBadlo4UHZJWW0v
            eDNicW5UT2ZmRXFSN3o2eE1MNkhudVkKU7M8g+m3MWZ58VdU9x5qD0vFOTQNhOZn
            pk1MDrxCAK/P6jzy0kHUDRkql3DZ+WWlr3abuBvX4BmxDydCCunyjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbUVxRndGc0xTMEZSL0Uz
            Tm5sNGtEUXdNeFFkaDVvRVcrc3AwM3kxcXhvCmF1OTYvTWw1Z2pnVnJPNk1RNHNM
            WWpWeDJPQ0JyL3dtQ3BVTXpyb1BoYTgKLS0tIEJWaU9DTSsvaVRnMVNzQXl3ZTVy
            dFUvdUx1bzkxcEN2d1QzbjBpWmVaMkUKITU+GtvoJspiMrQCVFPoz4dQJMVtTNLu
            xDxuaSCSkgbmRDZ9ryOn36P7CcLufwIymVm8RE2JHz6I+i4e1QQ6+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RFp0bk1STmgzeVEwN3JK
            ZUgrZ0FHZ1lTZlhhNnB4RnBUUTZjcFkxNEVNCmpVeW9ZeHNzK2hCOFc4bmV2OVFa
            cVMxSVYxdlN0aXFhRE1HakF0VnJFenMKLS0tIDVmV0EraENLNktTS2paOGpzZ1hm
            ODgwaE8ydjZBemJmcHR0S0VScmJmdGMKpIaq7BM81CZ8Pj6ZvmQYDAfthXm1i2Gz
            Ice+TrZzkubOCyXKqk/WHQBr3MGVsUK4H0y1wZLCVN9cAnJCc52mig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNzBQYnVIMVJvMG10TUZw
            TmVoMGRpVGNEUW8wdHYzaDQzSHp6T1llNEVnCjc1TFhQbHhraEpsanJsZ28wMWxJ
            V04vZno3K1RRNTUxR3VKZE9IK25BeEkKLS0tIE9QUTFMeEpOcHNlN3hPbkF6ODZh
            T2NpMTYrMWRIRnY5SDNlbWwzRVVPY0UKA7z96kZkvEwrcsuIeNaWnG33rC3RJJ/D
            rI0w/Tlz1CIfxQLBb7qlseAJwFMPgc/NnlcIXn9pjoVxsCjN/SG9iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyWERlRitwVmY0TFMyT0Vr
            SlRMUWs4d1VkMjBzczJidjI3a1ZDZ3VvemxVClEwMnl4emtHYlBUOEkwaC93dDdD
            T1FKdnd0UEZ4K3NRempHVjdUdkZUaE0KLS0tIE1VNE1NelFpeStpTkVxcUlJdTQ3
            Z0sybWIxR0tMN3BMR0JySDJEWUcrRTAKhxaxUOv1PMX34iLhbz2m90pz4pJjR3Ep
            2JXYu1Y2Jb29O5Uy55rkh19JSscmiR+Z4Y7aEgxzXczXguLkr9FFow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VytJM2NyUUU1eVh4YkdI
            NVE0MEh2ZW5KSUQ5WTc3ellnZDg1cHpETVZVCkJIckJmbHlvdlVGZlFvNnQvSDFz
            M3doWjlpRU1jdkx5NzYyWVZIQXF0S0UKLS0tIGY0dGYrcm9laU1Hc2xLNU1PQ01O
            dU9YSCtKd21oU0RjNmp0T0xqWTl3TTgK3/rKam77s/SqfQP9b5dVyJZzSJi1PLf1
            Lc45Z0Zaaafw1DJs+oDtJbPPO4x5XSJa3Uvm2ip1XyDyE19qOTzGFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l5t62uzsj05pzftv9wg6s346csxyq202vxmmyyx8gwy8zu2nrfrs7v2a4z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN2U2TGJQUWpmY0c3dWIw
            L3V4Z3hXWUVkZ3F4VlArOVE0ZlJxM2daSng0CnVmQVB5Ym1uRmJCaVB6dUgyZW8z
            VWxFR3FjR1VYMjRHbWtnbnNIZVpDUUEKLS0tIENKd29rYlZrTkc1cTJsUHdFOUpu
            UXNqMEQxL3RDNGZIN05MK01Icld2R0EK3UuA53m+YHFLdsW7K32eETH7VKNsVCCh
            BgPj+nprnnAoX7vlWjcSvgUnVhILr/rN7++6uw3Srtdkqdlc4HeAXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
    lastmodified: "2026-08-18T09:47:41Z"
    mac: ENC[AES256_GCM,data:CD0fh73MSxfNE+xt0/KKh2Q4rxwiaRaD89HLf3nFUYDEfaP+pBQhKLHbIVKIQKKmhz2KIaos96tOMtlgOtFs6lgSQ19N2UT27SVE3AaHeTv2Cs0mafpGvqjFRD2iT+46v00+hHsX1LOUBBnIBUaqBJi5J16yahKrGkZOyi4LwDI=,iv:LKEbMkE0zL9v7+x10lt94zdZCuzCWfqwkcR3/XLYJ8g=,tag:1EGMsLd7Fh+WdBIVh6r7FA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
