apiVersion: ENC[AES256_GCM,data:pok=,iv:l9iB2/EczVOF9rp3leTqH342hQOriIT9PRPUTrMdRgI=,tag:d36SIakYwzDfbLwCeDg6Uw==,type:str]
data:
    SSO_OIDC_CLIENT_ID: ENC[AES256_GCM,data:wadHXoT+RnKAK3b8PV29yz+7+/cbnuB4gmACUvxcHPI0uD1E9x9igvyh27TGzirl,iv:q6MXnMR7TJkHr0mubmK+6tsHRvd/B4B9GfuLB+xSG+4=,tag:S694LXj1A+8Q8xJyhkCZGA==,type:str]
    SSO_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:3Sq5b+yUvJWKoU0S2zuikFScq2J0ldviiupOmmfMz1BXTGAmumYaAv+b5j4=,iv:vWFsKPKZ4JCEyvLoePC9NjpWuG/lKdB5HIqY2Sunxmc=,tag:aYQjililWnlS0l+lbnrGnw==,type:str]
kind: ENC[AES256_GCM,data:Q5IF8h5n,iv:xVKWwJ0WBu6SuiW+16efm7gS4nQoMlcW1naQ5UjvcmA=,tag:lK28X9FtrteEs6JHBW4TFQ==,type:str]
metadata:
    annotations:
        helm.sh/resource-policy: ENC[AES256_GCM,data:5xfsBA==,iv:ky1NzJgiv/F0DLWpkOdgdThtBLyuOCGXcCOmOrtYdOM=,tag:0WPFSw8ihl+0Htm10INyfA==,type:str]
    labels:
        app.kubernetes.io/component: ENC[AES256_GCM,data:Ngw2GyhNMg==,iv:DPAMYbxfxs4UFW5Fy3POjKURlfpfEovfWkiGvmx3J+8=,tag:VaPv5vx6i0PLm7b+e83IiQ==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:gejmzOmIO0UmhKlEgIgiTY+jMmHlBw==,iv:LQrq+VgPOqmkQCG8xQ4QCis/ZkUn4pS/gcHU0dIRj70=,tag:1L32PeEZLALPVfsz4vOjrg==,type:str]
    name: ENC[AES256_GCM,data:fBOy5r8DWd6uV0sT5L1+I+0ZBhk=,iv:67PSzwP0egwF278ykZJklEHMs3fUSH0UXcmBxxWuQ4U=,tag:IahwoQwdzWjgukswP5LTMA==,type:str]
    namespace: ENC[AES256_GCM,data:/VlGyBiK9JdJI8Zo,iv:yGtSqrV0xYjJOfoRYMnEt88DBv40qTZwaULuPd9QcGg=,tag:wFsJGEsFXYVjJLF02x34dw==,type:str]
type: ENC[AES256_GCM,data:6E4C4z1j,iv:JO7EzH/zwi3/iG0TUwf7mDl2NXlSokE9rC7CDNyhdAE=,tag:7hm+wOdVYKFRhhb/akgvNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQ0IrMHYybVZKSE9JN3pr
            ZDEvZlZham5KUFRydWo5V0ltUlVydjBkWWpjClM2eVgrM0MxOUlRVkIybVZWcnZC
            MFFpbFlQaHlSbGY5N3JGUmV6MjJoR00KLS0tIHdWVGN4S2VWV0t4OTJ0Z1o1T2Zj
            bUM5OVVzWVlvWEg1ZzBIZld1QlRBYWcKIOJTekPgMSk38QVZr7STxT7mdVGgoSy4
            mzAoYUyPKiDdRrvR1WPkhBnhuPJ+Us35OPte8rRc9+UKcdwod9vrTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQzlKSnNvUlRrS2owRUFE
            dGwvQ3RNM3czVE1WRTNVRkhLWndDZUk2cTNRCmZRQi9ZRXNBcjJvOUJmRXVIZ2NH
            cUR2cVc2RzE5b3VYcUoyRVR6dEhhSncKLS0tIHRMK3A2dkFmM2txcytyWkVGc3pr
            RHhIYVNocVFjQ2JhelYyZEY5WGJZT2cKcWIEJbLw+e2KPxSb0epI4UFb54b+Urdr
            5srj+qArysqG6pOangesgTHEbGUdqWOyHKMdFqrcBE77NUwydqiQ/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyS2tNUlJqbk16a2lRRmpO
            a1FodHJ1djd5MnBRb2QwVUdXcitMWFRSNFZFCllzZ3QvWnJSOUVEVExFdzdJV045
            ZXFmeVlwQUxybzBoZkJleUp5UHJyeXcKLS0tIHRXY1NtbjMrM3RId2s0UjkyWkQr
            eDdVVURXUlppMzJDL1QrdnBwWEJvaUEK8MKJ9C1w+ca/AG2urCjosVFtNIt06S5A
            BqihaEjGLu+FZh6mlaX/3NVdtE2j5xBsFFGN71bKVg8zAW8Tc+v9EA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SXFyc2JMMnl4ZEZadzN1
            YzQzb3pBOVdSR25qaWpsd3dTS21ER1l4VUFZCm5QbEk0eU45ZU51ZTBIM3YySlJL
            Rjc5NDV0UFg2Mmx4aWt0WkZDNDlmM0EKLS0tICtwRHdJYjkrdldqRUJxQ3cwRmZY
            VXZJM1hmVVFpNUU0UHk0RkNZYnNmRk0KTwYypVqm+7gvDMwGnywr/Z5fUldazpXH
            nH/YG0O1m7WLZ9HPu7Q3i63GfWmpByGhA9Ia0wKyMVZfVQRQWFJwJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSk9ZT1UxRFBiRHJyQmdN
            MEZITGRGSldsNU1yeDRNT0FsTUxUV3lUeERFCkZKd3AvaFZFdW9xQVl2MFlTcWVs
            ZHkwenNseW5pVURiRzBkWitqZElscTQKLS0tIG5USUdnRHhXdnVhY2pHVlpFalFF
            NWZSUXFxdFFFbDNyVFphTFBqYkhkNTQK/SvzQbE8gS4TDC/EMchcFsqTRsfBujiX
            6TgUVcOhmpgW/I8zN4o/tSCb0pDy4yYNyxBeaqTiBuBr0riUlsF/Ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL1JLeW5laE45bkNhM1BG
            NHpRRUJrNS9hL3ZPUUdwUDFteDZ4Uk0ybzFvCmMveFhZcVlhV1R6cVRvYWdIYW9H
            ZFg2OGJTM0VRV3FzUHlTVUxqSExtRlEKLS0tIHZXLytiWUNBeFdkdVplZWh1UDFV
            UXBPa3R6SzgxdGJOOTlmS2o5ZGQ2K0kKfMzDjldA3WhQhcXQVmdtACpzCa29SLO5
            RcTYua7HpOj9R/b8IPkv/lao0RKtgHPh4fwoSwOcKi0iwjmoPnIPQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVmZQcHRzdFlWalFBc052
            bi9iL0ZaSzAyb3dKc3JBM0xlV1BpWDdSVGtjCm1UNE1KaXpCOTJJV2JrY1ZwOWNj
            Si9aekV1TkdyMTgrN3c3Wm9xazduRTAKLS0tIElRd0VWUGM0djJUc0FGTklTc01t
            a1JSMm5IRUFObjZRcEFPdUw5SjAxejgK+TP6wubEdIKYu3xUrIyhY9HAE2c8OnFU
            3HfVtU9MKxfWxaa8kV9Ac+LUUQyp4bBELRQOhAjOrsVMXUd93kadhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRFhxMk1xSWtzOU85YTJ1
            empGVzVMS2lLTEs0QTlSZmN2RHV5c3hZMWlBCkhLemxLU3kvNGVWSlR3V3hWWEVt
            VEIzMkVnVEhaclNiSlJwc01hQTF6RGMKLS0tIE5SaWphMEhqK1dEbmtjQUIxb2ph
            RWV6L0NHUzBJVFJHcDRvYjkvS2lSbXcK7888cC0iUeHjIqIC78tOOvqLrfL0JWqY
            BouNzE7liDw2henyM8DdMO3ZxHWeol1uXAOLCGPId2Z0XuU6bS0DRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdm9ySXNBYnhXS1hRUWYw
            VHFiQzB5K0NRT2ovK0lxN2tqMFRDUU9WWVdVCkRzY2p6aEVnOHpFRURBeDRLakpZ
            ekVXQUtma3pvMkRhQ3Nod2s3SitFeXMKLS0tIEEvdVNOT2dmclBlb0c3U0RTRXQv
            MEJVb3pDbTNtSExycEUrMzg2QXF0QzQKhPudb67GaDcXSfEk8lY6DpFO1Md3OW+O
            3Vp2IQwfRVwY5wxKyVdNKLsx6GacHBIv12+Y/pbFX1Lt8lAGFS06Mg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
    lastmodified: "2026-08-18T09:47:41Z"
    mac: ENC[AES256_GCM,data:CD0fh73MSxfNE+xt0/KKh2Q4rxwiaRaD89HLf3nFUYDEfaP+pBQhKLHbIVKIQKKmhz2KIaos96tOMtlgOtFs6lgSQ19N2UT27SVE3AaHeTv2Cs0mafpGvqjFRD2iT+46v00+hHsX1LOUBBnIBUaqBJi5J16yahKrGkZOyi4LwDI=,iv:LKEbMkE0zL9v7+x10lt94zdZCuzCWfqwkcR3/XLYJ8g=,tag:1EGMsLd7Fh+WdBIVh6r7FA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
