apiVersion: ENC[AES256_GCM,data:sgY=,iv:TSbJjc4VUJ1xDKfXXAO45CBxchoEZ8UP1aU9oALdzyY=,tag:NPfjscUOxUGfaIlHI1Puvw==,type:str]
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:BmvGBY75/p4/mO9foDJBNK7vVlhEgZL4RcNo+BjUOTuGEJOV,iv:qBITkaCL+YA0fNHeT2IyLsbpqQ1CwTABEh8xYoAeEXs=,tag:bYyJe2xD+NCC+jNJiq7I9Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:aznrdFhlwYm8oML1EDdDI6Ff+7ntX8LdP+CAE2Uw0ZZRkOK9jYXkkxqLdos=,iv:GCSyd3EPnGzQKxljJsJszulgZCqNpa0JmOxmwNaGsdI=,tag:xLOzZiTwWedATZJTwGaeVg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:BchGP2hNwcL4ct9u6ama46Mtx9qQjSyHcvhuHygx+C4UampxzQpxyIJTKRMXUprTJtIlmmWIqP+OCiYqIyU0NuzlZCnxf7Q+7yHh+jQnMFGo2TQKgcR6tm4V2kx5VwfVsjsbg/vm30CjmgaxoaJ+Q9pH32VWuMIny8z9gIYUMBu8PubgAJJM49z8uMwHm6oC1TZb6mKJwrAx+0KmqOz4dtvYmuJWC0IjiT8HOA==,iv:2pFRSsXloNCWJ+6ZoQONbH+d3kunYm06LzP185IGBxg=,tag:KqXNbzUhuFLZpcxi4qOCQg==,type:str]
    DPOP_SECRET: ENC[AES256_GCM,data:igyFOls4WMkWTeZgdv4dyV5Tk9JNjIuaNKbDfGknOEdoecb55xk9iVAnaBv7dn4VxpgLut3LchlAIWRrllrNtK9m7LE7vxmmxutm4CTv4dlWZ5AskiwAOA==,iv:ybCuYLTRyT65W0V4qOpf/OJIDXVg8pGMgsFJtEvQ9eU=,tag:pccuyBxT3w5PNpdVs14LDg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:2budmK0afUv43v1Ryh4In67FKKW3YDZmRqrWhvCO0wHxrnmURJ+BES7geWay3ycjmBc3pnGPfWQ9cXw3Ba+yJ0tTpSEqU6D8Xd3DiEXcmOR818LAr2HrkQ==,iv:rlzlmm2Zl/knGKF31wvr+dN5dm6byz2RXjKLfmLcMUY=,tag:EMh4tzFjx+rk8QFYxS9pnw==,type:str]
    MAIL_SMARTHOST_PASSWORD: ENC[AES256_GCM,data:LJj2k2O2fR+kYhssoHEfxyJbuhx6LrqKsv035RXG2hLV6lhoeqqRmyWfP3NEPyQR,iv:mZeGLsOslEj+wofnQfp/WpkTDRmxVKYqrg8CAKBDMP8=,tag:9/eE/igJBky0oxjG1IdPjw==,type:str]
    MASTER_KEY: ENC[AES256_GCM,data:64n19KzKYOw5q7yAOw+K+sxlDeCdhd8owVoTq3CBquvFBhFuKXOjRYTuiN553PgOMcdhBO9d8WuotB2QIY7DEhKAM2/ubDALQA4yhKTa+P32nTpWh7nmzA==,iv:l/LpiW7pAtR4xATy3dUZ4FI/zHZTDU7hIa7++UZOEpA=,tag:hIdlRowIOEoE81vfamkHaw==,type:str]
kind: ENC[AES256_GCM,data:C8We0Irg,iv:47FACQOIB3EoUooC8RAzV3z+o8K6XvK5MyyBMsPphns=,tag:LNcqL0K5g8YTmKKqGIqWBw==,type:str]
metadata:
    annotations:
        meta.helm.sh/release-name: ENC[AES256_GCM,data:57a/yY2nJPJBD6fh,iv:Orx79TkbVfxFErspGXOIoDiaNsFvAH0jv2Qlcasyk8c=,tag:h7IJxUH0bgamg4taQSByQg==,type:str]
        meta.helm.sh/release-namespace: ENC[AES256_GCM,data:JcfsVPWDWQ==,iv:C9chsb+rKN8XfjwnHaw0RRztgKNrw9oufyZxpyYKBws=,tag:oHna3XUi6UnpLG5M7Jugxg==,type:str]
    labels:
        app: ENC[AES256_GCM,data:fih79RVWZ8EWMjxD,iv:WWDQG+VF9he4b0BFgvhkRS2zpaMRS/Ann4998CoN78Q=,tag:hNtvUU85KY5fuz0QEauRog==,type:str]
        app.kubernetes.io/managed-by: ENC[AES256_GCM,data:CtkALw==,iv:DC8t977ll9nRc7qTFjuXWLjsALV+hQBvSL02v9A+/eo=,tag:QOGevWhMw5dGJXOkk6M44A==,type:str]
        kustomize.toolkit.fluxcd.io/name: ENC[AES256_GCM,data:P+leTNH+lw==,iv:CNpNiWk4zHKZssXEurmNJ9Jl1TcwT7N53Dr+jRruOBs=,tag:niQ1qoGgnYkbqOGjUAuU0g==,type:str]
        kustomize.toolkit.fluxcd.io/namespace: ENC[AES256_GCM,data:OCNhSXPAnZMLAzs=,iv:cIFObnunQGOkb9iSV/WcGoj+ovUvId7vpsXsj7pgMDk=,tag:A7L2/5nf63zMbebf6BEOHQ==,type:str]
    name: ENC[AES256_GCM,data:G8oROi/sPuOVZeQ2Bsb+qw==,iv:E7gdp2gfKUB9zZH+/iUifwGAAtF92vOorKGp+DsPELE=,tag:CVTFCB0WF2Xx1rwe+x/F9Q==,type:str]
    namespace: ENC[AES256_GCM,data:X+vSp4CQ1S90mVMM,iv:nOJ0zfVG9hx6nflGr/SuNZmFS14VB0BM/kq90fYiJsk=,tag:pjBCa6THqAAPOkKrSZt2AQ==,type:str]
type: ENC[AES256_GCM,data:axyTr86m,iv:myTcY6PIcJFo6JWboLv1Jd/n0OybR7u0R+xd3P5hP8Y=,tag:lo+psmX/GMBU9+Fpsbfcdg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicGl2V3hEMHpBN1VjYlo5
            aHdyTnBpWG4rSzI2WmJNWlp4cmU5WFRXWlJ3CkgrVW8yZzRvd0Ywb3ZRMUVGRzdM
            RHNVekIrV2VvN2UxcTA5M3EwQ2hGL0UKLS0tIFk4Y3hCc2FPcXo3WSs2UGFuWTNk
            WDh1bm1hcFl1QjZXYzBDV0J2SXlidHcKMtRID4uScJ8fshTvnK6SNtqboj7b1tzB
            T95rssgzrFaBAqguuLsF5dznL+Es4xqORupMY9EYVc/PuCGX8VZ7oA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVkRtWU5NdmVUbnZlZ1I5
            dWRWZlltcjU2RFlxQ2hSRnZNQXRrcmJlbFQ0CnRyK2NCTnJRWVZ3cVRuWksreXJD
            Y3o1Y0pOSDd6emQ4OVFTaThHRThvZzAKLS0tIGorN0oxUG0yQW5YeXFHWUdjaWJt
            UmNjaVQrU3VEVE13ZjkzTE56bHNqaGsKxRp35j+EUA2MrMU9nTGtx4ZLVHctcPgo
            b1HRBjYB9mmH7zoMWbNL3kF6u4Z8NdF0BVOKfP+o54ND+SUWLOfPQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVW9mZVcwRnFib1BtRXpu
            cHNBU1dSenhqTmVMSzZKaVMvUU1QeENTVjE4CjZaZjZMZzROS3JEVG9XQ0dTcytR
            NGgyc0p2RVVVKzBaZDRiN3I2QThxQTQKLS0tIFp2ZHJrTENiSXNLQzFSOVdEdW1R
            T3BVRmR1ZlJnbG02RXdZdVhPRTNSRE0KPmu4MhoKGu6ujz+zxSBo3FHC+kMLMXyN
            56kLrBh/c67ml9UmGTpWQKuTwSk9ouCof73+gKeU4oDxq1z06964kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeHpEajU4WG9QQzFpSGh4
            RmdBa2g0OTlaUllxNUl3T0hPTE1oMDQ1dGh3CjdmQ1NOZ2V0ejhudVlJUDFQRnh2
            aXRrY3NvWTBNVzJCdlVlQWJaUnBSTUkKLS0tIEN6dVJHZVk1TW0zbTRYbWFNUW44
            K1VtaXAvUVBLZUJtQVExeU9ucjAvdjQK+kRryM28Z3Vm8HdrLGUuEl9XoFje7nB/
            jcphPRdC6W2uUUP3O7wdLAiW1uGYwrsUK71kFXAg5rPO9cgpiicZ6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aDR3c0tEaXM5K1VVOWFp
            Y2pWQ3podUFIQXlUN1pOOTBWdmx3VDkzYWp3CnQ1bnBXcTRHdnB6ODBlN3YzUTFR
            d3hCbWhqbGx5cCtueXJha0dFZXRUc3cKLS0tIHdteUQ3cTcxRjJISTladU8wZjRq
            L2tUZkxFTWw2R1dEdGZSQWdyK211eTAKlkKnZmKHbjneymSEGYShuZETuSuxdHUF
            MqIy85AStwY07YtlsUT69rjk7/MgRZAuhb7T2TuXKfGAfUnw/M2JxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUGtEamp2ZEdETkhIU3Np
            dnV4a0s1MG0xa2tTL2QwWFIzL2JvYktCdEJFCkYzZlJPM0RhczliUEVxRVBVdjUx
            NlArT3p3WHFBMVRKSTdBV3dGOFB0S0kKLS0tIEFLbkR2QlU3STVqdUlGUVUrbFN3
            Mnh6dlpFVjNYdTRUakNEbTZEUTBkS0EKaxKFZfX4gwXSvCSHdZNGQz9/wzabmpVE
            zOVXqP7xmbHcBGdr0RrBkdZJmYY6mMaZOG41K14ThDeG0n6qwhcNeQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvak5VZzArOTdrSE5MdjI4
            RzlwTWUwbFVlNVVFU0dFeFQrUytNTWtkZVVZCmNIRnppY1d5eiswTloreWlmNnha
            dkozclNnNEJoMEFLM2xHL1ExMGF4ZU0KLS0tIHhSNnhaLzJMS2E0TkQ0YkRqNnNv
            R1d2VTBYeHEvK2N0REV1cEdNTDAzc1kKQy1WLoSsbgQ25I4aqNicTDnZSvKh+yht
            jxYxz3q6M/bnWfDuLyjRygXm0UW7NSR6Mq9vYiynbkPTsLVzQlgcig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMGZVcmltcnFvV1RMeFRT
            Qi82UStKQm9sZGZJMWdEZUdxaThzcDZQc1V3CnUwc3UwdEdTZVR1Rjd4dVpaYjg0
            YVNIN3hZYkp0MnU5L1RhMGNLQmZ0cW8KLS0tIHJQRmJGTUR0R2l2dlJVVkZzZUkr
            ckVhNWRLYUpvaWR6QUh5WFUrVEY2dm8K3tZ/uHb50sWAI8VroWqJUpOjFT3VLm8F
            TaERP5XUzZXh4Oz+lxvZt1vwG6AF24mDU4IbS0X4AwshsRQSxkQDbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUmR1WWpxOUhEL2lGRFhG
            M2srL2E1UElML29lbmM1K0JGWDJwbEZPR2x3ClRuZHBBWTU4RkIvaUJwbVNaMThl
            dEtmVHVpaW4xTFZhcXl5Skgydzdlck0KLS0tIEtpaUx0NU5kVk1DcDhBRloxRjZK
            amZrejJUcHM0M3p0K2ZMUm14MkJLYWMKZwQFhZlviZB6YVFJ6zVFoq4rsNfUGr/a
            mLtzPD4o8CTQ8TMj3aQohKiM4+9fnBrIId9OzRilrBgwVDmrohPjWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
    lastmodified: "2026-08-18T09:47:41Z"
    mac: ENC[AES256_GCM,data:jPeT/QdxbHq7PHup+BUeAIQKotv+FhrlkxExrPPwk3JPX7uogqdaSQ357KsBswgHmF5sApb+MhaumckzUIU0nAKSSAQwkjfVVho8Fmm1OFMkophYJkySew7V6LULqb6XMO+ct8YcXVK914yT5E67nPxDlMK6K/GAEh6BJmUfF9Q=,iv:Vf5iKHNjpNRSWQfGNMF6nF9qhC3eWleaZEoz7vwTKe8=,tag:TPYGfRF6Qj2vVl29QLHsDQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
