apiVersion: ENC[AES256_GCM,data:UmQ=,iv:C8q+1wTJAiUdLBJ4IeaDPehNGjrktbGXlHum//49cS0=,tag:H5ChROF2nSvGnnop3RUShA==,type:str]
kind: ENC[AES256_GCM,data:PxehT2R1,iv:JVjhgwz/Gbazrl7CmnJiUPBT7QbTVcIfNprkR0Uk34c=,tag:BY7ARV2p/lJBdlAvVIw4pg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2PH04lIFmbeV7dCLSzk2Hsc=,iv:TK94gR2URWahbHwmiIlSzw8vQq7yRZFmXQ591hy4X7M=,tag:sqkvifnzkWSII5t32gre+w==,type:str]
    namespace: ENC[AES256_GCM,data:imEijBBvW1QHZcs=,iv:N2cjgpjVNrxk+zEp2WFUR0ADRGfL+Ay2X2GwUkR3geM=,tag:0uVI1+HbcRfCP5DuuXayfg==,type:str]
type: ENC[AES256_GCM,data:WvJKV7mv,iv:dHNT2uisaFIby4PnMXM1NVobzNmj5Qv7XMUJc6u0FzQ=,tag:HMQReqv+1Gcs+u9myQ2DJQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:GVL/skzHPCM=,iv:9YPlRszn6WUcMAVD7MnLD4YQhjoW4tbzM4R034EsL7s=,tag:7h7ZUNG6glosZe5rJtiKGg==,type:str]
    password: ENC[AES256_GCM,data:a+EBcpLz6yZ6XfuU46r03IFwn47FqMGHWGQiATFSTkqOtKU72OOii0CggYaCNVXkp2xd8vlBRvyxcECk9ErmNg==,iv:E8a57A1q98xK0mP2dQxClc3UUcfAEIJVGWRnRIzvZ9s=,tag:yEPT4kFBSFuBEPNv5cbLiw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNDA2SWFzekRXUjUvcElh
            TmgrYkZRQm5yaElPc3BPcE5tQWM4R2NJWVY0CjlST3B5T0ZSMUJRRUYzdU9aU0xt
            UEZxcmhoSVlqMzdMQ3NZRDdQd1Z2WTQKLS0tIEM3QytQYk1sb2tPVElQMjIzdVZR
            cGQrdklLUHVFa3hmbmtiRGlHdFZzK28KXi0K6f/adPcS4bYUQ6hWxsJ/RKwADQ2/
            jefeP1zsVU3u1K5Qg2S4HtQw6G+LTKD61Z3lHZ1veqCbLH2ERS/05A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXa2JYS0pHcytCdllOSmFl
            T0IwZkNTN0ZZV1hzalkvOGRhcTZ2VEs3TkRnCmxvRmFMTFVTUnZBcUdXM3Q0cnNl
            TnZRN0NKZ3VRT2MyeVJyYUdnL2dYTkEKLS0tIGFidjhVSE90VkJnRTFNUTkxaVIy
            eEhIMXNYTEJkZStCNkcvblJzdWZta2cKk0jEfGrQp8ze2k9x41i2WutQD8Kp5ghE
            wp5PpEQLbrZ3uF1bIU6PCqI8H+B2fKdhaccVc+3zE7Pddqpl88y3jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvd2hFOWE1bU9xOFlVL1FL
            Q2cxUlNuZGJXMVI3eVc3aXY3Q2pEWk5HOEZFCmFDVUl0cytVa2w0V1k1eXNZTTQw
            dzhYWG9pODh1TEdYTVFCNnE0UzVOZjgKLS0tIG5DQ29YZlQ2dzZSNStWeUVmeXNJ
            ZVRVQkJyOWtoYXVDbWFIVk9PTlV6WFUKm7x4TXCNp04uiEh/lv3NLIlMCYcuPDEi
            J+qzwtar8f2Sq8dbYWb+4/Y0MFR8RVbHxQ8dAm4iUzHXppomg7zyOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaWFoK0JDeFFLekRuOW1l
            c1A1RmVLdlcvSjc3TWJYcEsyYm9SemlTRUJvCmNuZ1lJNGVodzZ1U3FWQlg5dVBa
            c2N0ZGlVdUs0ZlpSY0xiRDhyMzBMRkkKLS0tIEUwM0l5Wk8xK2lIM2RmYUdIeFFa
            Z29qMkRLemd0TUN5NG1TVmYzZkxsbDAKrF0mOY8Yp9bQeMEt04MwFq8p5Ke+18qi
            uVrYgdrKYwNP36RT+kMzcYh/rzOMY03ypKYyttkZG2JGEMw+OWknPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjclBGcFNmcjBDa0VsdXZv
            aGUwWjFsYkVrT2ZSSW94bjdaa0dTVlJOS3pzCndWa2ZuSk9VZFpCQ2FxS3oyQmwy
            MVBVMkU2ZjlZanhPWi9QMGZjYUtVYjQKLS0tIDJCbnc4TG9DSjFIUVRaelFtd0NY
            blFTTml5UVdUejRlbUxwbHpLSkdMMVEK9mtPNBDT1gBk0MR2RJ2H0jp6/rWkL2NX
            exgTHTNDUp4zwp94N22GW9TDjrFDHwazSFjFQn4DSmfLMKLLhzYcTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2L3l1WTB6dnB2TEU1S3BN
            dlRUTE1oeVAzb0dyUVJxQTcrMGNxeW11RkQ4CjNYRVJRbVVlbm5TYkI5STBDSHZL
            b09XUW13K2lMb0xsVkYxcG5CWXduOE0KLS0tIEE2YlAwUmJOTHdLVWU1dTEzaW4w
            QVNvUU9aTFFUU3R0dWhIVlNPRDFDdUUKzDw6kf6xh3HbDFw98AHeA2QkeCRSTPfs
            F+L72Fy1G8WrTF2shkf3k1WeoFahZVZmA684AFTwbkkkq3S0o2bb9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDd2syQzZBdHJFN2JLWm1Z
            d2pjVTNTRHdMeUkwQXZPSjdETnMwb01Idm5VCmlIZ3YrZlB2NHUyZVhwSHp4aVVy
            bUpCcUZOS2sxb2Y4WERsaWV5UWdPVTgKLS0tIEUxcmY4VWVxMzB5TlNpUWpVeThP
            WWh1QUUvd0VmNkVqOUxxNytxNmMzK1EKmLsKb5rYz84codTAS5kZao5iPir/e4KY
            FjURiKvfq1OXDOWxsPuL9RyQmOqsUljl81Baiacb6XvuZd6LP1IqTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoc2RsM1U4ckhqN2dEZXZK
            a3hzUGoxN2Z6SWt3cXVGY3h1MFVhMU1rNHpNCjdDblhCcTZ6Tm4wTjJ0MzRCaWN2
            WkpBUWRJbG1XQndYWU9aYmhCT1ZYKzQKLS0tIEwrbnpJOGwwWXRpUk8xeGtLZFll
            VE9nYkdmUExZeUw4Sk5kSzEwZDhMTjgKxN4gGf2ibpky5a7hsMtjFD32Uoo/h8EC
            jDh71c+G2Fbz9biBbCn9ktcwk5CtWXjWEfYKfQ2NiMuG4peYAiypuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbmM1ZTJTbEROQ29OekJ1
            RDE3cVFYK2x4TGJjbXhRSkR3eVpGc0FSelFnCkxMN2RwQ3p3WEJZcWdkUVBDWS9Q
            ckRmd0EzdzMybUQyejFqRU55VWl0UFEKLS0tIDNxZkp3NVJWZzEzMlE1Q3o4L1ox
            eDFWeFd3RUZlUWRwMWtKNEZyM2Y5Qm8K5ycD2vX/+3zrIxPVRBedWX5UvuOw/myL
            hVOQZQ8V4W+tUM0UMeWC0FoPL93jGQCNgFSh+l36fu1MtxegIr9b6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
    lastmodified: "2026-08-18T09:47:41Z"
    mac: ENC[AES256_GCM,data:lbDvpYQHKPUYFZvsOJNRWBFw4XvcgHsSqtxTSFhNcYKsbnGbXvrP9mVFLVls1GEZGncosRM7qnZ0JUiqp+/zkr5+yMThPX8ER3oUBM0HRxQZOj8ouw7rSGULED2gAQ70T25TduJnjlMgqdclovuZIha7luKGYgFU0hej2mXhv/U=,iv:rCoAktw5HLMTwE1acRBcBgRuor4IItivl3vk/mTdSxM=,tag:kQYFSGj3gXaPHCVzqcIPpg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
