apiVersion: ENC[AES256_GCM,data:OLM=,iv:1xvVt7MQVbQ3TCYrfvA3Hpi36w49dgGklEcQdUoN/Sw=,tag:cCezXH8zaIvE+a5STtPfoQ==,type:str]
kind: ENC[AES256_GCM,data:wH/M5iI/,iv:2sSsqcSrS4hVWrpGUs5u7oW0rb2vYjn2q9xY3k5YI3Q=,tag:tj1cz4UydJbTLCyAGl5zkg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7VKWwJTAuWO3kHuA/1J93FaSwZk=,iv:QB11CSG4wfZ737+lWRpWnrnssz+luvykyBm1Aq71rKU=,tag:Ubmv7ugb5I/m6dTUFDPMQA==,type:str]
    namespace: ENC[AES256_GCM,data:P/FkKNB35K84jqg=,iv:YhrkcLipSyqkHTq5lt69s3Ux3mXb1AJipbcyK2NieRk=,tag:wNVaLoSoV9qt2542vzOlrw==,type:str]
type: ENC[AES256_GCM,data:mTmD2Zf8zH7+icgRUhk5blWMhcFrXjy+,iv:MoZ5sXupdvqG4qZZVsTCb+DfO6lQdO9O9TpoQCiiJu4=,tag:z7N9U8FFfYwSK5jPSZwueQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:BrnMM1pozC2LVaM=,iv:DoY5FBqLP+/o7MzZxd0Es8W1wy+7bRwbiSME/hg/qiE=,tag:0FxaqVLqwqPays0IepeD/A==,type:str]
    password: ENC[AES256_GCM,data:A3U0SmuVkpmjSMSbD7L2FpWK5p6uFE3gnRcYN6pUE9xKETvu0ahZJhINWy3K77OlvKBH7Ln07757PnjmPtKWLA==,iv:uhpQ/9II6BwlsB2vFFp2MGHw7TcqsyX6u6yhO3Z8iAM=,tag:29qfsyqgoRxptCcUIaW2bw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYXZYSTRsMWkxdnpZNW13
            aWlKczh6czlzclNpSDVIUzJmMUJNSVkxWDN3Ci9yZXA0ZmFNT09sSlBjK0wzdFVL
            cXJyeHhmYmppQ2M1TkVudU9ZQTlncnMKLS0tIEY3UFlWWDVJUzI3cWVsVlQ2akhn
            Ri9jTHNicmNGd3M4bmxTNVJ5L24wbUkKL1CGoObu59PV/u4fW6F8we7hdBEzT3B7
            loVEzcUoVTBDI6ocxR0Is9TuhR6R6Z0wzSGX9TY0O4UOk7J7DRc0OA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdXBnQzQ5ZllaclMrL09G
            S2dEM1ZVMHJJc2twUTNuMmQ3QXVLK0Y2UERNClAxYmF0TGoyTWtWS1BNWVIvK0dP
            U2wveDgvWlk1bWNCRTlTU3h4Ylp5QW8KLS0tIGJhNVRmcnpiSmZTaHJGdldkQm9i
            ZTJvazB6NHZCYkk5Y2RpY2xYQ09nTzQKMce8q+s3n2MKJqEoM+TXUo2X+9U3FaxC
            bHoc1RLbFadjaQpN4e2vGAnWlKF8qXByfl66QyssCT/yrLFHW6ndMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM3NZbm83TGN1c2hMQk5T
            YVI0d1c5RktMNVF2OEFNV1B1SUNiTTNMeENJCkUxR1VWaUZ2dTJiSzNMWWNWRGV5
            S0JlM3RXQjhNVjN1TzlHZnE4R1Y2MlUKLS0tIFJWaDdJSDNKNDV3WWRORmZvUGM4
            L3Fxamt5NHRldHUvbDVpcDhJVm1WOUUKaM2WjyCFNqJLpbxMcXIHlcIeEWGbAUIv
            KZxyPvhzqeejkE7sBahLTF3JS4euHuqZts3YFQI0Ypj2JxJV5nyPLw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tdgfvwl4qdptyvgxju3rwz9uh45hz422txzcgsrwm4f4f96x558skzxklr
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRHlFVXRnSUlaelZlUU0r
            VXBsY2hLZjZTZHY2QlRUTlZZakwxNm1UampRCkJGVng0VFl1Ym56dDIwMThoeE82
            ZEpJWmVRbWtBTHR4Y2NCRFplOWtjc00KLS0tIFVKOG53ak5ucno3TGFBeG00cmkv
            MkZQaUJxUjMwbjhoWjB2a3RWQThqTWsKm8HJeSZyMnGoW6F36GqGdUBuccLGSvEK
            iQohnqMs410yQubTdcdC6JUmCz6wLpAm74T0dQHzOtkahkdfLG9Scw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZDJKZHlCK1ovVXpmWjQz
            enR1aFhIdjJUZUNYbEFUK05iOFFBSjBzckFjCnZ1YTIzdFNhcEQyU2N6VmcvREU5
            b0d6aTE4R3NrYWJwRzNiV0hpVzk4MjgKLS0tIHlLUU9KVUN3b0d2dk56dGNvZEFD
            cHNpeFIvV1lkUGFSS2FFMEtYbUtZODQKJmiple/8jm6YzQSqcT6KkleMHO7mt+KV
            ukLFXV7kjEkYlwXFXKDIu2k7LLg/dUzDk9TGKkyarIdH/LTzJUqgNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPKzhndHNhSi83dG9RTkRL
            aDVQd2wvSW1ZQUNoMkxrVzN3d20zZ3RvOGxrCmxGQ1dUNW5kS21SdUFtYnFKU3J6
            VWEzRklCaWNHNHNJS1RlUzZLY0hFUzQKLS0tIEZscDlwSENaVitBdXdMaEs0enlT
            Vmx5NnluT2pmQ0RGajgxZWRNcXFTa2MKokW8tGaLn9U0JEjvscdkr9I2YZ7VP6ks
            AETYTgBEohDp6zZvkEdlHS2SRnJJNcIbqRClnUXPrTkMVvRB0FLtVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaVpiMUJpdDR1NFNYdDdN
            R0hOVCt4TDl4eEtJOHRHd1dqdnIyeDJST1hjCjdBMS8rY213YWdZaU5XSmsyKzF2
            L0RzSmk4TzU4QWF0d2psclQ2ektmSVkKLS0tIE5EUkJKeVJnYzlkYi9NK1cvelN2
            UkZDM1FVc2xLUTFKdGNJeDRvTnlFdTAKtrHIK2wGUJlpl3OeZyLVEPb7dDDxJNz2
            INSwSjFtb+VCi+UmXl4AhyaHvnAcmt7FyvLRtXJjHvfPCnm+QrCS3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaFZHZ3M0N2FPdHZIbFJR
            a0FCWmI5VWM3NlVJVWdPRTdkSDFFZ2pzYTNJCjFuOVlRZWVMNTQ2Y2JPTTRDcy9x
            Wk13MmxhODBEZWxlRTFvK3FzbDVtWm8KLS0tIEw4dStUNExHdHQ3anJjMTJqaG4v
            L09YaC9mNnBXUjVrTXp2Y0NRVktIc28KoyYX4iI/dX/vI0Gas861BnIkKTbIiY3Y
            XJ1T1gSyXuQW/upEKBzb1OC0IpM1QnXTYZ9mEw/CFFgSgLOMfX44bw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeTA5QytZTGl6bFNlRG9D
            Vlc1S1RJQXlVajlLeVRzcXA0dzJ3R2NhZkdvCnlGUUwwa2F2V0VQZ0hkUkt6TWtw
            NTIrNXdVeTR1elV3Z0dxRU5INUQ1ZEkKLS0tIFp3a2ZOQUtSTnpnT2RLdnZrK3FO
            bDhRZ21IdmR6UmZmZjRORkdXeVNwbjQKA1kQAoGPH01x+8RnE07lZdv1xnElFVfM
            e/m8BxOO9DylVvBHwRpEps1epREJG9PgVItekk2zoYz5YaGYwMaD1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aFF2U1h1eG5qSXNEVWVG
            cGgvUEhLbUtQM2x5ejZDN0RUWk1La3hqblQ0CmdYQ0U2VmUxVVFOdXFWckFSbXV1
            ZnNPMDJFNVJHK1JNaTNYVmVIMHJES00KLS0tIDNJMU13WjhqMHRKVkdlT2czUUhZ
            OERpWGs5VXVnSmJOYlgvUTdEbWtRaU0K7MlOMQPJa1ZGOcx0SnYtKI6Iov6tXQLI
            Ey7l1jUSRQxQWfkel9LZvqRI4OnkzSysnnhX1MGWIh24iHZTcbBR3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l5t62uzsj05pzftv9wg6s346csxyq202vxmmyyx8gwy8zu2nrfrs7v2a4z
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzd0N6RUxJUVNWZnlmUllU
            OFR3TlFTM1NnNGROaW84cWF1bGdCaG9RUXgwCjlFZ0toTkJ1dVJRbVZ2dXgrYzZl
            dEgwVXhpWTZ0emFmbkxVY3YyODJzM1kKLS0tIG5OTi9jOUR2TEFDTldHdWhVMkpI
            Qi9ZMFIwcXRsTlN3Q205eGRUS2pRaVUKEYZbIcFNFsCNkNn9/OAe0l65Is2H6PTF
            ixHNIP78i6rjTu1ze800rqa8+HgSpB8vJ0/+xs8/K9S2+iMGK63IJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
    lastmodified: "2026-08-18T04:37:06Z"
    mac: ENC[AES256_GCM,data:VOG8uoriosNRi+vo2ig/V3B822jL+L0dVU1l/2cGz0pMAKKFd8MQ31GIZqxNezcHkemyI/FOFxr8TsswcC4twao4TO5ob6ICG+9siofsp82R3JsA+gYUwa2zUfFlxSYamv3y3O6z/WcqQAOwigNWeft8O0bfe5+htPK+2tXqInc=,iv:nr6nusYd/UQISIWoYE+sA4W4HA9bhh/TK7WEzufxf3o=,tag:/+fbvUTMOgpt8ttQdWYShg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
