apiVersion: ENC[AES256_GCM,data:OLM=,iv:1xvVt7MQVbQ3TCYrfvA3Hpi36w49dgGklEcQdUoN/Sw=,tag:cCezXH8zaIvE+a5STtPfoQ==,type:str]
kind: ENC[AES256_GCM,data:wH/M5iI/,iv:2sSsqcSrS4hVWrpGUs5u7oW0rb2vYjn2q9xY3k5YI3Q=,tag:tj1cz4UydJbTLCyAGl5zkg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7VKWwJTAuWO3kHuA/1J93FaSwZk=,iv:QB11CSG4wfZ737+lWRpWnrnssz+luvykyBm1Aq71rKU=,tag:Ubmv7ugb5I/m6dTUFDPMQA==,type:str]
    namespace: ENC[AES256_GCM,data:P/FkKNB35K84jqg=,iv:YhrkcLipSyqkHTq5lt69s3Ux3mXb1AJipbcyK2NieRk=,tag:wNVaLoSoV9qt2542vzOlrw==,type:str]
type: ENC[AES256_GCM,data:mTmD2Zf8zH7+icgRUhk5blWMhcFrXjy+,iv:MoZ5sXupdvqG4qZZVsTCb+DfO6lQdO9O9TpoQCiiJu4=,tag:z7N9U8FFfYwSK5jPSZwueQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:BrnMM1pozC2LVaM=,iv:DoY5FBqLP+/o7MzZxd0Es8W1wy+7bRwbiSME/hg/qiE=,tag:0FxaqVLqwqPays0IepeD/A==,type:str]
    password: ENC[AES256_GCM,data:A3U0SmuVkpmjSMSbD7L2FpWK5p6uFE3gnRcYN6pUE9xKETvu0ahZJhINWy3K77OlvKBH7Ln07757PnjmPtKWLA==,iv:uhpQ/9II6BwlsB2vFFp2MGHw7TcqsyX6u6yhO3Z8iAM=,tag:29qfsyqgoRxptCcUIaW2bw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBud2RIcC83dHgvbGdsWXpX
            ZEFjeElkZmxOZGp4R1crWTE4VjZFZ2lQeVhFCkxmOEVNU2N0NmI0TlpjbVBSWlBG
            UmQ3Uy9Fd1pGWlZaekhrVFZ3Wkw4MWsKLS0tIEVIUDJPdVRVKytkVlBFSG5IS2ls
            Ymkzd29VY2ppaC9EbkdUL0NtMFNOZ1EKnWbubDb1aTxmq2PGVVHItm9brmYxd1xJ
            K2uCmLqiSbaKpdNb0qo/6RLyYphRFHjxYHSzEscLesDPjhqfZTxayQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kny9hv9t64ge379mk977slfx8deqy3df0c4cydh0lxu4ffczkftqpe2x6g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZHlwOXg2RUtDM3JkdHVa
            aHNIOGhOSkZURXhSanAvSURJRk03U3UwQ2pFCnd2QjhzOXBwN3BiVXFsa0ZLcVoy
            ZUltaUdPOXNlWXgrbHNwUm5xZnhqUHMKLS0tIENLM3pIaTZMbkw1M1BvN0pyUGFt
            eG5LR3J0ekZ3T2lWT3dabVZ1dVlSK1kKkUqPiGCRF00Sd4foN8Swb+P1plX9l5h4
            SCOXy12qtoooQe40zUYNhLjJmV/K8epP1Fj7I8H26WhZhxWldifVag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MktsUTEzSUdlZHN3bTdH
            OUgrRU1NODlYb3p4bFlPNGlscDY2eEFudkM4CjhpRkhtVHVZYnpUZm9JSTUySGo1
            amVPMHVvbWYwNUJaVGRGcm5mNWZNNUEKLS0tIDI5MWhJSll6UFhTc082ZzBmTXJw
            KytGekhvOXhuQkFwRE56a2xUdlVEUXMKEFJbLZXQ0f6s0SHdVhMirKeDHly43lOz
            WKYR4owOMVTUVf4rzRfc7Yr7+VVcsOVzMC8SihdCABolA4buze0uow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjR29veU5RWXo4M2hGYXVP
            cVRocEtCWk5zNXRvVGtobVNwa0VmU0x0bWtnCmFJMzhJZnJna1BmMG1rZlJVMW1r
            VDFsR2xxb1R5VGxDdVpxVkgwb3hhcUUKLS0tIGlUSUdYQUIwT2hBdzZqV3lMVE9K
            ZGQ4d0U1MUFabWdWZkc3Z2d3YSt0SGMKNNerM4tKNlgajxXYBUrZZBSit4efBNxp
            w7e1nGj3oCjGGdH3h2OEAGMZ95GEr0zRiee9Pdzyx8XgFuL0mC9wTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZDQzMk5FWFlKMkQ4VVBT
            Ui80MkVtTjFGZG8rOXNoSm1mTnJxeWhTVXpnCkxPTllDWTBkUWZYYjNyUjlKOEFM
            UEo4dDYrVlVteFFZVnBTUTRLaU1UQ0EKLS0tIGZOSXg4N3h1UTZPZi9IcmVjblNp
            d1NBNWx5dm81ZUNpbm5MSzloU01NNzAKlKAdnzxEUr+JT9k5P6hANmD/e1th4Sd/
            eTaExpcipSxT7ygoh252lbRc7h5VK3RyvQknAL7ieUw77OH9DYPhKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNlZrR2NDVzgyVE1ucXRl
            alZCd0lzbktqV3JMY05QS2NsU044UklsVVRZCjJUVjA0S3V3S1pDVWFnQzA5L3Ur
            QU11Mk5qSkx6WTdNRkd3bjBoQ0FhRzAKLS0tIFNta0NLcXMwZEtEVUxMTytBSHNQ
            ckVzQ0JhdDZkL3pqeXlNZTBuak9JSzQKzq2Mexhg7pJ4AAWmeKgfNSB8ird/jg54
            VsNmk4mtSirrPOz/sqgT0705e3gv/IQjSkMzFYiZoZ+/6cotv3ClDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hhvzccxzrysq6ak2ktuks00vy3smr6rhey9swhncq8850epftpjqt3c7f3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOaDNCM04vY0wwTHhvaEdL
            azhNZS9rb3J2MHBZb1hFazNBVmc5Q3EwTjJVCmdRV1RrMTJvc215QVhuWUd6VmRW
            cHFXcXZmcW5vT20zb2d6MXpzZHJmTUUKLS0tIHRkb3BucEs4MXZRRlVKOUw3NUVJ
            Q29qSnZrVEI2M3dZL01iUU1VNXJlbzgKDzUrJDMxLb2zCaxj871J5kZ5Azhhc33U
            o4BKBlSjEmoVj0qvoLWZdIGScBIw17W+xE2+LHc8IvJ21eIbr/vUgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNWpqTGU5VXpnN2puM05S
            ZUJoZ0F4OW9RcDZMRHdQcmg4aGw3M3pZdXhVCm5MNm93TFBTZVJvMEM0a3lZMERB
            dW5odVFyZG1jZDZhb0h2Zmd0MGFqdmcKLS0tIC80eHlUZ0ViODBPZDlQSmx1aTFO
            bzQxSXNiUjVBMllnd2dmVlh1Qyt3VlUKBTTr2fZF6+MNvVEZRMjp92t1v55pDXGX
            vxXZmDIscAkyisEwyUT9NyVlBRmjFm9wjnn8TiIjwVjp6nuvRG0HCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v4x5alkmvxsx5jsrwpecx0tne0ch2rwfkk0rq5w8x578j2pf5urssg5gx2
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYWR6MEt0a21jWFRyUFRP
            dGJSeTFqN1N6eXMrcHpwUnYxK3NXN3E5NEdVCi9MU3p1YXRJMG9qbjZDNG1kSWpk
            TlYxLzlwZnJvaGNJd0gwZGdNYnBNbEUKLS0tIEpYVmlndnNOSDRKZksxL1graU0w
            N2VodnhzV1VoWUd5T2tqNG9NcnV6KzgK/dWCwGdL7BOv2YsZFVP6JDh6NDi7QZgc
            0gFurngTgFd7OCTxR0UW/Fc6tsVMFbLeNDpDSa94QPPjJlSPeJwKJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl6m6gpea4kxr53c35y2tp0dd26nz8jurd7058nf0fmf2wqzxu0qsdg2fk
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZXdIaGdOMmpkMkI4eWZn
            TlhuZUFoSnUzOGtITjk5T3BFWlVXY3JSYXdRCmlxaUluOHl6SlpFQzlVUkg3VGdV
            L3dVdkNJbURKTUJxZGxJM3JFRzJjYzAKLS0tIFZGTnQrZExLUUYyQk1oZVloYVRE
            ZnpwT2hoUGVxUmpxcVB3WVBqS0JqY3MKo4cQmcMlRC2+2rAnb/xvNBRHD/q9sBHH
            dzYnsIFk6pj2YiaMqEs5/DoEReSBxOfImWYtWViDnFKduDmsN7e6pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObXdJQlA3NTN6elZKV0tW
            UTY3Sk5BbTEwMHB0dXMybUVWLzg0SEhZSjJVCmZSY2UzaGtHZ1ZySWZsOXZQNFhk
            QVhoY2RueFNWRU1ZMHZ5bFJpVVlPcWMKLS0tIDhQcFRidWZaU3BtSFlQY1N0eGth
            aDE2VlV6Z3ZlbTZZL1V1QWZzMG1rMXMKZtVRy67RCpU0LpRaRiq0u3kYge539QY9
            8CuLzIpHtOOQ5abTo60tL+0OghdWRibBRTXKrvy/L6JDZsNMhx33Tw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1su5lre6favcv6gdc50yh7ecv33qgfp0tm6klunpuasa3q79kmqtsykaq0d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RFZLajJuNFJmclFRYW5W
            eklQeDg1RlpiTkJGb0VjdFk4MHhncnVVVGxjCmdyaUdoSHNYMGVpVzZnZzJJZko2
            WXdzdlNydU14R2lKNUhXVXZkcCtqVVUKLS0tIG9JUCtPVForZW5lZXJLSlpBSWtz
            cWRoazlvTXFydFZxOG5MR0lRU0k1S2sKkkFiuJMei9ARJJ9CMMZLjqMKNzl/dge9
            AL+F1vriU7vduJCM+YahCdUF/yltQoxW7EKvAN9/EHvVQrWbeAFbig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVFUwRVBFWG1OcFFFaWw5
            R0hhcjdhQ25sMWptaEgvay9KWHJSRmdIU3l3CkRzVUhML3hSSjViMURZMGlZbzRL
            QVJ0THVMOG9uZ0pvWDd0QVVBaXBiUXMKLS0tIHF2SUF6cGRyYm92Tk1jV0trbjBH
            YWVaZHFhaXowNmU5ZlJkZHlPNXpKOXcKWzOXZZfdvxXsES7TGIpcMg+q5a97LQeH
            MwpY+bNFhZO2hVs40G+ttX4iQ0F6T0Ivi1fC5Ln7pJ7utEYfnc93mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1axn36h9356ena7rq6y2xa4rcm250w9h0m9pz6x0677gla0v4f4dsj92yfm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZUpNY09RdHB2SW1KM2t2
            UDdjaVBmNjcyaEhMaGtaaVNKMU9jbFdvRTJZCnhUSnllazg2MkhVSThiMld5NHlU
            RHpzMWEvZTI3ZmlwNEtQWXNxd09RcXcKLS0tIGgxRkJDa3c0aGVCbS9iY2NEcXl6
            Q2NxblNtTm93MDVERVUzdGFZUmlkR1UKnmqKekuQpvEupbv/4xB35DEaiXBWROIC
            tlDkbUIiCH7Nmt/ZxquXDPT0wP2GOV5PlCRYAUD1OtGul+PNtb/LTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kgp3x48wn0dmzwqp0vdpfsdw42rej0ypkj0qavs7c2t2tgdud5zqcmhl40
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcEI5dFhmMHZmZnRDYXRD
            WVF6OGpHNXlEWWFhVG16ek1sSi9aTFppLzJrCnd2dnpZR2k2NEorVGdCVGVwSDVv
            TTRGYklhbzZiR2lERDViKytsai8rZ28KLS0tIHNkc3ZQSm1MUldCOWExdXlyckZW
            QlR0TlBKNnJJZU1ZSTRLUU9iT0hGT1kKvo0DD+ryl/mumqUY3ezXQ6+P29o3y1+m
            0uIp7Xbe7gWhoCjm6y0ilqbsluF2ZJVbq4kngo+AMhvxeip6fLRHLQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c62ajygt7yx5k0f85h6w3tquu4ak0gg5c9drrhh34yyyea3xtpas8knau3
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUWc0bDE3R2NXMGtBdzln
            aDhHcFBXeHhVWmpaS0ptZG84aG5ibWFYQmtFCmpHZTVDS3dTSXFmUEpOV0xBOEtG
            WFRoQ09tbkQxUFZES1R0c2RmYktZVjgKLS0tIC9LZDJEamdHWWIwV2lxZzQzNXdG
            Znh4aW14NExFVm54bmtobW9lWDk2VWMK9BTTdAGd1SN43IG8HUPunnYvAtDU/0xu
            oBc/+SpPF5UUMo04jR6kIKmkfZo5fYR5FOBfNZNZh5ZB7gbN836rNA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gz3835qckr54gn44znlefa6m7yvjx83gptq8keslyq944nfxsfzqndenmt
    lastmodified: "2026-08-18T04:37:06Z"
    mac: ENC[AES256_GCM,data:VOG8uoriosNRi+vo2ig/V3B822jL+L0dVU1l/2cGz0pMAKKFd8MQ31GIZqxNezcHkemyI/FOFxr8TsswcC4twao4TO5ob6ICG+9siofsp82R3JsA+gYUwa2zUfFlxSYamv3y3O6z/WcqQAOwigNWeft8O0bfe5+htPK+2tXqInc=,iv:nr6nusYd/UQISIWoYE+sA4W4HA9bhh/TK7WEzufxf3o=,tag:/+fbvUTMOgpt8ttQdWYShg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
