apiVersion: ENC[AES256_GCM,data:OLM=,iv:1xvVt7MQVbQ3TCYrfvA3Hpi36w49dgGklEcQdUoN/Sw=,tag:cCezXH8zaIvE+a5STtPfoQ==,type:str]
kind: ENC[AES256_GCM,data:wH/M5iI/,iv:2sSsqcSrS4hVWrpGUs5u7oW0rb2vYjn2q9xY3k5YI3Q=,tag:tj1cz4UydJbTLCyAGl5zkg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7VKWwJTAuWO3kHuA/1J93FaSwZk=,iv:QB11CSG4wfZ737+lWRpWnrnssz+luvykyBm1Aq71rKU=,tag:Ubmv7ugb5I/m6dTUFDPMQA==,type:str]
    namespace: ENC[AES256_GCM,data:P/FkKNB35K84jqg=,iv:YhrkcLipSyqkHTq5lt69s3Ux3mXb1AJipbcyK2NieRk=,tag:wNVaLoSoV9qt2542vzOlrw==,type:str]
type: ENC[AES256_GCM,data:mTmD2Zf8zH7+icgRUhk5blWMhcFrXjy+,iv:MoZ5sXupdvqG4qZZVsTCb+DfO6lQdO9O9TpoQCiiJu4=,tag:z7N9U8FFfYwSK5jPSZwueQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:BrnMM1pozC2LVaM=,iv:DoY5FBqLP+/o7MzZxd0Es8W1wy+7bRwbiSME/hg/qiE=,tag:0FxaqVLqwqPays0IepeD/A==,type:str]
    password: ENC[AES256_GCM,data:A3U0SmuVkpmjSMSbD7L2FpWK5p6uFE3gnRcYN6pUE9xKETvu0ahZJhINWy3K77OlvKBH7Ln07757PnjmPtKWLA==,iv:uhpQ/9II6BwlsB2vFFp2MGHw7TcqsyX6u6yhO3Z8iAM=,tag:29qfsyqgoRxptCcUIaW2bw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnam1YZ0x6Y3A4Z0lvWGFX
            ODRRZFhSU2Y0bXkydnl3Z0NhNDZ5T1lyUm5RClVBTE43V0FLa2J6Tk54MTVIdXlp
            Njd0ZkpsQXhPbmNhcHJOZjlxcXI1Z2cKLS0tIFF4UVJySE50L2hLamhSVkdiTGFo
            T3hzbWhmajgyWVdnV1VFUUtyQmJ0R1kKgCQYl/nMvUd947m5wfdebnj1rZFZSVg7
            zutxyFWgwGyJCL2QKf9OWwIsjHPm2JiXveT8rk/8kqKVwWWbSIPH7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tgm3rcc2glqjxl5al2r780aweywv5tc2u065fzqlntwjzws4kckqepz7nl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aCtnTnhWVllRcFZpSFZZ
            RG5aMk9ocWJUdG5VQ2dITHZaUGRTenkzMDJJCmFUSzhhQmlmd09XY1k0R0ZJdDA4
            UmtyQ2lWZW1DT1o4RWN2dVBIQU12QUUKLS0tIDhDWmttUDM0NG52YzJHQ1QwMXNQ
            UDZuZkkwd01JQ1BkSm10OUpXSXhvY0kK2rXMQcxL9IkwOw2GhjzCSp0VxNzAT8iV
            oz1+ldBcOtcdbjfh7eo5evj32eG39yiTjw05zeIsPMvCXhpJGhzngw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1e5a0aaueyk34klry2qk094zrwfsvga0uft93mwweye30xhqhvfzs3jgqku
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOEYwVmh6OThBQjA2cm05
            WDFRWEVUTnhDMVUwV3FFbHZwdmFVcjI5R0drClZWTFVkWXpFWk9sekl3MDBmWGFw
            WjdjYkwxbnJESnBmNXJxRkFhOEk1QW8KLS0tIGQzbFJIUENFd09hdFFjQm5xdCtz
            b09mVEszRzNYeXFDcytRZ2RQdnJIWXcKfgGPVgj9XhvyfzVCDW31O/PC+OMCMB3E
            4fiyRgXWYHnf4fc3mndBmWxtzVqY8KII8bvgStxUBKoDaGoI6XrM+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1876lthmlfq2aq6nm6z2qyu0ed4aa5ss68xvnlw5cqxcdtzslaqrqzgcmlm
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUFN6RjFoc1JIS0htYmtq
            dGVHMVBCZGtuZGMyU0xBTTZzK21HejBoTlhFCmtmREV2bGJ4OVJCaTFqejNPTTJS
            UW5MbmdNaENnK3U3Rkw5NjcvZlRwOE0KLS0tIEZVTE1SUTlkTU5Yb2Q4UTEwdnc1
            bFVRb1c4Q0FqdDJkRnpmWlkzcjBvUlUK/Uwi7prKkSsWL5HX1X45AX5ZcNWbMnMJ
            ArcfHWoXJWJnFx2dBcAQ6BF5xTy0ctH7cFjO9G3Vxsuqp6F7wJQWvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1j9jju3whwj72udhge7v4c77gk6v6w2cq8zjngzyppwtptfsz499qyywu9a
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MVhOMGhIQ294NVdnWmhV
            b05Oc0ZIVElxQlVIa0JMNkg0TGJXbzRaSGhZCndweFExQ25UcWllU2tFWVVOUnNy
            bTl4UVhFN2k0a1pkMk9pdThrZjJOemsKLS0tIGkrZkpNNE05NzFwMzJNUVVRV2lo
            c0dPOHVJVHhBNE9kY3B3NHU2cFNKZDQKTby8xSR/jqHVjyd0D5XvqdVMoU5sEBJn
            Dz+w8q3uz82ezFW8RSBZvcPBCno9ZXZ2ik7D9K4/+uj2Y4r/hJNKiQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age162sx8kppp90mjxw88eqs78hgnpkddf8k9kgtksmmexzvcdxknpkspmkgaf
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWjV5bkxhRWRMcDVmWHd2
            TGZLZExKbmVFcnZBNjlpdnZRWS9YRlFiVVVZCkRQUGNvemVvTE5BVEtMTzFmTFpi
            ci9lQmxlbzE5TklXc1VPeWdoZ1J5SkEKLS0tIEhpV3lRN2s4VzJuUGZnVXJnZXdM
            WmpjSHRmcGZzaklzZ280Y3BnRXB3a2sKNA1GzpTNNIrvOI3Wd5AsVEOqHUQ5N/oT
            wOkoSmdnl3S6WxP1DnQn86LbOK8Q37JKWe+vMDXb+0DdVP5NeajsrA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fczwtlqdqq7pjyzna2yl9nvmhpe68zk5k6nyn0dt4sp0lts04anskhcmu6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2amxBWDNBcEJOMmp2d2NP
            akpBVzNwTGtRZjlEaXRGY3lEVUhoMnR0QVQ4CjU5MnVCVFNvdFU2aGNoR3hZMFpm
            cFRER0tKbDZuQTdsbm5GTlVCWE1ucVUKLS0tIFlHRVR4VExIYjVhS3JKSkVqMFZw
            RHcrWlFjdGMwejhQK2pmUWpNYlhMeDAKD5M+zJ1XcFeeTEZWwW37Njn5pZIlQhSi
            V+bIsmoq2hEulss5rEy11QGzHxh2PT/HZMJqabf2adbTP7evdY7tIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15td0jk5e2qeq2pexvxguhuuaxuaa7nhql7mhx9jr79caska6t4pqdv5spl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCM3VzMUVMTEdKeGwvRHhn
            Uk5GSmUrWmdjb0tkZWpodGtVamNaYmhtUXowCnZ1djRpTkZ6d0lpcUZkeUJIVjRo
            RkFtc1BvbnU4WnZUK3oxeHc2MTBsRFUKLS0tIFlDekVhVlpVRXJJL0hjWXhjVWt1
            a2RTQWdHM2kzV0FpYlNFc2dRSzVVc0EKzik9kErIGSfdlSQfMWDttD+Tz/5OJDgw
            nD2jONpaObkXPaInj5pObHBQdS3h8cAhmvpIpdgBDkpDe/7k+F9Vjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age157en2pt286a22pxzyugt84ak6rn2at89tpma88juqfgj84lme5csq4999g
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cmhzdUQ3aWJwT2J0bUcy
            SWl2RVFNS1FVZE5xdExsano0dnIxT3kyR3pJCjhzblFyL3N4cVUzY0ZjMllwbFBH
            ditiZ1VDc3crcmlHaU9zeHNUeTlhOVEKLS0tIHo5TXA0MFJjY05ybVl3UktMMElP
            T2dYbEZCSWZURnR4TTZLZ0lqcEpnZEkK4eEeMykaMP5vlWT/AUb8Wsvg1bB3bjDU
            GUTmMtgSqSw/CSQU4IP7YJU8YzVowqvPh3SnBtEcQgQpiHk/arEkKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14pn3ukj9n38lx7fxc07qgdx34jedwrx8vhve5x06tyanff7hlgws3xgpvn
    lastmodified: "2026-08-18T04:37:06Z"
    mac: ENC[AES256_GCM,data:VOG8uoriosNRi+vo2ig/V3B822jL+L0dVU1l/2cGz0pMAKKFd8MQ31GIZqxNezcHkemyI/FOFxr8TsswcC4twao4TO5ob6ICG+9siofsp82R3JsA+gYUwa2zUfFlxSYamv3y3O6z/WcqQAOwigNWeft8O0bfe5+htPK+2tXqInc=,iv:nr6nusYd/UQISIWoYE+sA4W4HA9bhh/TK7WEzufxf3o=,tag:/+fbvUTMOgpt8ttQdWYShg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
