apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: pg-shared-backups
  namespace: cnpg-system
spec:
  configuration:
    destinationPath: s3://aly-backups/sinnoh/cnpg
    endpointURL: https://s3.us-east-005.backblazeb2.com
    s3Credentials:
      accessKeyId:
        name: pg-shared-b2
        key: KEY_ID
      secretAccessKey:
        name: pg-shared-b2
        key: APP_KEY
    wal:
      compression: gzip
  retentionPolicy: 30d
