app:
  name: ""
  port: 0
  image: ""

database:
  secretName: pg-shared-app
  mainDatabase: ""
  logDatabase: ""
  environment: false

legacyConfig:
  path: ""
  format: xml

config:
  storageClassName: local-path
  size: 1Gi

exporter:
  enabled: false
  port: 0
  image: ""

resources: {}
