app:
  name: ""
  port: 0
  image: ""

database:
  secretName: pg-shared-app
  mainDatabase: ""
  logDatabase: ""

legacyConfig:
  path: ""
  format: xml

config:
  storageClassName: local-path
  size: 1Gi

resources: {}
