apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: nextcloud
  namespace: cnpg-system
spec:
  cluster:
    name: pg-shared
  name: nextcloud
  owner: nextcloud
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: paperless
  namespace: cnpg-system
spec:
  cluster:
    name: pg-shared
  name: paperless
  owner: paperless
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ombi
  namespace: cnpg-system
spec:
  cluster:
    name: pg-shared
  name: ombi
  owner: ombi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: pinepods
  namespace: cnpg-system
spec:
  cluster:
    name: pg-shared
  name: pinepods_database
  owner: pinepods
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: pocket-id
  namespace: cnpg-system
spec:
  cluster:
    name: pg-shared
  name: pocket-id
  owner: pocket-id
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: bazarr
  namespace: cnpg-system
spec:
  cluster:
    name: pg-shared
  name: bazarr
  owner: media
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: lidarr-main
  namespace: cnpg-system
spec:
  cluster:
    name: pg-shared
  name: lidarr_main
  owner: media
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: lidarr-log
  namespace: cnpg-system
spec:
  cluster:
    name: pg-shared
  name: lidarr_log
  owner: media
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: prowlarr-main
  namespace: cnpg-system
spec:
  cluster:
    name: pg-shared
  name: prowlarr_main
  owner: media
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: prowlarr-log
  namespace: cnpg-system
spec:
  cluster:
    name: pg-shared
  name: prowlarr_log
  owner: media
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr-main
  namespace: cnpg-system
spec:
  cluster:
    name: pg-shared
  name: radarr_main
  owner: media
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr-log
  namespace: cnpg-system
spec:
  cluster:
    name: pg-shared
  name: radarr_log
  owner: media
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: sonarr-main
  namespace: cnpg-system
spec:
  cluster:
    name: pg-shared
  name: sonarr_main
  owner: media
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: sonarr-log
  namespace: cnpg-system
spec:
  cluster:
    name: pg-shared
  name: sonarr_log
  owner: media
