apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pg-shared-daily
  namespace: cnpg-system
spec:
  schedule: "0 0 4 * * *"
  cluster:
    name: pg-shared
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  backupOwnerReference: self
