apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: flux-system
spec:
  suspend: true
  chart:
    spec:
      chart: ./k8s/charts/plex
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
      version: 0.1.0
  interval: 30m
  releaseName: plex
  targetNamespace: plex
