apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  namespace: plex
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tautulli
    spec:
      nodeSelector:
        johto.narwhal-snapper-ts.net/workload: media
      containers:
        - name: tautulli
          image: ghcr.io/tautulli/tautulli@sha256:670e68dd9efca538d508b0c5b222b7e41bd70a22dce0cb822941ea55c457f5d1
          env:
            - name: PGID
              value: "100"
            - name: PUID
              value: "1000"
            - name: TZ
              value: America/New_York
          ports:
            - containerPort: 8181
              name: http
          readinessProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: cache
              mountPath: /config/cache
      volumes:
        - name: config
          hostPath:
            path: /mnt/Data/apps/tautulli
            type: Directory
        - name: cache
          hostPath:
            path: /mnt/Data/cache/tautulli
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  namespace: plex
spec:
  selector:
    app.kubernetes.io/name: tautulli
  ports:
    - name: http
      port: 8181
      targetPort: http
