replicaCount: 2

image: atcr.io/tranquil.farm/tranquil-pds:latest@sha256:c0cf3c0e63efbda82dbadb0d78d3b58d75d23253462320d81ef43edaa5478451

hosts:
  - pds.cute.haus
  - aly.social
  - "*.aly.social"

publicIngress:
  enabled: true
  clusterIssuer: letsencrypt

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi

valkey:
  storage:
    className: local-path
    size: 1Gi
  resources:
    requests:
      cpu: 25m
      memory: 128Mi
    limits:
      cpu: "1"
      memory: 512Mi
