apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cnpg.yaml
  - gotk-components.yaml
  - gotk-sync.yaml
  - ingress.yaml
  - letsencrypt.yaml
  - media.yaml
  - private-ingress.yaml
  - secrets.yaml
  - tailscale-private-ingress.yaml
  - tailscale.yaml
