apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  - cnpg.yaml
  - barman-cloud.yaml
  - gotk-components.yaml
  - gotk-sync.yaml
  - ingress.yaml
  - immich.yaml
  - jellyfin.yaml
  - letsencrypt.yaml
  - arr.yaml
  - nextcloud.yaml
  - paperless.yaml
  - plex.yaml
  - pocket-id.yaml
  - postgres.yaml
  - postgres-backups.yaml
  - private-ingress.yaml
  - secrets.yaml
  - slingshot.yaml
  - tailscale-private-ingress.yaml
  - tailscale.yaml
  - uptime-kuma.yaml
  - watsup.yaml
  - ombi.yaml
