apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ombi
  namespace: flux-system
spec:
  dependsOn:
    - name: postgres
    - name: secrets
  suspend: true
  interval: 10m
  path: ./k8s/ombi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m
  wait: true
