apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: postgres-backups
  namespace: flux-system
spec:
  dependsOn:
    - name: barman-cloud
    - name: secrets
  interval: 10m
  path: ./k8s/postgres-backups
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m
  wait: true
