apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: immich
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: immich
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      enableServiceLinks: false
      nodeSelector:
        johto.narwhal-snapper-ts.net/workload: media
      containers:
        - name: postgres
          image: ghcr.io/immich-app/postgres:17-vectorchord0.4.3-pgvector0.8.0@sha256:0baf4cde9b54d8d7dc6a6ad8d8c43c3c6b884f82e1c2a023d571414820e39336
          env:
            - { name: PGDATA, value: /var/lib/postgresql/data/pgdata }
            - { name: POSTGRES_DB, value: immich }
            - { name: POSTGRES_INITDB_ARGS, value: --data-checksums }
            - { name: POSTGRES_USER, value: immich }
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: immich-env
                  key: DB_PASSWORD
          ports:
            - { name: postgres, containerPort: 5432 }
          readinessProbe:
            exec:
              command: [pg_isready, --username, immich, --dbname, immich]
          resources:
            limits:
              memory: 3Gi
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: shared-memory
              mountPath: /dev/shm
      volumes:
        - name: data
          hostPath:
            path: /mnt/Data/apps/immich/postgres-johto
            type: DirectoryOrCreate
        - name: shared-memory
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
